### ISSUE TITLE
Prepare for local axes

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#103]
Based on the description in the [Kratos wiki ](https://github.com/KratosMultiphysics/Kratos/wiki/Local-axes-orientation)

We can prepare an example for an element or condition that needs local axes, like beams.

I've seen that the write format is:
```json
"local_axes" :{ 
    "origin" : [0.0, 0.0, 0.0] ,
    "axes"  : [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0] ] 
} 
```
Anyway, I'll need help with this

**Comment by pooyan-dadvand** [comment]
Ping @KratosMultiphysics/structural-mechanics Team

**Comment by RiccardoRossi** [comment]
The guida should write a vector variable LOCAL_AXIS_2
Orthogonal to the beam axis as a Elemental value assigned to each beam element

**Comment by jginternational** [comment]
We are writing LA as

```
Begin ElementalData LOCAL_AXIS_2 // Element: BeamElement // Groups: Parts Auto1
   31  -0.7097014744   0.7045025318  -0.0000000000
   32  -0.7097014744   0.7045025318  -0.0000000000
...
   42  -0.7097014744   0.7045025318  -0.0000000000
   43  -0.7097014744   0.7045025318  -0.0000000000
End ElementalData
```

**Comment by RiccardoRossi** [comment]
@KlausBSautter, can u modify the beam element WITHIN Kratos to read the initial local axis from LOCAL_AXIS_2?

such variable will have to be created in kratos (actually i would create three 2D variables with components LOCAL_AXIS_1,LOCAL_AXIS_2,LOCAL_AXIS_3) since i think it is currently not there

**Comment by RiccardoRossi** [comment]
i reopen this as it is still broken on the kratos side

**Comment by KlausBSautter** [comment]
@RiccardoRossi I try to do it this week but cant promise to do so

**Comment by philbucher** [comment]
For me it still works, I just checked.
Lets have a look tmr @KlausBSautter

**Comment by KlausBSautter** [comment]
The problem occurs as soon as I want to assign LOCAL_AXIS_2 to an already meshed structure in GID. So right now it is only possible to assign the axis to a line and then mesh it. It would be nice if we could also assign LOCAL_AXIS_2 to single elements

**Comment by jginternational** [comment]
Hi @KlausBSautter , At this point, in the Kratos GUI, we are assigning everything in Geometry mode, instead of mesh mode. Let's see if we can improve that in the future.
