### ISSUE TITLE
Missing error message 

### ISSUE THREAD

**Issue by soudah** [KratosMultiphysics/GiDInterface#105]
It would be very helpfully to get a "Error message" when some condition have been not assigned on the GiDInterface.

For example, when I forgot to assign the "material properties" on the "parts", and I started running Kratos, I got an "KRATOS Error"....but it's not a KRATOS Error, Its my fault because I forgot to impose a conditions. 

For that reason, "Error messages" would be very grateful!!!

**Comment by RiccardoRossi** [comment]
Hi Edu,

I don't think follow you. The problem is that the Kratos error message is bad? Or?

**Comment by jginternational** [comment]
In the current version of the problemtype, a "beautiful" error message is displayed if no parts are assigned. Try it with the latest version
