### ISSUE TITLE
Different process for rotation and displacements

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#118]
This is pure OCD, but I don't like to have different processes for the rotation and displacement:

![imagen](https://user-images.githubusercontent.com/19991680/28427042-42701a80-6d75-11e7-83f7-4e7a367741b0.png)

We should thing about remove duplicated processes

**Comment by jginternational** [comment]
You are right. This was detected in #104 . Rotation is using a deprecated way of doing
