### ISSUE TITLE
Write condition's property id

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#119]
During the development of the DEM Application #116 I've noticed that the property id of the MDPA conditions is hardcoded to 0:
```tcl
for {set i 0} {$i <[llength $obj]} {incr iter; incr i} {
    set nids [lindex $obj $i]
    WriteString "$iter 0 $nids"
}
```

Unfortunately, DEM is still using properties for conditions, instead of the json file, so this should be adapted for this use.
Besides this, there are more properties written in the SubModelPartData, applied only to nodes, ignoring the conditions.
In addition, there is a reference in the SubModelPartData to the PROPERTIES_ID written in the properties section.

All this factors make the DEM MDPAs quite different from the rest of applications.

My original idea was to change the name of the current "materials dictionary", and call it "properties dictionary", but it is being used in all the other apps, and I'm afraid that a change of this magnitude at this point (8 days to the release) can break something. So I think now that maybe the best is to implement an 'ad hoc' write procedure for DEM, just for the release, and then try to achieve the use of json and common write procedures.

@KratosMultiphysics/dem is on your plans to change to json soon?

**Comment by maceligueta** [comment]
Right now it is not a priority. We have to deliver two releases. We can think of doing it from september on, but the team has to discuss it internally first.
I think that switching the project parameters python file to a json file would be easy. However, this json file would be quite different from the other jsons I have seen around...
