### ISSUE TITLE
Pfem inlet in Boundary conditions

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#12]
Add a new Nodal Conditions -> Inlet

Velocity in each direction.
Intervals
Material (Available in issue #13 )

**Comment by jginternational** [comment]
@KratosMultiphysics/pfem  Is there any process for Inlet?

**Comment by jginternational** [comment]
@maceligueta @AFranci @josep-m-carbonell hey! Is there any process for this Inlet?

**Comment by maceligueta** [comment]
We are working on it. It is not working yet.

**Comment by maceligueta** [comment]
Should this be closed, @jginternational ?
