### ISSUE TITLE
Pack and publish release 5.1 

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#124]
When KratosMultiphysics/Kratos#185 publishes a definitive release, it will be time for the problemtype.

Steps to publish:

0. Create a branch for the release
1. Pack only the approved applications
2. Tests will be done in this branch in both modes developer and release
3. Add a message that references this repository for developers
4. Check the minimum GiD version (it may have change, due to DEM changes)
5. Add the Kratos version in the default.spd file
6. When everything is tested, create a zip and publish in the GiD ftp
7. Ask @KratosMultiphysics/dem for a public version of DEM, to publish

**Comment by RiccardoRossi** [comment]
@jginternational i think that @roigcarlo has almost finished packing the final release. Could u create the release branch packing the applications we agreed upon?

**Comment by roigcarlo** [comment]
Give me 5 min to pack and upload the win versions...
Linux is not yet ready since we have a problem with libmpi...

**Comment by jginternational** [comment]
@RiccardoRossi I can be in CIMNE tomorrow (Friday) at 3 p.m. @roigcarlo do you think that we can publish then?

**Comment by jginternational** [comment]
Master branch has been unlocked
A new branch, called Release-5.1 has been created and protected

This new branch will have only the package modifications
