### ISSUE TITLE
MPI launch script only appearing in CFD but not in structural

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/GiDInterface#136]
also at this point it would be good to have an equivalent OpenMP launcher, so that someone can eventually run it at need from the command line.

**Comment by rubenzorrilla** [comment]
@RiccardoRossi are you talking about MPI or OpenMP?

**Comment by jginternational** [comment]
@rubenzorrilla he is talking about this

https://github.com/KratosMultiphysics/GiDInterface/blob/Release-5.1/kratos.gid/scripts/Writing.tcl#L1195

We have done an MPI launcher script for linux, not to be launched automatically from GiD, but the user can launch it manually.
