### ISSUE TITLE
Addition of MPI FSI coupling strategies

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/GiDInterface#142]
Recently we have been working on the MPI parallelization of the Relaxation and Recursive MVQN FSI coupling strategies. To be able to properly validate and to work towards the next Kratos release, it would be nice to add the parallelism field to the FSI interface.

To enable the parallelism is as simple as deleting the line that enforces the OpenMP parallelism in the GetFromXML.tcl file. The issue comes when the coupling strategies have to be enabled/disabled according to the parallelism.

The point is that we implemented the coupling strategies in a similar manner that the common linear solvers. However, the coupling strategies have the same unique name in both OpenMP and MPI parallelism. This generates a conflict... @jginternational, have you any idea to solve this?

**Comment by rubenzorrilla** [comment]
@jginternational ping.

**Comment by jginternational** [comment]
@rubenzorrilla The first step is to tag which strategies should work in MPI

**Comment by rubenzorrilla** [comment]
Done!
