### ISSUE TITLE
PFEM interface, work to do

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/GiDInterface#155]
PFEM features needed in the GiD interface:

- [x] 1. Body type SOLID:

   Constitutive Laws of the Solid application are not seen, instead there is only the None option.

- [ ] 2. Body type RIGID:

    a. Rigid Wall
    b. Rigid Body (here the parameters of Rigid body are needed):
  
       Mass/Centroid/InertiaTensor/LocalAxes
	or
       Compute Weight-Centroid and Inertia (density of the material is needed)

    c. Parametric Wall:  (Type: Parameters)

         PLANE  : Point,Normal,Convexity,Plane_Size
         CIRCLE : Center,Radius,Convexity
	 NOSE-WALL : Tip_Point, Tip_Radius, Rake_Angle, Clearance_Angle, Convexity, Plane_Size
         CYLINDER: Center, Ratius, Axis, Convexity
         SPHERE: Center, Radius, Convexity

- [ ] 3. A Boundary condition can be imposed to a Body type RIGID -> needed feature discussed already

- [ ] 4. Somewhere the Dofs have to be defined, adding a extra field (element technology: U-P, V-P, U-wP, U-J...) to write it down as a parameter "extra_dofs" for the solver. In fact, elements are the ones that know the DOFs of the analysis, after assigning all parts the number of dofs could be extracted from elements, the interface has to do this search.
         
- [ ] 5. Contact strategies and Meshing strategies must be moved to Modelling tab in the same level as Analysis type

- [ ] 6. Start to introduce some configuration parameters for Meshing strategies:

   Meshing_frequency
   Constrained
   Mesh_smoothing
   Jacobi_smoothing
   Refine_parameters:  remove/refine  domain/boundary

A json file is provided as a guideline in the "apps/Pfem/write" folder, the following corrections are needed in the current writing of the Parameters.json file:

- [ ] 7. No "remesh_domains_process" must be written for Body type RIGID. Instead "parametric_walls_process" for Parametric Wall, and "rigid_bodies_process" for Rigid Body or Rigid Wall must be written. 

- [ ] 8. The Body type RIGID is not a "meshing_domain" when writing the "contact_domain_process". The "contact_domain_process" must be written only if a Solid Domain with contact is assigned in the model.

- [ ] 9. When a Parametric Wall is assigned, "contact_search_settings" must be written into the "parametric_walls_process" with the parameters of the contact strategy selected.

The most up to date branch is of Kratos repository to check it is solid-mechanics-develop (from https://github.com/PFEM/Kratos.git)

**Comment by jginternational** [comment]
Ok @josep-m-carbonell 
The first step is to merge the branches of the solid and pfem development

**Comment by josep-m-carbonell** [comment]
@jginternational  merged and pull requested #157

**Comment by jginternational** [comment]
I'm starting on point 1
> Body type SOLID:
> 
> Constitutive Laws of the Solid application are not seen, instead there is only the None option.

This is not working because the filters in the Elements.xml file does not match with the attributes in the ConstitutiveLaws.xml

For example, the element UpdatedLagrangianElement2D is filtering constitutive laws with this parameters:
``` xml
<ConstitutiveLaw_FilterFeatures>
      <filter field="kratos_module" value="SolidMechanicsApplication"/>
      <filter field="Type" value="PlaneStress,PlaneStrain"/>
      <filter field="Dimension" value="2D"/>
      <filter field="StrainSize" value="3"/>
      <filter field="HybridType" value="False"/>
</ConstitutiveLaw_FilterFeatures>
```
And there is no constitutive law that matches all the filters.

**Comment by josep-m-carbonell** [comment]
I see @jginternational. Kratos module is wrong here. I will apply proper corrections. Please, keep on advancing in the other points.

**Comment by jginternational** [comment]
@josep-m-carbonell at this moment we can not handle so many Constitutive Laws called with the same name. If you see the last commit you will see that I've added numbers to the J2 Plasticity constitutive laws

CLs can have the same name if they have different Dimension, because they are filtered using that field. this is due to a customlib issue: internal name and public name are mapped in the "dict" field using a tcl dict, If 2 CL have the same public name, it gets a wrong value.

I'll work in a solution from "our" side, but it can take some time, so I prefer to change the names now as a patch

**Comment by josep-m-carbonell** [comment]
I have not experienced the error, in fact if they have the same pn is because the law is the same but duplicated to get the correct filter and specialization. Maybe we can think about another way, an easier way, to write this xml without duplicating things so much.

**Comment by josep-m-carbonell** [comment]
Well, the numbers are a temporary solution that must be solved. I have also seen that parts disappeared from bodies. It says bodies instead of parts. Is there amy reason for this?
