### ISSUE TITLE
ImportError: No module named 'assign_vector_process'

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/GiDInterface#156]
I tried setting up a very simple fluid case (see attached).
Specifying an initial condition does not works because it does not find the process.
@jginternational do you know a solution?
[fluid_case.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/1374906/fluid_case.gid.zip)

**Comment by jginternational** [comment]
I’m testing it 

Ping  @rubenzorrilla

**Comment by rubenzorrilla** [comment]
@philbucher, at first glance, it seems that we did not remove at all the old processes dependencies... I will try to do it ASAP.

**Comment by philbucher** [comment]
@rubenzorrilla thx, the same happened also for some normal inflow conditions. I think you have an inlet process for this now in the FluidDynamicsApplication, right?

**Comment by philbucher** [comment]
@jginternational another small thing I saw is that in a structural case you write the 
```

    "material_import_settings" : {
        "materials_filename" : "StructuralMaterials.json"
    }
```
twice, once in the solver settings and once again at the end of the file. Only the one in the solver settings is needed/used. At least atm
@rubenzorrilla do you know the final location of this definition?

**Comment by rubenzorrilla** [comment]
@philbucher In depends on where do you want to build the CL clas... AFAIK it should be done in the solver, therefore only the one outside the solver settings could be removed.

**Comment by philbucher** [comment]
I also think it should be done in the solver
maybe @RiccardoRossi or @loumalouomega know more?

**Comment by jginternational** [comment]
This is solved, isn't it? @rubenzorrilla

**Comment by rubenzorrilla** [comment]
Should be.

**Comment by rubenzorrilla** [comment]
My bad, should be as soon as I merge the interface branch I'm working on.

**Comment by rubenzorrilla** [comment]
Done!
