### ISSUE TITLE
Add SubModelPart writes deprecated Condition names

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/GiDInterface#158]
Hi @jginternational 
I saw that the (new) feature AddSubModelPart writes deprecated condition names.
The correct names are listed [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/sources/variables.cpp#L527) and [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/sources/variables.cpp#L1120)

**Comment by jginternational** [comment]
Are this the changes required? @philbucher 

https://github.com/KratosMultiphysics/GiDInterface/commit/e3cbad35d5d2bbdb403ee2db3c1e4e6bebb24b46

**Comment by philbucher** [comment]
I did the changes, closing
