### ISSUE TITLE
Road to Release 5.2

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#160]
There is a scheduled publication of a new Kratos version for late November, KratosMultiphysics/Kratos#866

There is a grid available for setting which application will be packed with the GUI and deployed with GiD
Add/Remove apps [here](https://github.com/KratosMultiphysics/GiDInterface/projects/5)

There's a hard effort in the way of adding an example in every app for fast validation and make user experience better. After the summer we argued about setting a policy about that. If an application wants to be published, it must have at least 1 usage example.
At this point, only body fitted fluid and FSI have an example. Structural, Solid and Embedded are missing.

@KratosMultiphysics/team-maintainers

**Comment by philbucher** [comment]
@jginternational what is the format in which you want to have the application cases?
@KlausBSautter has a ready case but we don't know how to handle it (also this requires #159 to be done)

**Comment by jginternational** [comment]
Ok @philbucher , I've created the issue for the example #161

**Comment by loumalouomega** [comment]
@jginternational can you add to the structural application the possibility to chose:

- HyperElastic3DLaw: For 3D solid elements
-HyperElasticPlaneStrain2DLaw: For 2D elements

Thanks

**Comment by jginternational** [comment]
@loumalouomega I'll be out of the office until the next week
You can try and add it by yourself in this file:
https://github.com/KratosMultiphysics/GiDInterface/blob/master/kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml

Take a look at the LinearElastic laws

**Comment by josep-m-carbonell** [comment]
@jginternational  if the  pull request of the code is accepted and #176 too, we can include SolidMechanicsApplication in the release

**Comment by jginternational** [comment]
Released 5.2.1

https://github.com/KratosMultiphysics/GiDInterface/releases/tag/Release5.2.1
