### ISSUE TITLE
Structural example

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#161]
List of things needed for an example:
- [x] Define the geometry
- [x] Define the mesh properties
- [x] Define the values assigned to the tree 
    - Parts
    - Conditions
    - Parameters

**Comment by jginternational** [comment]
You can see the examples in FSI or Fluid applications.
Geometry should be parametricaly created (for difficult geometries we can load a gid model)

Force meshing parameters is not mandatory, but recommended for a example.

Another important thing is to define the tree parameters, because the main idea is to create a "one click example" so the user can see the best settings that work with the model.

**Comment by KlausBSautter** [comment]
Hey @jginternational here is an example for the truss element:
[TrussCantilever.zip](https://github.com/KratosMultiphysics/GiDInterface/files/1417740/TrussCantilever.zip)
The problems still arising are summarized here:

[Project](https://github.com/KratosMultiphysics/GiDInterface/projects/9)
