### ISSUE TITLE
New Shallow water application

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#173]
[Branch ](https://github.com/KratosMultiphysics/GiDInterface/tree/add-Shallow-water-application)

**Comment by miguelmaso** [comment]
Hello, I can't push commits
In Kratos repository I can push correctly. Any idea? Here is a screenshot.
![captura de pantalla de 2017-11-16 17 21](https://user-images.githubusercontent.com/25640870/32902795-aa2e29ce-caf3-11e7-9e05-f678bafe5891.png)

**Comment by jginternational** [comment]
I've added write permission to  @KratosMultiphysics/shallow-water team

**Comment by jginternational** [comment]
Is it working now? @miguelmaso

**Comment by miguelmaso** [comment]
it's still not working @jginternational
