### ISSUE TITLE
solution_type still written

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/GiDInterface#186]
@jginternational @philbucher solution_type is still written by the problemtype.

@philbucher did u check if after #850 the problemtype is still working correctly?

**Comment by philbucher** [comment]
I think I did, I will check again tmr

**Comment by RiccardoRossi** [comment]
Thx mate!! (I have the impression that some some commit overwrote changes)

**Comment by philbucher** [comment]
was working for me, see #188
