### ISSUE TITLE
The requested analysis type "Non-Linear" is not available!

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/GiDInterface#188]
Exception: The requested analysis type "Non-Linear" is not available!
Available options are: "linear", "non_linear", "arc_length", "formfinding"

**Comment by RiccardoRossi** [comment]
this again is @philbucher @jginternational 

also @rubenzorrilla wasn't this changed??

**Comment by RiccardoRossi** [comment]
same with residual_criterion

**Comment by philbucher** [comment]
That is strange 
I am quite sure I checked it
I will have a look tmr morning

**Comment by philbucher** [comment]
@RiccardoRossi are you sure you have the most up-to-date version of the GiD interface?
I just did a test in 2D and 3D and everything was fine
![screenshot from 2017-11-10 08-00-03](https://user-images.githubusercontent.com/25484702/32646631-b27d7cf2-c5ed-11e7-8c05-6a744d5c0434.png)

**Comment by rubenzorrilla** [comment]
@RiccardoRossi In my case everything if fine. Both @philbucher and me (together with @jginternational ) discussed and fixed this a few days ago.

**Comment by RiccardoRossi** [comment]
sorry guys this was my bad. I did do a pull, but for any reason my git was "detached from head".

i now managed to pull correctly and the thing works.

@jginternational 2-3 comments on papercuts i still see:

Right now the OpenMP defaults to 1. I think anyway this is not used. Can we remove it? or eventually set it to a default coresponding to the max number of threads

also we are missing in the interface the hyperelastic law of @loumalouomega . I guess it would be nice to add it.

**Comment by RiccardoRossi** [comment]
another small papercut: we should expose the "echo_level" in the interface (my personal taste  is that the default should be 1 to see the iterations, however i am open to discussing it)

**Comment by philbucher** [comment]
@RiccardoRossi  I created a [card](https://github.com/KratosMultiphysics/GiDInterface/projects/9) for your suggestion
