### ISSUE TITLE
Create Potential Flow Application

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#19]
Growing from Fluid app:
The application has it's own:
- Solution strategy: potential_flow_solver
    - Needs:
        - skin_parts : List with the skin submodelparts
        - no_skin_parts: List with the Wake modelpart
- Condition : Wake 
    - Over:
        - 2D: Point - Node
        - 3D: Line - LinearElement
    - Parameters:
        - Direction
        - Epsilon

Supervisor: @RiccardoRossi

**Comment by jginternational** [comment]
We wont need any condition from the Fluid application (inlet, outlet....), nodal conditions (initial velocity...)
There will be a new one called far_field, that contains the whole contour (2d lines, 3d surfaces)

The only parameter for the fluid is the density

**Comment by jginternational** [comment]
@RiccardoRossi 
It's almost ready
We can test it

**Comment by RiccardoRossi** [comment]
La has subido al github? En qué branch?

Riccardo

**Comment by jginternational** [comment]
La branch se llama potential_flow

**Comment by jginternational** [comment]
@RiccardoRossi Lets see if we can pull this to the master soon

**Comment by RiccardoRossi** [comment]
I think you can put It is máster

Thx
Riccardo
