### ISSUE TITLE
Invalid Properties are written for Beam

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/GiDInterface#190]
When preparing a beam case GiD still writes `LOCAL_AXIS_ROTATION` and `SECTION_TYPE`
These have to be removed, otherwise the analysis does not run!
can you please do this @jginternational?
@RiccardoRossi FYI

**Comment by philbucher** [comment]
Also the `time_step` in the `ProjectParameters.json` was written as `[1.1]` instead of `1.1`
Could you please also check this @jginternational ?

**Comment by jginternational** [comment]
Hi @philbucher you can test it, but I couldn't get the [1.1] error

**Comment by philbucher** [comment]
I couldn't reproduce it either
Beam works now, thx @jginternational !
