### ISSUE TITLE
Constitutivelaw.xml parameters with values=" " field ignored

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/GiDInterface#191]
The values= " " field is ignored in the parameters of the constitutive law. It is a feature that is needed to help the user to select a section size for example. In Solid app, into solid/develop branch there are some examples.

**Comment by jginternational** [comment]
I can't see the examples @josep-m-carbonell

**Comment by josep-m-carbonell** [comment]
<parameter n="SECTION_SIZE" pn="Profile Size" v="80" values="80,100,120,140,160,180,200,220,240,270,300,330,360,400,450,500,550,600" />
      <parameter n="DENSITY" pn="Density"/>

**Comment by josep-m-carbonell** [comment]
parameter n="SECTION_SIZE" pn="Profile Size" v="80" values="80,100,120,140,160,180,200,220,240,270,300,330,360,400,450,500,550,600"

**Comment by jginternational** [comment]
Ok, I didn't understand the problem

**Comment by jginternational** [comment]
You can test it

**Comment by josep-m-carbonell** [comment]
Ok it works
