### ISSUE TITLE
README.md when using a link

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/GiDInterface#207]
I tried to set up a link to my Kratos installation folder in order to substitute the kratos.gid/exec/Kratos one. When doing a git status, the kratos.gid/exec/Kratos/README.md file appears as removed. I tried to locally untrack it by adding it to the .git/info/exlude but it does not work. Any suggestion?

**Comment by ipouplana** [comment]
@lorenzogracia and me have tried adding the README.md in the .git/info/exlude with the same result...

**Comment by jginternational** [comment]
@roigcarlo added it. That file has been added because he needed those folders to exist. Maybe he can bring some light on the issue

**Comment by roigcarlo** [comment]
Yep I added it. Feel free to add this to the git ignore. I could not add it myself when I added the file for obvious reasons...

Reason for this is that I found (myself included) that people tend to forget to add the "exec/Kratos" and they end up having kratos in a place were the script cannot find it.

**Comment by roigcarlo** [comment]
I fixed this.
