### ISSUE TITLE
Structural examples by @mpentek

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#210]
@mpentek [wrote ](https://github.com/KratosMultiphysics/Kratos/issues/866#issuecomment-348976501):

@jginternational it would be quite important to solve this issue, see my detailed experience as follows with sample files hyperlinked. I think there is some problem with the model creation from the GiD side. for an FSI case I have a previous shell model and works well for solving. however, anything surface-like I currently try to create does not. line (beam) and volume (solid) type elements work fine now as well. I am quite confident that the model is created correctly. 

the error message definitely says that some entities are trying to be assigned/combined with conditions that are incompatible. in case you are out of office for a longer time is there a chance that this issue is addressed by someone else?

@KratosMultiphysics/structural-mechanics maybe you have some similar/other experience

**Samples which DO NOT seem to work:**
**thin triangular shell**
-> [static](https://syncandshare.lrz.de/dl/fiBAPEvKNDkWTnMHjZ99P5dZ/csd_shell_thin_triangular_static.gid), [dynamic](https://syncandshare.lrz.de/dl/fiP5zynoMN7gzvzkiynzxxG3/csd_shell_thin_triangular_dynamic.gid)

_Error (l685): You have not assigned a proper entity to group structure
STACK:
You have not assigned a proper entity to group structure
    while executing_

**thick quadrilateral shell**
-> [static](https://syncandshare.lrz.de/dl/fiN4YWCrtJ7Nt5CViJzUAGLK/csd_shell_thick_quadrilateral_static.gid), [dynamic](https://syncandshare.lrz.de/dl/fi54NxtC3fJ5sCkE99ayH7Pm/csd_shell_thick_quadrilateral_dynamic.gid)

_Error (l685): You have not assigned a proper entity to group structure
STACK:
You have not assigned a proper entity to group structure
    while executing_

**thin corotational quadrilateral shell**
->[ static](https://syncandshare.lrz.de/dl/fi4c5WP2e8AaZTyZRYzMNf2e/csd_shell_thin_corotational_quadrilateral_static.gid), [dynamic](https://syncandshare.lrz.de/dl/fiTf1TdWDHhzS5YRNCdEXyg5/csd_shell_thin_corotational_quadrilateral_dynamic.gid)

_Error (l685): Element QuadShellThinCorotationalElement Linear (2 nodes) not available for line entities on group structure
STACK:
Element QuadShellThinCorotationalElement Linear (2 nodes) not available for line entities on group structure
    while executing_

 
 
 
 
**Samples which DO work:**
- [solid small displacement tetrahedra static](https://syncandshare.lrz.de/dl/fiJdyvJW4SdXmGH6Cz8D7n1f/csd_solid_small_displacement_tetrahedra_static.gid)
- [solid total lagrangian hexahedra dynamic](https://syncandshare.lrz.de/dl/fiEPkAqc9G56Vj7UJeTpJdBR/csd_solid_total_lagrangian_hexahedra_dynamic.gid)
- [beam large displacement static](https://syncandshare.lrz.de/dl/fi89mA79ETLeBqbMvufRYNRS/csd_large_displacement_beam_static.gid)

**Comment by jginternational** [comment]
Hi @mpentek 

What I've noticed on all your examples is that the groups are empty.
I'm attaching an example of how to use the GUI to generate a Static Thin Corotational Quadrilateral Shell case

https://www.dropbox.com/s/rpzbryl0yee50ju/QuadBueno.mp4?dl=0

**Comment by mpentek** [comment]
Hi @jginternational 

Thanks for this example. Yes, you assign the conditions and parts by selecting the geometric entities. I generally setup the geometry, assign geometrc elements to groups and then assign conditions to groups. 

Now I managed to have the static example

- with directly assigning conditions to geometric entities it works, see [here](https://syncandshare.lrz.de/dl/fi2G8yAC3VQ6Cp17fjeMZLRL/csd_static_no_predefined_groups.gid)
- with assigning the geometric entities to groups now (for this case) and later conditions to groups also works, see [here](url


- for an older example it does notwork , although the groups do have geometric entities assigned, see [here](https://syncandshare.lrz.de/dl/fi4c5WP2e8AaZTyZRYzMNf2e/csd_shell_thin_corotational_quadrilateral_static.gid)

I am a bit confused, but there is someking of bug involved, at least I think. I have set up the working examples - for solid and line-type elements - which work in the fashion I generally do.

**Comment by mpentek** [comment]
@jginternational  my colleague Anoop (will add him today to Kratos on GitHub) is having similar issues, so I suppose it is not isolated to me.

"
So I am also able to run it with quad thick shell elements, static and dynamic if I assign the loads and properties directly to elements, and if I define the groups before, it shows the error of not findign Mainkratos.py. 
"

**Comment by philbucher** [comment]
I also just tried a completely different example using the shells and had the same problem:
What I did: 
Create Geometry => Assign Entities to Groups => Assign BCs and loads to Groups

I will now try to do it as in the video. This however can not be a permanent solution, since it will be hard to handle for complex geometries.

**Comment by philbucher** [comment]
The membrane Elements have the same problem

**Comment by jginternational** [comment]
Even if you create the groups first, and then assign them to the tree, you have to select the proper geometric entity in the tree window
Check this [video](https://www.dropbox.com/s/z1hm70oz5je1biv/external_group.mp4?dl=0) showing how it works

**Comment by mpentek** [comment]
@jginternational thanks for the tip, it seems to work. There is definitely some change in how this is done, it seems that previously one could do it in more ways - at least @philbucher and I are accustomed to something else. Important to know how it does work. 

We are going to test GiD and Kratos with our student, so will be able to see how beginners cope with certain ways.

**Comment by jginternational** [comment]
Perfect! Anyway I'll keep on working on an automatic way to avoid this errors
