### ISSUE TITLE
Beam and truss elements are in developer mode

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/GiDInterface#214]
Trying to make the truss example in release mode and the element type changes (without notification) to solid!!!

**Comment by jginternational** [comment]
This is a big trouble. Should I set those elements as "production ready" or "hide" the examples that use those elements?

**Comment by pooyan-dadvand** [comment]
For me it is ready. Any comment from @KratosMultiphysics/structural-mechanics team?

**Comment by jginternational** [comment]
Also MembraneElement is only available in developer mode
