### ISSUE TITLE
Time settings not available for static analysis

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/GiDInterface#219]
Hi @jginternational 
If I select a static analysis, I cannot change the time settings. This is however necessary for a quasi-static analysis.
Since it is available in the dynamic case, could you please make it available also for the static case?
Thx a lot!

FYI @KratosMultiphysics/structural-mechanics

**Comment by loumalouomega** [comment]
I would recommend to create the Quasi-Static analysis

It will be visible just in the interface, it will create a static analysis but with the possibility of adding a time evolution

**Comment by loumalouomega** [comment]
Fine, then @jginternational

**Comment by philbucher** [comment]
hi @jginternational I tried to implement this but I did not manage

It would be really good to have this in the next release

**Comment by jginternational** [comment]
I think that tomorrow I'll have this finished
