### ISSUE TITLE
Structural - Moment loads are missing in the interface

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#227]
I don't know if this is in the TODO list

@jginternational would be very difficult to add moment loads to the interface?, it would the same as the case of the rotation, when the element selected has rotation add to the tree the possibility to set moment loads.

The processes to use are the same as the standard loads, but instead of POINT_LOAD the POINT_MOMENT will be use. Instead of PointLoadCondition3D1 the PointMomentCondition3D1 will be used.

Besides @KratosMultiphysics/structural-mechanics I think that we have missing the distributed moments (not very common, but for consistency we should add it)

**Comment by jginternational** [comment]
At this moment, I think that we have no chance to filter conditions from elements automatically. But I can add the moment loads.

**Comment by loumalouomega** [comment]
Thanks

**Comment by jginternational** [comment]
@loumalouomega is this working in the Kratos side? have you got an example?

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/structural-mechanics ?

**Comment by jginternational** [comment]
@loumalouomega @RiccardoRossi @philbucher 

Shouldn't it be also available for 2d and 2d axysimmetric? I haven't found them on Kratos registered conditions. 

Should I call it PointMomentCondition3D1N even in 2d models?

**Comment by loumalouomega** [comment]
The current structural does not support axysimmetric, I haven't found the time to fix it. I don't know if the conditions are registered
