### ISSUE TITLE
Fix | Patch current bugs

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#23]
From the current bug list, there are some of them really hard to solve but easy to patch. 

Depending on the available time and the real impact on the rest of the issues we should take the decision of patching them and keep the issue opened for future solutions.

For example: #6 and #20 have an expensive solution, that will change the whole json writing system for all the applications, but it's cheap to patch 'em by banning some "forbidden project names"

**Comment by rubenzorrilla** [comment]
@jginternational, what about this? Is it still pending?
