### ISSUE TITLE
floating point in properties input values

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/GiDInterface#235]
The interface is writing a value which is cut at 6 decimals. This causes a loss of information

If I write DENSITY:    7850.129876  the written value is 7850.12
If I write a BULK_MODULUS : 164.206349206e9 the written value is 164206000000.0

**Comment by josep-m-carbonell** [comment]
Any solution @jginternational?

**Comment by jginternational** [comment]
I'm working on it

**Comment by josep-m-carbonell** [comment]
Ok, thank you. I think is something related to use strings for values and the tcl expr conversion.

**Comment by jginternational** [comment]
I think I've found the problem. It will be fixed soon

**Comment by jginternational** [comment]
@josep-m-carbonell fixed !
