### ISSUE TITLE
Structural - Add Eigensolveranalysis

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#243]
As said in KratosMultiphysics/Kratos#1458

This issue will contain the GiD needs to achieve the required implementation

**Comment by philbucher** [comment]
hi @jginternational 
Thx for the fast response
Here are (some) settings:
The solver type should be named "Eigenvalue" (`eigen_value` in ProjectParameters)
It should consist of the same things as the Static analysis, except the following things:
- no analysis type
- no loads
- scheme should be selectable (same as in dynamic analysis), at the moment only "dynamic" is available (in ProjectParameters: `scheme_type : dynamic`)
- under "Solution", you can remove "Time parameters" and "Strategy Parameters". Furthermore there is no MPI available (yet)

The process for the postprocessing and the solver settings I will write you tmr

**Comment by philbucher** [comment]
The process for the postprocessing is the following:
~~~json
 "list_other_processes" : [{
        "python_module"   : "postprocess_eigenvalues_process",
        "kratos_module"   : "KratosMultiphysics.StructuralMechanicsApplication",
        "help"                  : "This process postprocces the eigen values for GiD",
        "process_name"          : "PostProcessEigenvaluesProcess",
        "Parameters"            : {
            "result_file_name" : "User_input_problem_name",
            "animation_steps"   :  20,
            "label_type" : "frequency"
        }
    }]
~~~
The Settings for this process go into "Solution". Please expose the following two settings:
- Number Animation steps (int) (default to 20)
- Label Type (string): "angular_frequency" or "frequency" (default)

The result file you have to load to postprocessing is named: whatever the user saves the project under + "_EigenResults.post.bin"
e.g. "Structure_Beams_EigenResults.post.bin" if the user saved the project under "Structure_Beams"
In this case you have to set the "result_file_name" in the json above to "Structure_Beams"

**Comment by philbucher** [comment]
for the selection of the eigensolver please add an option "Eigenvalue Solver" under "Solution"
there please expose the following settings (with defaults):
~~~json
{
    "solver_type": "eigen_eigensystem",
    "number_of_eigenvalues": 5,
    "max_iteration": 1000,
    "tolerance": 1e-6,
    "echo_level": 1
}
~~~

these settings should be added to the `solver_settings` in ProjectParameters as `eigensolver_settings`, i.e.
~~~json
"solver_settings" : 
{
    "other_settings" : {},
    eigensolver_settings :
    {
        "solver_type": "eigen_eigensystem",
        "number_of_eigenvalues": 5,
        "max_iteration": 1000,
        "tolerance": 1e-6,
        "echo_level": 1
    },
    "other_settings" : {}
}

**Comment by philbucher** [comment]
That should be all I think for the moment, please ask if sth is unclear.
I will test it once you have a draft

Thx again for the fast response

**Comment by philbucher** [comment]
ping @j

**Comment by jginternational** [comment]
Hi @philbucher 

I think that you should change the file:

`[...]\kratos\python_scripts\eigen_solver_factory.py`

and set:
`linear_solver = new_linear_solver_factory.ConstructSolver(settings)`

**Comment by philbucher** [comment]
@jginternational I think it is fine the way it it
`settings` are the settings for the eigenvalue-solver
the eigenvalue solver needs a linear solver internally, this one is created with `settings["linear_solver_settings"]`

**Comment by jginternational** [comment]
@philbucher test it if you can!

I can not hide the MPI part, but I can show a warning if the user tries to calculate it in MPI
