### ISSUE TITLE
DEM SubModelPartData bug

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/GiDInterface#269]
It writes 
IDENTIFIER name of the group
(with spaces, which is giving an error)

**Comment by maceligueta** [comment]
just to let them know: @salvalatorre @merceln

**Comment by jginternational** [comment]
@maceligueta  how should it be written? with underscores?

**Comment by maceligueta** [comment]
Yes, I have tried with \" at the beginning and end but Kratos does not accept a string limited by " ". So I think the only solution is to use undescores.
