### ISSUE TITLE
Fluid - Missing flush while calculating

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#285]
In Windows, when you run a case from GiD, 99% of the time the case is running, the user can only see the following.

![image](https://user-images.githubusercontent.com/5918085/37234319-59f3812c-23f7-11e8-89af-9e67c287838a.png)

It does not matter the Echo level selected, after a long time, it flushes and all the information is printed.

Maybe there is a "flush" missing in c++ or python

**Comment by pooyan-dadvand** [comment]
Yep the old problem

@KratosMultiphysics/fluid-dynamics you may add a flush at least every 10s....

**Comment by jcotela** [comment]
@pooyan-dadvand shouldn't using the logger take care of this? I'd prefer switching to the logger rather than forcing flushes.

**Comment by pooyan-dadvand** [comment]
I would rely on you decision on this, my concern is to have 5.3 fixed and released before eastern....

**Comment by jcotela** [comment]
I have added flushes to the current script to avoid complicating the issue. @jginternational the script runs in linux, but we never had flush problems there. Can you try a case in windows to see if the flushes actually happen? (I set it to flush every 10 seconds for OpenMP runs).

**Comment by jginternational** [comment]
OK, In windows I'm seeing the refresh every 10 seconds. Fine!
