### ISSUE TITLE
Fluid - Stale branch to remove divergence cleareance

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#294]
There is a branch with only a commit called: https://github.com/KratosMultiphysics/GiDInterface/tree/feature-fldyn-removing-divergence-clearance
by @rubenzorrilla 

It was created on December 2017

Shall we merge it or destroy it?

**Comment by rubenzorrilla** [comment]
Hey @jginternational ! I think that we already merge it (or directly committed to the master branch) since this option is not available anymore in the interface. Indeed, we remove that from the FluidDynamicsApplication solvers.

Summarizing, we can destroy it.
