### ISSUE TITLE
Interface fails to write calculation files if there is an accent in the problem name

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/GiDInterface#304]
I don't know if accents are supported in Kratos also as problem_name and model_part name. The first error that appears is that the calculation files can not be written in the problem folder.

**Comment by jginternational** [comment]
Ok, as a first measure, I'll add it to the forbidden names list

**Comment by josep-m-carbonell** [comment]
It happen randomly... it is strange. Maybe is better to forbid certain names.

**Comment by jginternational** [comment]
The currently forbidden names are:

- Numeric
- Boolean
- "null"

For example, this names are not allowed:

- 3.gid
- false.gid
- null.gid

I can add to the banned list any name containing accents and strange characters

**Comment by pooyan-dadvand** [comment]
We should find a definitive solution for this....
