### ISSUE TITLE
Unify loads

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/GiDInterface#306]
Hi @jginternational, I can not unify loads because there is a field that changes depending on the geometry

The field is this one:
 VariableName="POINT_LOAD"
 VariableName="LINE_LOAD"
 VariableName="SURFACE_LOAD"

This is why I has not already done it. Any idea to surpass this problem?

**Comment by jginternational** [comment]
This field could be placed in the Topology section

**Comment by josep-m-carbonell** [comment]
I have unified the load names, so the variable name coincides in all geometries. It is more consistent. Now the problem are the units. It is clear that a distributed load on a line does not have the same units as a distributed load on a surface.  I would like to add a help message trying to explain that, but it does not open in the correct place, I don't know if this can be improved.
