### ISSUE TITLE
Release 5.3

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#314]
Release 5.3 is almost here!

I've created a branch for it, so it's time for hotfixes before packing.

@KratosMultiphysics/structural-mechanics please check the latest features, hinges and eigenvalues. They have been added without testing so you'll find bugs

@KratosMultiphysics/dem test it, you are the great new feature of this release

@KratosMultiphysics/fluid-dynamics test it, but I don't think there are much changes in Fluid

@KratosMultiphysics/solid-mechanics  test it, but I don't think there are much changes in Solid

@rubenzorrilla Check the examples in the FSI

https://github.com/KratosMultiphysics/GiDInterface/tree/release-5.3

**Comment by loumalouomega** [comment]
I get the following error with the eigenvalue:
~~~
Traceback (most recent call last):
  File "MainKratos.py", line 127, in <module>
    solver.Solve()
  File "/home/vicente/src/Kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py", line 259, in Solve
    mechanical_solution_strategy.Solve()
RuntimeError: Error: No degrees of freedom!
~~~
It is related with https://github.com/KratosMultiphysics/GiDInterface/issues/321,if I write the group manually it works. Great job JG

**Comment by jginternational** [comment]
Release 5.3.0 is available at: 

https://github.com/KratosMultiphysics/GiDInterface/releases/tag/Release-5.3.0

**Comment by jginternational** [comment]
Please, @KratosMultiphysics/structural-mechanics @KratosMultiphysics/dem @KratosMultiphysics/fluid-dynamics @KratosMultiphysics/solid-mechanics 

Check if it is working fine. If you find any bug, feel free to add it as an issue
