### ISSUE TITLE
Structural contact process

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#32]
Solid contact process implemented by @loumalouomega need some customization in the writen json.

Ask user to match pairs of GiD group to contact.
(e.x. by defining a contact id in the process)

In the json one of the submodelparts will be origin_model_part_name and the other destination_model_part_name, and the contact id must not be shown

**Comment by jginternational** [comment]
@loumalouomega At this point, it is working in a 'Master-Slave' structure. You can try it in the Add_contact_to_solid branch

**Comment by loumalouomega** [comment]
@jginternational Right now I am working in autocontact detection

**Comment by jginternational** [comment]
@loumalouomega test and close this issue when you think it's ready

**Comment by josep-m-carbonell** [comment]
@jginternational @loumalouomega, somebody decided to add a CONTACT field in boundary conditions of the SolidMechanics interface,  is there any design for that addition?  it has conflicts with other designs for contact in other applications, i.e. pfem solid. I personally don't approve this commit.

**Comment by loumalouomega** [comment]
@josep-m-carbonell we can just move it to the StructuralApplication interface

**Comment by rubenzorrilla** [comment]
@jginternational @loumalouomega personally, I wouldn't move it to the StructualMechanicsApplication neither. AFAIK the contact mechanics interface is still under development and such StructuralMechanicsApplication is supposed to be stable. What I suggest is to create a ContactStructuralMechanicsApplication subapplication similar to the embedded fluid case in the FluidDynamicsApplication.
