### ISSUE TITLE
something was broken in last commints. Groups not written correctly

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/GiDInterface#321]
Parts group name is not written. In some places Parts_Parts_ apper instead of Parts_ only. Some groups from loads are also not written correctly. Some of the last changes destroyed the writting of the input. Problems detected in the Solid App without doing any change to the app interface.

**Comment by pooyan-dadvand** [comment]
We should wait for next week when @jginternational come back to office.

**Comment by jginternational** [comment]
Hi @josep-m-carbonell 

I can't reproduce the bug.
Are you in the Release-5.3 branch or the master?

Could you attach an example (.gid) of the problem?

**Comment by josep-m-carbonell** [comment]
I think it was in the master, group names are not written correctly.

**Comment by josep-m-carbonell** [comment]
It must be checked in the release too, if the same changes were applied

**Comment by jginternational** [comment]
@josep-m-carbonell @loumalouomega You can check if it's fixed
