### ISSUE TITLE
error when assigning self-weight condition to different geometry types

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/GiDInterface#322]
If I have a mesh of triangles and quadrilaterals the condition applied on surfaces fails.
![error selfweight mixed geometries](https://user-images.githubusercontent.com/23210788/38327861-a32aade6-3849-11e8-8cf3-783225bcc015.png)

**Comment by jginternational** [comment]
Hi @josep-m-carbonell .

You should apply the self weight 2 times, one for each mesh.
We are not ready for writing a group with more than 1 type of element

**Comment by jginternational** [comment]
Can we close this issue? @josep-m-carbonell

**Comment by josep-m-carbonell** [comment]
Well, you can close it, the problem is that you assign the loads to geometry and then you decide the type of mesh you want. Therefore the correct thing would be to make the assignment independent of the type of mesh.

**Comment by jginternational** [comment]
Yes, I've got something similar noted on my list of features for Kratos 6. 
If a group has different element types assigned, write them separated, to avoid the current restriction of 1 element type per group
