### ISSUE TITLE
CONTACT boundary condition has disappear on the interface

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#328]
Just that

**Comment by jginternational** [comment]
Remember that:
- You must be in developer mode (Menu Kratos)
- Your must apply a part before the Boundary conditions are shown

**Comment by jginternational** [comment]
I can see Contact in Boundary conditions, just adding for example, a Solid small displacement element in a part. 

Remember that elements must define wich nodal condition can be applied

**Comment by loumalouomega** [comment]
I will try again and tell you

**Comment by loumalouomega** [comment]
I updated and now it works, sorry for the noise
