### ISSUE TITLE
Check proc for writing Solvers in the tree and establishing default values of each param

### ISSUE THREAD

**Issue by djvicente** [KratosMultiphysics/GiDInterface#335]
Hi @jginternational,
I have detected one possible bug related to the selection of the 'Solver' and the default values which appear in the tree. I will try to explain it. In the DamInterface I have solved this bug, but I think it could be interesting to comment it. 

I needed to change the default value of one parameter of a specific Solver (in my case the 'BICGSTABSolver'). In my app, I read the 'Common/xml/Solvers.xml' and introduce the Solvers in the tree with the proc 'spdAux::injectSolvers' through a 'dynamicnode'.
I have found that, although the default value of a specific parameter in a specific solver is changed (in my case 'preconditioner_type --> v="ILU0Preconditioner", if the same parameter is common in another solver written after the one I have changed, the default value is set into the value of the last solver.

I think, but I am not sure, that the origin of the problem is the way it is imported the Solvers to each through the spdAux::injectSolvers proc.

To check this bug I have made some tests. For example, changing all the default values of a common parameter, 'max_iteration'. I put a different value for each solver and it always take the default value writen in the last solver 'AmgclMPISolver'. If I change the order of the solvers, it still takes the last one.

In my case, I have solved my problem copying the 'Solvers.xml' file, and writing my default solver with the desired params and values at the end of the Solvers List. This action solves my problem, but maybe it can be fixed in a global way. 

I hope that it will help you discover this bug and if I have not explained well, do not hesitate asking me

**Comment by jginternational** [comment]
This is a well known bug. There was an discussion about it a couple years ago. There was a problem with the default values here with the parameters 'shared' between different solvers. 

Imagine you have Solver A and Solver B, and both of them havethe param Parameter
For Solver A, the default value of the param is 1
For Solver B, the default value of the param is 2

The first time a user opens the tree, Solver A is selected, and Parameter value is 1
The user changes this value to 5
Then changes the solver to Solver B.
What should Parameter value be? 2 or 5?

It's not easy. For the next Big change, expected to be published after summer, this will be solved.
For this case, Parameter value will be 2, but if you change again to Solver A, it will remember the 5

**Comment by djvicente** [comment]
Perfectly explained @jginternational. Then, as you were aware of this aspect, I close this issue. 
Thank you very much for your help
