### ISSUE TITLE
Add MPM example

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#356]
Create the automatic example for MPM application

**Comment by bodhinandach** [comment]
@jginternational Let me know if I can help you with this I have some of them.

**Comment by bodhinandach** [comment]
Hi @jginternational, I was thinking recently to add some examples to the problem type as there will be more user trying to use the MPM application. Can you give me some help on this? This will be a cool feature to have in the next release.

**Comment by jginternational** [comment]
DONE
