### ISSUE TITLE
load on lines does not work...

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/GiDInterface#369]

**Comment by RiccardoRossi** [comment]
![screenshot from 2018-05-30 18-37-34](https://user-images.githubusercontent.com/8059665/40734401-a1bea514-6438-11e8-81ca-8b445d589eeb.png)

**Comment by RiccardoRossi** [comment]
[aaa.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/2054836/aaa.gid.zip)

**Comment by loumalouomega** [comment]
Here the same problem

**Comment by jginternational** [comment]
That is only an ugly warning from GiD, it should work anyway

This commit fixes the bug, so new models will not have this problem.
To fix old models, 

- Load the model
- execute this command in GiD command line
    - 'Mescape Data Conditions UnAssign Yes'
- Mesh again
