### ISSUE TITLE
Write calculation files does not check if a mesh was generated.

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/GiDInterface#370]
It allows you to write the file without generating the mesh (unlike standard calculation) and then it fails with a "mysterious" error message
```
There are no nodes
There are no nodes
    while executing
"GiD_WriteCalculationFile coordinates -factor $mesh_factor $formats"
    (procedure "customlib::WriteCoordinates" line 7)
    invoked from within
"customlib::WriteCoordinates "${s}%5d %14.10f %14.10f %14.10f\n""
    (procedure "write::writeNodalCoordinates" line 10)
    invoked from within
"write::writeNodalCoordinates"
    (procedure "Fluid::write::writeModelPartEvent" line 18)
    invoked from within
"Fluid::write::writeModelPartEvent"
    ("eval" body line 1)
    invoked from within
"eval $wevent"
    (procedure "writeAppMDPA" line 17)
    invoked from within
"writeAppMDPA $appid"
    (procedure "::write::writeEvent" line 19)
    invoked from within
"::write::writeEvent $filename"
    (procedure "Kratos::WriteCalculationFilesEvent" line 11)
    invoked from within
"Kratos::WriteCalculationFilesEvent"
    invoked from within
".gid.menu.button7.m.m invoke active"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke active]"
    (procedure "tk::MenuInvoke" line 50)
    invoked from within
"tk::MenuInvoke .gid.menu.button7.m.m 1"
    (command bound to event)
```

**Comment by jginternational** [comment]
Hi @jcotela 

That only happends if there is no mesh and if:

- You are in developer mode
- And click on menu Kratos > Write calculation files and no run

In release mode, this message is shown
![image](https://user-images.githubusercontent.com/5918085/40743269-565e3aee-6451-11e8-8a69-319676b9df57.png)

And if you calculate normaly (the rocket icon, or F5):
![image](https://user-images.githubusercontent.com/5918085/40743302-6ed63db0-6451-11e8-9009-2f6fb24e50de.png)

The error message policy in developer mode is showing the whole stack trace, and in release mode, show only the section where the message comes from and the message itself.

I can change the message to:

"There are no nodes, Please mesh your model."

**Comment by jcotela** [comment]
@jginternational ok, if it is only a developer mode thing, I can live with it. I just thought I would report it since it popped up while doing some tests for the next release.
:+1:  for more descriptive error messages.

**Comment by jginternational** [comment]
It's not scheduled but the issue is there #146
