### ISSUE TITLE
Trusses should mesh only one element per line

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#379]
That

**Comment by philbucher** [comment]
i am not sure if this is a good idea...

You can always force this by assigning a coarse mesh size

**Comment by philbucher** [comment]
to put also @KlausBSautter in the discussion

**Comment by KlausBSautter** [comment]
that's true. I guess we can expect the user to know this

**Comment by loumalouomega** [comment]
Or we can force the number of divisions to 1 or we can pop up a message

**Comment by KlausBSautter** [comment]
sounds good to me

**Comment by KlausBSautter** [comment]
I would prefer to pop up a message so that one knows what's happening

**Comment by jginternational** [comment]
So, to sum up, if Truss is assigned to a line meshed with more than 1 element, should raise an error message, right?

**Comment by loumalouomega** [comment]
Yes

**Comment by philbucher** [comment]
@loumalouomega sorry I misunderstood, @jginternational please proceed

**Comment by loumalouomega** [comment]
Add a warning after release
