### ISSUE TITLE
[Release 6.0] I don't understand hinges

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#380]
![imagen](https://user-images.githubusercontent.com/19991680/40793433-a77b3926-64fc-11e8-817d-c4c91c548ea0.png)
Can anyone explain me the meaning?, there are tags duplicated BTW

**Comment by loumalouomega** [comment]
Ok, I think I understood, but in my opinion should be moment Z for 2D

**Comment by philbucher** [comment]
I never used this, maybe @KlausBSautter knows better

**Comment by KlausBSautter** [comment]
we should change this text. what it does:
it decouples the respective dof in the local element cs.
So i suggest to add the word "local" at some point. 

We also have to be careful as this utility has to be used in the element code. So enabling this hinge feature for all elements will do nothing for most of the elements.

I have not realized that this is available in GID. Thanks for indicating

**Comment by RiccardoRossi** [comment]
@KlausBSautter could u suggest the name that you would like to be shown?

**Comment by KlausBSautter** [comment]
I would keep it like that but change the header from "Apply Hinge" to "Apply local Hinge"
sth like that

**Comment by KlausBSautter** [comment]
To be true I dont really like this naming which is used right now. It's too long.
Maybe we can add 
"Apply local displacement hinge" & "Apply local rotation hinge" and then one can choose x,y,z node 1,2

at the moment it's strange to say displacement and moment ?

**Comment by loumalouomega** [comment]
@jginternational We need this for the release or move this out
