### ISSUE TITLE
Cables work in self weight?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#382]
[test.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/2062122/test.gid.zip)
Does not work for me

**Comment by KlausBSautter** [comment]
@loumalouomega  add e.g. "TRUSS_PRESTRESS_PK2" : 1000.0
a straight line with truss/cable elements without prestress is singular and thus cant be solved

**Comment by loumalouomega** [comment]
Ok, I just wanted to create a catenary https://en.wikipedia.org/wiki/Catenary, maybe a check should be added to the element, setting at least a prestress of 1000*epsilon or something in the Initialize

**Comment by KlausBSautter** [comment]
maybe with a small prestress you get a catenary I ve not tested that. 
I would suggest against a default pre-stress. There are cases where you dont need prestress

**Comment by loumalouomega** [comment]
OK, i think will close this
