### ISSUE TITLE
Which applications are included in the release?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#383]
EigenSolverApplication is included for example

**Comment by loumalouomega** [comment]
The eigenvalues require by default the EigenSolverApplication

**Comment by loumalouomega** [comment]
At least I need to compile it just now

**Comment by roigcarlo** [comment]
I can give you the list of the applications that will be **compiled**, but not the ones that have to appear in the interface.

**Compiled Linux**:
- EigenSolversApplication
- ConstitutiveModelsApplication
- SolidMechanicsApplication
- ParticleMechanicsApplication
- MeshMovingApplication (Old ALEApplication)
- ConvectionDifusionApplication
- DAMApplication
- PoroMechanicsApplication
- MetisApplication
- TrilinosApplication
- StructuralMechanicsApplication
- FSIApplication
- FluidDynamicsApplication
- DEMApplication
- SwimmingDEMApplication

**Windows**:
- EigenSolversApplication
- ConstitutiveModelsApplication
- SolidMechanicsApplication
- ParticleMechanicsApplication
- MeshMovingApplication (Old ALEApplication)
- ConvectionDifusionApplication
- DAMApplication
- PoroMechanicsApplication
- StructuralMechanicsApplication
- FSIApplication
- FluidDynamicsApplication
- DEMApplication
- SwimmingDEMApplication


For the next time, I follow the list in here: https://github.com/KratosMultiphysics/Kratos/projects/5

**Comment by loumalouomega** [comment]
OK then I will close this
