### ISSUE TITLE
Moments on points missing for 2D?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#389]
I think the problem is the lack of definition on our part, is this expected? @KratosMultiphysics/structural-mechanics

**Comment by loumalouomega** [comment]
Only point_moment_condition_3d exists

https://github.com/KratosMultiphysics/Kratos/tree/master/applications/StructuralMechanicsApplication/custom_conditions

**Comment by philbucher** [comment]
This one should work both for 2D and 3D

At the time I was doing it I figured that making a separate one would have been too much effort, so I decided to to the more general case only

But we should probably rename it then
