### ISSUE TITLE
Has FormFinding disappeared?

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#390]
When trying to use Solvertype  Formfinding this error appears

`
Exception: The requested solver type "formfinding" is not in the python solvers wrapper
Available options are: "static", "dynamic", "eigen_value", "harmonic_analysis"
`

@KratosMultiphysics/structural-mechanics

**Comment by philbucher** [comment]
not merged yet, see https://github.com/KratosMultiphysics/Kratos/pull/2101

**Comment by jginternational** [comment]
So, I understand that formfinding must be out of the release 6 in the GUI

**Comment by philbucher** [comment]
yes :/
