### ISSUE TITLE
Error when I add a parameter to materials in StructuralMechanicsApplication

### ISSUE THREAD

**Issue by Vahid-Galavi** [KratosMultiphysics/GiDInterface#399]
When I add a parameter to a newly created material in StructuralMechanicsApplication, the script crashes and gives the following error:

unknown option "-menu_callback"
unknown option "-menu_callback"
    while executing
".gid.central.boundaryconds.gg.data.f0 configure -menu_callback {::snit::RT.CallInstance ::boundary_conds::Snit_inst13 _fill_data_window_in_material_c ..."
    invoked from within
".gid.central.boundaryconds.gg.data.b.b3 invoke "
    invoked from within
".gid.central.boundaryconds.gg.data.b.b3 instate !disabled { .gid.central.boundaryconds.gg.data.b.b3 invoke } "
    invoked from within
".gid.central.boundaryconds.gg.data.b.b3 instate pressed { .gid.central.boundaryconds.gg.data.b.b3 state !pressed; .gid.central.boundaryconds.gg.data.b..."
    (command bound to event)

**Comment by loumalouomega** [comment]
This is on the interface or running the script?

**Comment by loumalouomega** [comment]
I assume on the interface, I add the responsible

**Comment by Vahid-Galavi** [comment]
Yes, it is GUI.

**Comment by jginternational** [comment]
Hi @Vahid-Galavi 

I should see how are you adding that parameter. Have you created a branch?

**Comment by Vahid-Galavi** [comment]
hi @jginternational 

In order to reproduce it:
- Open the StructuralMechanicsApplication problem type.
- Select of the materials (your can also create a new material model)
- Right click and select "Edit"
- Click "More" button. It will crash and you will have the error message that I have reported here.

**Comment by jginternational** [comment]
Hi @Vahid-Galavi 

The proper place to add a new parameter to the materials database is by editing the materials.xml file in the Structural application xml folder.

I don't remember what was that button for, but it's not working due to some GiD updates, so I've hidden it.
