### ISSUE TITLE
[Solid] Example not working in release mode

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#408]
I'm testing the examples and I've found that Notched beam damage 2D example fails in release mode.

It's because it uses SmallStrainPlaneStress2DLaw.SimoJuExponentialDamageModel constitutive law, which is only available in developer mode, so it crashes in release mode.

Solutions:

- Approve that constitutive law as ProductionReady
- Set another constitutive law in the example
- Show the example only in developer mode

**Comment by josep-m-carbonell** [comment]
The constitutive law must be ProductionReady. You can change it yourself. Thank you!
