### ISSUE TITLE
[MPM] Interface Crash

### ISSUE THREAD

**Issue by bodhinandach** [KratosMultiphysics/GiDInterface#413]
Hi @jginternational currently the MPM Application interface is crashing, after the recent update, I got the following errors:
```
Problem Writing MDPA block:
invalid command name ""
End problems
```

Also, the "materials" combo while selecting the element is not working.

This is a simple beam for 3D static problem as an example.
[surface_load_beam_test_hexa.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/2135290/surface_load_beam_test_hexa.gid.zip)

Is it a problem with the version? I am currently still with the v13.11d.

**Comment by jginternational** [comment]
Hi @bodhinandach , I didn't remember that the Grid element did not use constitutive law.

Should be fixed

**Comment by bodhinandach** [comment]
Thanks @jginternational will check it tomorrow and reconfirm. Appreciate it.
