### ISSUE TITLE
[MPM] Small Issue with Material Combo

### ISSUE THREAD

**Issue by bodhinandach** [KratosMultiphysics/GiDInterface#417]
Hi @jginternational, thanks for the correction yesterday. I still, however, have some issue with the "material" option combo in both the Updated Lagrangian and the Grid elements.

I used to be able to change the material through the combo, but now it can not work.

On top of that, as we decided before, the Grid should have "None" as the primary material option and the user should not be able to change it.

**Comment by jginternational** [comment]
Fixed!
