### ISSUE TITLE
Important: Add Name of ParentModelPart to SubModelParts

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/GiDInterface#419]
Hi @jginternational 
In the near future a container named `Model` is gonna be used more extensively in Kratos, it is the holder of ModelParts. @RiccardoRossi is pushing this strongly, see https://github.com/KratosMultiphysics/Kratos/pull/2137

Now it is possible that there are two RootModelParts in the Model that have SubModelParts with the same name
=> in order to get the correct SubModelPart is is necessary that the SubModelPartNames are prepended with the Name of the RootModelpart, like this:
`RootModelPartName.SubModelPartName` 

Here is a full example:
~~~json
"python_module" : "assign_vector_variable_process",
"kratos_module" : "KratosMultiphysics",
"help"          : "This process fixes the selected components of a given vector variable",
"process_name"  : "AssignVectorVariableProcess",
"Parameters"    : {
    "mesh_id"         : 0,
    "model_part_name" : "StructuralModelPart.DISPLACEMENT_support",
    "variable_name"   : "DISPLACEMENT",
    "value"           : [0.0,0.0,0.0]
}
~~~

Currently this applies to StructuralMechanics and FluidDynamics but will most likely also become necessary for the other apps

@KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
ping

**Comment by pooyan-dadvand** [comment]
Added!

**Comment by philbucher** [comment]
@jginternational are there advancements on this?

the longer this is postponed, the more issues with backwards-compatibility will arise :/

**Comment by jginternational** [comment]
Working on it

**Comment by philbucher** [comment]
I saw that sth changed
Is this solved @jginternational ?

**Comment by jginternational** [comment]
I'm still working on it for some apps like Buoyancy or FSI @philbucher

**Comment by philbucher** [comment]
@jginternational I tried it, it works for a structural problem in the projectparameters
in the `StructuralMaterials.json`-file it is not added yet

I also tried to create a fluid case but there was some error, maybe you can try yourself

Thanks!

**Comment by philbucher** [comment]
> @jginternational I tried it, it works for a structural problem in the projectparameters
> in the `StructuralMaterials.json`-file it is not added yet
> 
> I also tried to create a fluid case but there was some error, maybe you can try yourself
> 
> Thanks!

ping @jginternational 
this is important and should go to the release IMO
any comment from @KratosMultiphysics/technical-committee ?

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee see this necessary and approves it. Also putting to the attention of the @KratosMultiphysics/interface-committee

**Comment by philbucher** [comment]
> @jginternational I tried it, it works for a structural problem in the projectparameters
in the `StructuralMaterials.json`-file it is not added yet

@jginternational is this solved?

this is really important otherwise we will have many warnings soon

**Comment by jginternational** [comment]
Not in the materials file yet. But it will be before the release 7.0.0

**Comment by roigcarlo** [comment]
@jginternational What is the status? can we close yet or link the PR?

**Comment by jginternational** [comment]
Check branch #527 @roigcarlo @philbucher
