### ISSUE TITLE
Test and publish Mac Version

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#421]
Hoorray!

Check:

- [Issue](https://github.com/KratosMultiphysics/Kratos/issues/2287)
- [Version](https://github.com/KratosMultiphysics/Kratos/releases/download/v6.0/kratos-6.0-macOS-HighSierra.zip)

Special thanks to:
@roigcarlo @ipouplana

**Comment by roigcarlo** [comment]
Just to mention that you will probably have to adapt the GiD problemtype script so it changes `LD_LIBRARY_PATH` for `DYLD_LIBRARY_PATH` and also add $KRATOS_ROOT/Lib (without S and capital L) to the `PYTHONPATH`.

Because macOS is different and everything...

**Comment by jginternational** [comment]
@KratosMultiphysics/team-maintainers 

macOS version is available in GiD internet retireve!
