### ISSUE TITLE
[StructuralMechanicsApplication] Adding new CL to the interface

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#434]
This is a TODO, so super hurry, but will be nice to have in some moment. 

Ask to @KratosMultiphysics/structural-mechanics everything you need to add this

**Comment by jginternational** [comment]
I don't understand this issue!

**Comment by loumalouomega** [comment]
There are new constitutive laws->This laws must be added eventually to the interface

**Comment by loumalouomega** [comment]
I think it is just to modify the XML of the constitutive laws, right?. We can do it if it is the case

**Comment by jginternational** [comment]
The ConstitutiveLaws.xml file inside the StructuralMechanics app folder
 Try to add it yourself

**Comment by loumalouomega** [comment]
OKi

**Comment by loumalouomega** [comment]
@AlejandroCornejo
