### ISSUE TITLE
[Fluid] deprecated settings are written

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/GiDInterface#437]
there are several deprecated settings written in Fluid:

- In the fluid settings for the vms still the deprecated settings related with the stabilization are written. (see https://github.com/KratosMultiphysics/Kratos/pull/2624)

- Also the restart_settings can be removed entirely
~~~
"restart_options"                  : {
    "SaveRestart"      : "False",
    "RestartFrequency" : 0,
    "LoadRestart"      : "False",
    "Restart_Step"     : 0
},
~~~

- furthermore the `model_part_name` and the `domain_size` should be moved from `problem_data` to `solver_settings`

- last but not least the processes should be wrapped in additional `processes`- block like this:
~~~
"processes" :
{
    "initial_conditions_process_list"  : [],
    "boundary_conditions_process_list" : [{
        "python_module" : "apply_inlet_process",
        "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
        "Parameters"    : {
            "model_part_name" : "AutomaticInlet2D_Automatic_inlet_velocity_Auto1",
            "variable_name"   : "VELOCITY",
            "modulus"         : 1.0,
            "direction"       : "automatic_inwards_normal",
            "interval"        : [0.0,"End"]
        }
    }]
}
~~~

**Comment by jginternational** [comment]
I don't fully understand the vms point, but since the branch is not merged I'll create a pull request for the rest and keep this issue opened
