### ISSUE TITLE
How to import Ansys ICEM mesh?

### ISSUE THREAD

**Issue by 94zz94** [KratosMultiphysics/GiDInterface#487]
Hi, I have to import an ANSYS ICEM mesh into Gid.
How can I do that?
Should I save it in a particular format?
Normaly ICEM save the mesh in .uns or .msh.
I tried with the extension .msh but it didn't work, and Gid can't import .uns.
Does someone know a way to do that?

**Comment by rubenzorrilla** [comment]
Maybe @escolano can bring some light to this issue.

**Comment by escolano** [comment]
This topic really is related to GiD, not to Kratos. Better ask this question at the 'GiD forum' 
www.gidhome.com/forum
and if possible attach a zip with some small examples of all possible mesh formats exported from ANSYS ICEM
It is possible to implement a simple mesh format importer as a GiD plugin in Tcl scripting language.
(see \plugins\Import\ folder for several examples)

Enrique Escolano (GiD Team)

**Comment by rubenzorrilla** [comment]
@94zz94 I'm closing this. As @escolano points this is completely GiD related. Feel free to reopen it necessary.
