### ISSUE TITLE
Need of updating the Structural Mechanics Problemtype

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/GiDInterface#488]
During the last months @loumalouomega and me have implemented a lot on new CL in this App and we think that could be interesting to update in the same way the capabilities of the ptype.

What is necessary to perform this?

Thank you!

@RiccardoRossi @jginternational @loumalouomega

**Comment by loumalouomega** [comment]
What do you mean the PType?

**Comment by AlejandroCornejo** [comment]
the problemtype of kratos for the structural app

**Comment by loumalouomega** [comment]
I already open an issue for that, #434, but @jginternational has a lot of pending work

**Comment by loumalouomega** [comment]
In this case not, because we combine them, there is an extra work...

**Comment by jginternational** [comment]
Fortunately (for me)(for you)(for all) there is no other way to add a Constitutive law than adding it to it's place!

**Comment by loumalouomega** [comment]
Please speak with @AlejandroCornejo abou this

**Comment by philbucher** [comment]
related to https://github.com/KratosMultiphysics/Kratos/issues/4773
