### ISSUE TITLE
[MPM] Cannot write mdpa or json in MPM

### ISSUE THREAD

**Issue by bodhinandach** [KratosMultiphysics/GiDInterface#491]
@jginternational I just pulled the latest version of the interface and MPM fails to write mdpa or json with the following messages:
```
Problem Writing Project Parameters block:
invalid command name "Structural::write::getParametersEvent"
Event MPM::write::writeParametersEvent 
End problems
```
Could you please help me with this?

**Comment by jginternational** [comment]
In your file MPM/write/writeProjectParameters.tcl in the function:
`::MPM::write::getParametersDict`

The first instuction is:
`set project_parameters_dict [Structural::write::getParametersEvent]`

Change it to:
`set project_parameters_dict [Structural::write::getParametersDict]`

**Comment by bodhinandach** [comment]
ping @jginternational

**Comment by bodhinandach** [comment]
@jginternational Could you please open the following gid file and run it through GiD? It will stop creating mdpa files and the error above are printed.

[gravity application.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/2620733/gravity.application.gid.zip)
