### ISSUE TITLE
PotentialApplication not running

### ISSUE THREAD

**Issue by inigolcanalejo** [KratosMultiphysics/GiDInterface#497]
Does someone know the solution to the following error?

![gid_error](https://user-images.githubusercontent.com/28628414/49375998-235d9480-f706-11e8-820c-d64dd0c6a4e1.png)

**Comment by rubenzorrilla** [comment]
Hey @inigolcanalejo !

This seems to be related to the conditions writing (we had to modify it in the past and it seems that we forgot to update your application). @jginternational does this make sense to you?

**Comment by jginternational** [comment]
Yes, it's in my TODO list. 

Anyway it should have a running example like the other apps, so this issues will be detected earlier. Check the Fluid toolbar, the Book icon.

**Comment by inigolcanalejo** [comment]
Ok, thanks for the hint and your fast answers. I will prepare the running example.
