### ISSUE TITLE
[StructuralMechanicsApplication] Problemtype is broken 

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#499]
![imagen](https://user-images.githubusercontent.com/19991680/49510643-27fe8600-f889-11e8-8f10-c6a92b3a718b.png)

@KratosMultiphysics/structural-mechanics

**Comment by philbucher** [comment]
such things happen to me all the time
Usually I end up recreating the case from scratch. Have you tried this?

**Comment by loumalouomega** [comment]
I did that case from scratch

**Comment by loumalouomega** [comment]
In any case this should not happen

**Comment by philbucher** [comment]
maybe we could add some tests... @jginternational would this be possible?

**Comment by jginternational** [comment]
Yes, i'm working with the GiD Team in the testing platform. @philbucher 

I'll have a look @loumalouomega . Attach me a zip with the gid model please

**Comment by loumalouomega** [comment]
I did it from scratch again, so no problem, I don't have the errored version

**Comment by loumalouomega** [comment]
I attach you an example that doesn't work
[test_punch_prisms_only_shell.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/2649459/test_punch_prisms_only_shell.gid.zip)

**Comment by philbucher** [comment]
> Yes, i'm working with the GiD Team in the testing platform. @philbucher

Awesome!
