### ISSUE TITLE
Embedded fluid mesh before save

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#5]
Using the embedded mesher, the model must be saved before meshing.

**Comment by rubenzorrilla** [comment]
Correct me if I'm wrong, but otherwise the .res with the distance values is not created. Isn't it?

**Comment by jginternational** [comment]
@rubenzorrilla (Correcto) It has been marked as a GiD bug. Anyway, I'm going to protect kratos by not allowing to mesh without having saved the model (Only for Embedded Fluid)

**Comment by rubenzorrilla** [comment]
@jginternational If I'm not wrong, this is already solved, isn't it?

**Comment by jginternational** [comment]
@rubenzorrilla Yes, it's fixed in the problemtype side, not in the GiD side. Closed
