### ISSUE TITLE
Arbitrary noded line as connection of linear lines

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/GiDInterface#505]
Hi, I am implementing a "line" element in Kratos (actually finished that just now) which should be able to handle an arbitrary number of nodes. The special thing here is that I don't need any fancy high order interpolation of the geometry just regular linear connection between the discrete nodes of that element. 
See here:
![screenshot from 2019-01-16 10-14-14](https://user-images.githubusercontent.com/26179700/51238580-84b88a80-1977-11e9-8c18-a9918028e3f9.png)

> [A sliding cable model for rockfall barrier simulations using dynamic relaxation, R. BOULAUD, C. DOUTHE]

Is there the possibility to do realize this in GID? I am using the 3 noded line which is maximum so far I guess and here the node numbering is sth. I don't like and also the interpolation of the geometry ......

Looking forward to your answer!
Klaus

**Comment by jginternational** [comment]
I don't understand the question.

Let me ask @escolano

**Comment by KlausBSautter** [comment]
is there a possibility to visualize an arbitrary noded line as a linear connection between the nodes in GID? :metal:

**Comment by escolano** [comment]
I don't understand also the exact requirement of this question,
as you pointed in GiD you can have quadratic degree for most elements, also for line elements (line of 3-nodes). 
It seems that in fact you don't require high degree, and linear segments are enough to you. You can for example 'emulate' that 2-node line consecutive elements of a curve represent a single entity for your simulation (e.g. you can group them for your purpose: using GiD groups, or a condition with an id field, or GiD layers, or GiD materials)
For GiD postprocess is possible to define element results on line-elements with an arbitrary amount of 'gauss points'. This is a common why to represent a local graph value, like bending or shear effort on bars. This way is not valid to fully represent the displacement of the bar, the geometry is represented only by a linear segment of 2-nodes or a parabolic segment of 3 nodes (quadratic mesh)

**Comment by escolano** [comment]
To simplify this explanation assume that GiD has only linear elements, not quadratic ones (probably a piecewise polygon linear approximation of the shape is enough for you)

Then to generate the data in preprocess I have suggested that do you consider a collection of n consecutive line elements as a 'macro-element' of n+1 nodes, 
for example in Kratos - Structural use a 'Part' and assigg them one or more lines that define a macro-element.
then in the calculation file (*.mdpa) the problemtype could write a line by part, similar to your block 

Then in postprocess you must do nothing special, simply write the nodal or elemental results as usual (1 gauss point by element could be enough to represent its result)

**Comment by escolano** [comment]
other possibility is to use in preprocess only 1 line element to represent your 'macro-element' and then in the mdpa could write it as it was virtually divided in multiple aligned elements (must invent 'new ids' for the new 'virtual inner nodes')
and then for postprocess could define an elemental 'on gauss points' result on the element, with as much gauss points as number of nodes of your 'virtual division', to represent the value of your result along the line element (like a graph in local bar coordinates)

**Comment by escolano** [comment]
![image](https://user-images.githubusercontent.com/39376606/51487757-1ecb6900-1da4-11e9-9494-5987259a3437.png)
This is an image of postprocess with 2 elements and 11 gauss points by element representing the bending effort

**Comment by KlausBSautter** [comment]
@escolano thanks ! I found a solution :)
