### ISSUE TITLE
DEM - Fluid application

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#523]
Hi you all!

I've almost finished a first iteration to create this DEM - Fluid app

It's still in a branch, and there's still a lot to do in the ProjectParameters section, but you can check it in the branch /add-fluid-dem-application

Maybe we can meet on monday next week to have a look (19/02/2019)

JG

**Comment by ipouplana** [comment]
Great, thanks!

**Comment by farrufat-cimne** [comment]
I will merge the updated DEM branch into the master so the improvements are available for the coupled DEM interfaces.

**Comment by GuillermoCasas** [comment]
Sorry,  @jginternational, I had a rough week last week. Can we meet this week? What about on 27/02 afternoon?

**Comment by jginternational** [comment]
@GuillermoCasas 27/02 at 16h 👍

**Comment by GuillermoCasas** [comment]
@jginternational OK, 16:00.

**Comment by jginternational** [comment]
- Bug: DEM example old version.
- feature: List of hydrodynamic_law_parameters in project params (one for each DEM Property)
- Check PARTICLE_SPHERICITY in properties (inlet & dem)
- Injector type for swimming in inlet process
