### ISSUE TITLE
Error when selecting DEM parts in DEM-PFEM interface

### ISSUE THREAD

**Issue by AFranci** [KratosMultiphysics/GiDInterface#530]
We get the error here below whenever we select the DEM 'Parts' in the DEM-PFEM interface. 
After that it is  impossible to go on with the construction of the problem. 
Some idea? Thanks in advance.
Alessandro

NodeTest: Expected "WCARDNAME" for '' 
NodeTest: Expected "WCARDNAME" for '' 
    while executing
"$domNode selectNodes [spdAux::getRoute $schemeUN]"
    (procedure "spdAux::ProcGetElements" line 8)
    invoked from within
"spdAux::ProcGetElements $domNode $args"
    ("eval" body line 3)
    invoked from within
"eval [$procNode text]"
    (procedure "gid_groups_conds::eval_proc" line 69)
    invoked from within
"gid_groups_conds::eval_proc $proc $domNode"
    (procedure "_get_attribute_value" line 5)
    invoked from within
"_get_attribute_value $domNode $res"
    (procedure "get_domnode_attribute" line 6)
    invoked from within
"get_domnode_attribute $valueNode dict"
    (procedure "::boundary_conds::Snit_method_fill_data_window_values" line 67)
    invoked from within
"$self _fill_data_window_values $w $domNode $valueNodes $title"
    (procedure "::boundary_conds::Snit_method_fill_data_window" line 15)
    invoked from within
"$self _fill_data_window $win.data $domNode $title"
    (procedure "::boundary_conds::Snit_methodapply_cond" line 129)
    invoked from within
"$self apply_cond -what apply -open_window $open_window"
    (procedure "::boundary_conds::Snit_methodexecute_select" line 45)
    invoked from within
".gid.central.boundaryconds.gg execute_select 70 295"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 [linsert $args 0 $self]"
    invoked from within
"::snit::RT.CallInstance ::boundary_conds::Snit_inst1 execute_select 70 295 "
    (command bound to event)

**Comment by maceligueta** [comment]
@jginternational : is the DEM-PFEM going into the Release 7.0?

**Comment by jginternational** [comment]
Do you need it? @maceligueta

**Comment by maceligueta** [comment]
I don't know what's the policy or the procedure when packing a Release for the GUI, just asking in order to know whether the bugfix will go just to `master `or both to `master `and to `release-7.0`.

**Comment by jginternational** [comment]
Can you check if it's working fine @AFranci ?

**Comment by AFranci** [comment]
Thank you Javier, now it seems to work well! At least I don't have that error. 

However, I still have two warning messages. 

One when I create the mesh. It is just displaying 
'5 6 7 8'

And the other one when I run the analysis and it is writing
'DEM::write::GetNodesForGraphs'

After that, the analysis crashes, but I think that this is due to the last modifications of @GuillermoCasas that are not still supported by the PFEM-DEM interface. In this case the error is:

Traceback (most recent call last):
  File "MainKratos.py", line 40, in <module>
    Solution(model).Run()
  File "MainKratos.py", line 30, in __init__
    import swimming_DEM_PFEM_algorithm
ModuleNotFoundError: No module named 'swimming_DEM_PFEM_algorithm'

**Comment by jginternational** [comment]
About the numeric message , I think that @farrufat-cimne added it in kratos.gid\apps\DEM\write\write_utils.tcl lines 556 and 557

**Comment by jginternational** [comment]
I reopen this since
