### ISSUE TITLE
Apps in Release 7.0

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#541]
List of published apps in the 7th release #533 

- [x] Fluid Dynamics
- [x] Structural
- [x] FSI
- [x] Convection diffusion
- [x] Buoyancy
- [x] Conjugate Heat Transfer
- [x] DEM
- [x] Solid
- [x] Embedded fluid
- [ ] Potential fluid
- [ ] Pfem
- [ ] Pfem fluid
- [ ] Pfem fluid + DEM
- [ ] DEM + Fluid
- [ ] Stenosis W.
- [ ] Stent W.
- [x] MPM

According to the list  and discussion in #533

**Comment by jginternational** [comment]
@KratosMultiphysics/technical-committee

**Comment by maceligueta** [comment]
Are all those options already packed in the computational part of the Release?

**Comment by jginternational** [comment]
@roigcarlo can answer @maceligueta better

**Comment by roigcarlo** [comment]
@maceligueta From my part the list of applications compiled are the ones in the list below, but notice that some of the interfaces belong to coupling solutions of the apps. In this case Buoyancy and Conjugate  = Fluid + ConvectionDiffusion. So the relation will not be 1 to 1. I would say that everything in the interface is covered by these applications, but I don't know the nuances of every single interface on GiD so I may be wrong:

- EigenSolversApplication
- ConstitutiveModelsApplication
- SolidMechanicsApplication
- ParticleMechanicsApplication
- MeshMovingApplication
- ConvectionDiffusionApplication
- DamApplication
- PoromechanicsApplication
- StructuralMechanicsApplication
- FSIApplication
- FluidDynamicsApplication
- DemApplication
- SwimmingDEMApplication
- Metis (Linux only)
- TrilinosApplication (Linux only)

**Comment by rubenzorrilla** [comment]
I've just tried to set up a case using the embedded fluid GUI and works as expected as well as so it does the predefined cylinder example (I'm pinning it in the list above).

**Comment by josep-m-carbonell** [comment]
@jginternational  the interface for the Solid is not working propertly in linux, in the examples of 3D the calculation files are not written, this error appear:

invalid command name ""
invalid command name ""
    while executing
"$solver getInputPn $param_name"
    (procedure "spdAux::ProcGetSolverParameterValues" line 9)
    invoked from within
"spdAux::ProcGetSolverParameterValues $domNode $args"
    ("eval" body line 3)
    invoked from within
"eval [$procNode text]"
    (procedure "gid_groups_conds::eval_proc" line 69)
    invoked from within
"gid_groups_conds::eval_proc $proc $domNode"
    (procedure "_get_attribute_value" line 5)
    invoked from within
"_get_attribute_value $domNode $res"
    (procedure "get_domnode_attribute" line 6)
    invoked from within
"get_domnode_attribute $node values"
    (procedure "spdAux::ForceTreePreload" line 4)
    invoked from within
"spdAux::ForceTreePreload"
    (procedure "Kratos::WriteCalculationFilesEvent" line 11)
    invoked from within
"Kratos::WriteCalculationFilesEvent"
    invoked from within
".gid.menu.button7.m.m invoke active"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke active]"
    (procedure "tk::MenuInvoke" line 50)
    invoked from within
"tk::MenuInvoke .gid.menu.button7.m.m 1"
    (command bound to event)

I have not checked it in Windows yet, but something has been broken in the master. Please can you check it?

**Comment by josep-m-carbonell** [comment]
@jginternational  in Windows happens the same.

**Comment by jginternational** [comment]
@josep-m-carbonell fixed
