### ISSUE TITLE
reproducible problem when trying to use the beam of the structural mechancis application

### ISSUE THREAD

**Issue by agiuliodori** [KratosMultiphysics/GiDInterface#553]
We have been testing the problemtype, actually as a part of the of the Stent application, but the problem is most probably of the underlying StruturalMechanicsApplciation.

for the problem that can be found at the link

https://www.dropbox.com/s/08g9g89azymp2mv/test_beam_1.gid.zip?dl=0

we get a problem when we try to change
1- strategy -> Quasi-Static
2 - end time to 40.0 (here it explodes)

stack trace is
```

invalid command name ""
invalid command name ""
    while executing
"$solst getScheme $schemeId"
    (procedure "::Model::GetAvailableElements" line 7)
    invoked from within
"::Model::GetAvailableElements $solStratName $schemeName"
    (procedure "Structural::xml::ProcGetElementsStructural" line 18)
    invoked from within
"Structural::xml::ProcGetElementsStructural $domNode $args"
    ("eval" body line 3)
    invoked from within
"eval [$procNode text]"
    (procedure "gid_groups_conds::eval_proc" line 69)
    invoked from within
"gid_groups_conds::eval_proc $proc $domNode"
    (procedure "_get_attribute_value" line 5)
    invoked from within
"_get_attribute_value $domNode $res"
    (procedure "get_domnode_attribute" line 6)
    invoked from within
"get_domnode_attribute $domNode dict"
    (procedure "gid_groups_conds::give_printable_value" line 35)
    invoked from within
"gid_groups_conds::give_printable_value $childNode"
    (procedure "::boundary_conds::Snit_method_add_to_tree_from_dom" line 147)
    invoked from within
"$self _add_to_tree_from_dom [$childNode childNodes] $id  $state"
    (procedure "::boundary_conds::Snit_method_add_to_tree_from_dom" line 137)
    invoked from within
"$self _add_to_tree_from_dom [$childNode childNodes] $id  $state"
    (procedure "::boundary_conds::Snit_method_add_to_tree_from_dom" line 101)
    invoked from within
"$self _add_to_tree_from_dom $childNodes $id $state"
    (procedure "::boundary_conds::Snit_methodactualize_do" line 55)
    invoked from within
"$self actualize_do -do_focus $options(-auto_take_focus) $id"
    (procedure "::boundary_conds::Snit_methodactualize" line 6)
    invoked from within
"$self actualize $item"
    (procedure "::boundary_conds::Snit_methodactualize_domNode" line 52)
    invoked from within
"$self actualize_domNode {*}$actualize_nodesList"
    (procedure "::boundary_conds::Snit_methodedit_value_or_blockdata_ok" line 127)
    invoked from within
".gid.central.boundaryconds.gg edit_value_or_blockdata_ok 67 10.0"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 [linsert $args 0 $self]"
    invoked from within
"::snit::RT.CallInstance ::boundary_conds::Snit_inst1 edit_value_or_blockdata_ok 67 10.0"
    (<Edit-accept> binding on .gid.central.boundaryconds.gg.ft.t)
```

**Comment by agiuliodori** [comment]
Here is attached the link with a simplier geometry with the same problem when aplicating similar conditions:

https://www.dropbox.com/s/igr0ndssjv3j9t7/test_beam_2.gid.zip?dl=0

**Comment by RiccardoRossi** [comment]
@KlausBSautter aside of the gid bug, the latest link is also a good example to check for errors in the beam... it only works for extremely small increments!!

**Comment by KlausBSautter** [comment]
I am looking at you example of a cantilever right now (2D) @RiccardoRossi , I am a bit confused as the 2D beam always worked really good (the 3d works for the cantilever). For this example I don't see any problem data.. What cross-section, material, etc. did you use?

**Comment by KlausBSautter** [comment]
ok I was searching for the problem the while day but could not really find the reason for this. One thing though: 
we should add 
`  if (this->GetProperties().Has(TORSIONAL_INERTIA) == false ||
      this->GetProperties()[TORSIONAL_INERTIA] <= numerical_limit) {`
for all intertias. This example has inertias which are smaller than my numerical limit

**Comment by RiccardoRossi** [comment]
why don t you just check that it is different from zero?

**Comment by KlausBSautter** [comment]
yes also good

**Comment by KlausBSautter** [comment]
whereas checking if it is different from zero would have not failed in this case but 
`[TORSIONAL_INERTIA] <= numerical_limit)` did

**Comment by RiccardoRossi** [comment]
so please do the fix. We also need to backport this to release. @agiuliodori please check if once added the fix it works

**Comment by RiccardoRossi** [comment]
btw, depending on the configuation, it may also work with zero torsional stiffness.

the important thing is that the variable is there

**Comment by agiuliodori** [comment]
@RiccardoRossi I tried it again; when selecting "Quasi-Static" and changing the "End time" this error appears but the structural 'tree' doesn't disappear now.


invalid command name ""
invalid command name ""
    while executing
"$SolStrat getInputPn $paramName"
    (procedure "::Model::CheckSolStratInputState" line 3)
    invoked from within
"::Model::CheckSolStratInputState $SolStrat $paramName"
    (procedure "::spdAux::SolStratParamState" line 14)
    invoked from within
"::spdAux::SolStratParamState $domNode"
    (procedure "spdAux::ProcSolStratParamState" line 3)
    invoked from within
"spdAux::ProcSolStratParamState $domNode $args"
    ("eval" body line 3)
    invoked from within
"eval [$procNode text]"
    (procedure "gid_groups_conds::eval_proc" line 69)
    invoked from within
"gid_groups_conds::eval_proc $proc $domNode"
    (procedure "_get_attribute_value" line 5)
    invoked from within
"_get_attribute_value $domNode $res"
    (procedure "get_domnode_attribute" line 6)
    invoked from within
"get_domnode_attribute $iNode state normal"
    (procedure "::boundary_conds::Snit_methodis_button" line 12)
    invoked from within
"$self is_button [$childNode selectNodes $xp]"
    (procedure "::boundary_conds::Snit_method_add_to_tree_from_dom" line 62)
    invoked from within
"$self _add_to_tree_from_dom [$childNode childNodes] $id  $state                        "
    (procedure "::boundary_conds::Snit_method_add_to_tree_from_dom" line 60)
    invoked from within
"$self _add_to_tree_from_dom $childNodes $id $state"
    (procedure "::boundary_conds::Snit_methodactualize_do" line 55)
    invoked from within
"$self actualize_do -do_focus $options(-auto_take_focus) $id"
    (procedure "::boundary_conds::Snit_methodactualize" line 6)
    invoked from within
"$self actualize $item"
    (procedure "::boundary_conds::Snit_methodactualize_domNode" line 52)
    invoked from within
"$self actualize_domNode {*}$actualize_nodesList"
    (procedure "::boundary_conds::Snit_methodedit_value_or_blockdata_ok" line 127)
    invoked from within
".gid.central.boundaryconds.gg edit_value_or_blockdata_ok 65 30"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 [linsert $args 0 $self]"
    invoked from within
"::snit::RT.CallInstance ::boundary_conds::Snit_inst1 edit_value_or_blockdata_ok 65 30"
    (<Edit-accept> binding on .gid.central.boundaryconds.gg.ft.t)

**Comment by RiccardoRossi** [comment]
@jginternational ping

**Comment by jginternational** [comment]
I'll check it this afternoon

**Comment by jginternational** [comment]
Ok @RiccardoRossi @philbucher 
I've checked that there is no Solution strategy for Quasi-Static analysis.

Shall I set the one for static or the one for dynamic?

**Comment by philbucher** [comment]
Nope there is no quasistatic one.
Quasistatic == Static with several time steps
=> set the Static strategy


Why did it break? It worked when we initially did it

**Comment by jginternational** [comment]
I don't know, but one solution would be adding more examples, so I can run the automatic tests

I think it's fixed
