### ISSUE TITLE
supporting for hexahedra element type

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/GiDInterface#586]
Don't Gidinterface support Hexahedra element type? there pop up one error when i am trying to draw hexahedra mesh for hexahedron beam.
![Screenshot from 2019-04-26 18-49-40](https://user-images.githubusercontent.com/26964544/56803360-fc3e6580-6854-11e9-9eeb-1ddb36a2e45f.png)

**Comment by loumalouomega** [comment]
You need to create a regular mesh and assign sizes in each edge

**Comment by ZhimingGuo** [comment]
what does the regular mesh mean?

**Comment by ZhimingGuo** [comment]
it is done, thanks
