### ISSUE TITLE
No output files (mdpa json) are written in MPM

### ISSUE THREAD

**Issue by VeronikaSinger** [KratosMultiphysics/GiDInterface#590]
I tried to use the current GIDInterface for MPM but I cannot write out any mdpa or json files. I tried some earlier versions; e.g the version 10 weeks ago (Merge pull request #527 from KratosMultiphysics/hotfix-materials-file ) is working as usual.

**Comment by jginternational** [comment]
Hi @ga69kid 

Could you attach the model you are trying to calculate? (generate a zip containing the .gid folder of the model)

**Comment by ga69kid** [comment]
Hi,
here is a small example. 
[Test.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/3160486/Test.gid.zip)
Thanks for the support.

**Comment by jginternational** [comment]
You've detected a bug. 👍 

The fast way to make it work untill I fix it is to un-collapse (open) this tree sections: 
![image](https://user-images.githubusercontent.com/5918085/58017965-d88fd780-7b01-11e9-9d05-8152696e89ea.png)
