### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#603]
I have the following error message loading the problemtype:

![imagen](https://user-images.githubusercontent.com/19991680/59633642-43f2b680-914d-11e9-9b69-f81a686d8b62.png)

**Comment by jginternational** [comment]
Wich is your GiD version?

I assume you are in the master branch of kratos GiDInterface

**Comment by loumalouomega** [comment]
last developer version, last master GidInterface

**Comment by jginternational** [comment]
I've tried to reproduce the error in a new clean linux system (Ubuntu 18) with a new GiD 14.1.3d and everything goes fine.

I'll need more info

**Comment by loumalouomega** [comment]
The only difference is that I use Ubuntu 19.04

**Comment by jginternational** [comment]
Did you install GiD using the installer or the tar file?

**Comment by loumalouomega** [comment]
I tried both

**Comment by loumalouomega** [comment]
Just to mention that release gives the same error

**Comment by loumalouomega** [comment]
@escolano any idea?

**Comment by loumalouomega** [comment]
I can confirm that is something on the 19.04, in a clean user configuration same error (installing from zero)

**Comment by loumalouomega** [comment]
@jginternational can you tell me if it is safe to deactivate this command?

**Comment by jginternational** [comment]
You can try to open a clean GiD, with no problemtype loaded, and execute in the command line
-np- source {/home/vicente/bin/GiD/scripts/customLib/customLib/gid_groups_conds.tcl}

If the error is still there, it's a GiD problem

**Comment by jginternational** [comment]
Anyway I've tried it in a new clean Ubuntu 19.04, GiD 14.1.3d from tar.gz and it works fine

**Comment by escolano** [comment]
By the error message it is like the file /home/vicente/bin/GiD/scripts/customLib/customLib/gid_groups_conds.tcl was corrupted
(doesn't try to open it with a text editor, it is a binary encrypted file)
try to do a md5sum of the file and let us know to check its integrity
Confirm that the same happen using the installer and the .tar.gz (maybe is corrupted only in one of them)
What happen if do you start GiD and instead Kratos do you load the problemtype Examples->cmas2d_customlib ? (the same problematic file will be loaded. The same error is raised?)

**Comment by jginternational** [comment]
@loumalouomega is this still happening?

**Comment by loumalouomega** [comment]
Yes, but I could not try anything yet.

**Comment by loumalouomega** [comment]
> By the error message it is like the file /home/vicente/bin/GiD/scripts/customLib/customLib/gid_groups_conds.tcl was corrupted
> (doesn't try to open it with a text editor, it is a binary encrypted file)
> try to do a md5sum of the file and let us know to check its integrity
> Confirm that the same happen using the installer and the .tar.gz (maybe is corrupted only in one of them)

md5sum looks OK:
![imagen](https://user-images.githubusercontent.com/19991680/60724160-f8565000-9f35-11e9-8d6a-22f8329f0fa0.png)

> What happen if do you start GiD and instead Kratos do you load the problemtype Examples->cmas2d_customlib ? (the same problematic file will be loaded. The same error is raised?)

Looks like:

![imagen](https://user-images.githubusercontent.com/19991680/60724049-af060080-9f35-11e9-8c99-86f464d6b441.png)

**Comment by loumalouomega** [comment]
Same error with 14.1.3d @escolano

**Comment by escolano** [comment]
off course, the error already was with 14.1.3d, it's not?
have you tried in another computer? (we are not able to reproduce it in our computers, also with the same Linux version)
And what about previous GiD versions? (simply install and load cmas2d_customlib)
all versions fail? which is the higher version that doesn't fail, if any?

**Comment by loumalouomega** [comment]
I tried in my two computers, same error. It doesn't happen with GiD 14.1.0d, but the ProblemType doesn't allow me to use that version of GiD

**Comment by escolano** [comment]
try first copying the folder <GiD>\scripts\customLib\customLib_utils_c of version 14.1.0d into 14.1.3d
if continue failing try then to replace the whole folder <GiD>\scripts\customLib
and let me know the results

**Comment by loumalouomega** [comment]
i will check, thanks

**Comment by loumalouomega** [comment]
No, does not work

**Comment by jginternational** [comment]
I've installed gid also in a clean Kubuntu 19.04 and works fine.
I don't know how to proceed

**Comment by loumalouomega** [comment]
Mee too, I tried with a new user, so is not part of my local configurations.

**Comment by loumalouomega** [comment]
I use zsh instead of bash, can be related?

**Comment by loumalouomega** [comment]
@jginternational do I really need to use GiD14.1.2 in order to sue the problemtype?, the last stable release works on my machine

**Comment by jginternational** [comment]
It will work in GiD 14.1.2d, as it the current MinimumGiDVersion, 
We are soon releasing the new 14.1.4d, hope that works on your machines

**Comment by jginternational** [comment]
There is a hard restriction in the use of GiD 14 version, so it should work in any GiD 14. but I cannot guarantee that it works perfect for any version previous to that 14.1.2d

Anyway, a new release is coming soon, hope it works for you

**Comment by loumalouomega** [comment]
Can at least use developer mode on stable releases?

**Comment by escolano** [comment]
Try the installer of GiD 14.1.3d Linux x64, it seems that the problem has been solved

**Comment by loumalouomega** [comment]
Indeed it is solved, thanks @escolano

**Comment by jginternational** [comment]
bravo

**Comment by pasenau** [comment]
Hi,
please try the last 'preliminary' version 14.1.5e which you can find here:
https://www.gidhome.com/download/developer-versions/linux64/
Thanks for your patience,
