### ISSUE TITLE
FSI examples broken

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#610]
Changes in the Structural app have broken the FSI

Check the write settings:
```
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\kratos\python_scripts\gid_output_process.py", line 11, in Factory
    model_part = Model[settings["Parameters"]["model_part_name"].GetString()]
RuntimeError: Error: The ModelPart named : "fluid_computational_model_part" was not found as SubModelPart of : "Structure". The total input string was "Structure.fluid_computational_model_part"
```

**Comment by philbucher** [comment]
I think this is an error in the settings, at least on first sight this is not related to changes in the Structural (recently we didn't change much)
ping @rubenzorrilla

**Comment by rubenzorrilla** [comment]
Sorry, I'll take care of this ASAP.

**Comment by rubenzorrilla** [comment]
I agree it seems to be an error in the writing of the json settings. It is setting the "Structure" model part as root model part of the "fluid_computational_model_part".

**Comment by jginternational** [comment]
@rubenzorrilla Fixed!

**Comment by rubenzorrilla** [comment]
Thanks!
