### ISSUE TITLE
KratosInterface apparently does not show the main menu

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/GiDInterface#613]
Dear all,
Lately I've been using the latest version of the GiD Interface and now, when I load the ptype, the main menu it's not shown (Structural Mech Application).
Am I doing any wrong @jginternational ?
THX

@loumalouomega said that in linux it wasn't working too

**Comment by rubenzorrilla** [comment]
Have you tried Kratos --> Kratos data?

**Comment by AlejandroCornejo** [comment]
I've loaded the ptype (data->ptype->Kratos) and nothing happens :S So I do not have the Kratos folder

**Comment by rubenzorrilla** [comment]
You should have it in the top ribbon. If not you are not properly loading the problem type.

**Comment by AlejandroCornejo** [comment]
yeah it should be but it doesn't... I've downloaded the interface from github, copied in the ptype folders and gid says:
`Problem type loaded. 6 conditions read.`
but nothing else happens..

**Comment by AlejandroCornejo** [comment]
Ok! As @escolano told me, downloading a newer version of GiD the problem is solved.
THX

**Comment by jginternational** [comment]
https://github.com/KratosMultiphysics/GiDInterface/blob/master/kratos.gid/kratos.xml#L8

This should be 14.1.3d....

**Comment by RiccardoRossi** [comment]
not long ago we decided to wait to move to newer version until support was
stable in all the OSs

dud we reach that point?

**Comment by jginternational** [comment]
@RiccardoRossi a couple months ago, when we realized that it wasn't working for GiD 13.
I asked a TUM member to check if there was someone there using GiD 13 and @jcotela was the only one, so he updated and we pushed the MinimumGiDVersion to 14.1.2d
