### ISSUE TITLE
PFEM Conditions applied to Bodies

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#62]
A proposal for applying pfem conditions to Bodies (blockdata that contains Parts):

Try: 
- When a body is created: 
    - Create a group with the same name
If this is not possible (check customlib events for blockdata)
- When a part is created: 
    - If the Body group does not exists: Create a group for the body

This Body group can be:
- Empty
    - Pros: Better performance
    - Cons: If user draws it, any entity is drawn
- Updated with it's parts' elements
    - Pros: If user draws it, the entities of all it's parts are drawn
    - Cons: Lower performance

- Blocked in the GiD groups window (forbidden to rename it, delete it, assign entities...)

In the write event, it can be:
- Skipped
    - Pros: MDPA does not grow innecesarily
    - Cons: Need to implement a specific function for skipping this submodelparts and for the JSON
- Written (with or without entities)
    - Pros: We can use the common functions for writing (easier) MDPA and JSON
    - Cons: We do not need that submodelpart

My personal choice is:
- Body group updated with it's parts' entities
- Submodelparts written in the MPDA even if then ignored

I'll start with this development this way, but it's going to take some time, and I'll do it to be 'easy to change', so if we decide to change any of these decisions, not to start again.
@KratosMultiphysics/pfem

**Comment by maceligueta** [comment]
Ok. Let's put it in a branch so we can test it.
