### ISSUE TITLE
GiDx64.14.1.4d + Kratos Problemtype on Ubuntu 18 error

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/GiDInterface#626]
Kratos 7.0.2 from internet retrieve or symbolic linking I get the following error:
![image](https://user-images.githubusercontent.com/15231695/61800054-98641280-ae2c-11e9-8cfd-6e473b4ede82.png)

The same configurations runs well with GiDx64.14.0.1.

If I try loading the Kratos problemtype from the working GiD 14.0.1 I get the following error:
![image](https://user-images.githubusercontent.com/15231695/61800227-dc571780-ae2c-11e9-9e2d-32a79b82c705.png)

Any input on this?

**Comment by loumalouomega** [comment]
I had the same error...

**Comment by loumalouomega** [comment]
I think is related with the Ubuntu version

**Comment by jginternational** [comment]
@mpentek have you tried to load the problemtype Examples/cmas2d_customlib?

**Comment by loumalouomega** [comment]
Same error as #603

**Comment by mpentek** [comment]
@jginternational 

When loading Examples/cmas2d_customlib from itself:
![image](https://user-images.githubusercontent.com/15231695/61801802-b4b57e80-ae2f-11e9-85e5-4c9f5354dbcd.png)

When loading Examples/cmas2d_customlib from GiD 14.0.1:
![image](https://user-images.githubusercontent.com/15231695/61801876-d0208980-ae2f-11e9-8c49-b62bd98f5077.png)


We had an email exchange as I had an issue installing GiD14 on Ubuntu18 with the GUI, but installation seems fine with the console mode. The release version of GiD14 and the previous developer version both installed fine with the console mode and the Kratos problemtype worked as well, even symbolic linking.

I have Ubuntu 18.04.2 LTS.

**Comment by loumalouomega** [comment]
Try the new version of GiD, it solved my issue

**Comment by mpentek** [comment]
No, did not help. I have issues I671 twice again.

**Comment by mpentek** [comment]
I updated the name for the version 14.1.4d. Still valid also the 14.1.3d.

**Comment by pasenau** [comment]
Hi,
please try the last 'preliminary' version 14.1.5e which you can find here:
https://www.gidhome.com/download/developer-versions/linux64/
Thanks for your patience,
