### ISSUE TITLE
Error in DEM+PFEM interface 

### ISSUE THREAD

**Issue by MZecchetto** [KratosMultiphysics/GiDInterface#629]
Dear all,
I'm facing an issue building a PFEM+DEM model. I'm not able to generate the .mdpa file, even with the embedded example. I got the following error:
![image](https://user-images.githubusercontent.com/50821222/62364531-08a41f80-b522-11e9-9b55-d862b5d33075.png)
Also the bounding box definition gives an error. 
![2](https://user-images.githubusercontent.com/50821222/62364758-a26bcc80-b522-11e9-903c-6d7fc355aab9.png)
I don't know if these two are related or not.
Any suggestion? 
Thanks in advance,
Massimiliano

**Comment by jginternational** [comment]
I'm checking it

**Comment by MZecchetto** [comment]
any news?
