### ISSUE TITLE
Rayleigh damping parameters in Structural Mechanics Application

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/GiDInterface#632]
Is it possible to add this feature? It would be great, so we don't need to modify the json files manually.
@jginternational @loumalouomega

**Comment by loumalouomega** [comment]
Do you mean the process that automatically calculates the parameters or the manual setting? (@msandre  does not recommend to do it automatically by default, as the modal analysis is complex by itself)

**Comment by maceligueta** [comment]
No, I meant the values of alpha and beta. Just add the possibility so set them from the GUI

**Comment by loumalouomega** [comment]
Well, @jginternational would you do it?

**Comment by jginternational** [comment]
I don't know what are we talking about!

**Comment by loumalouomega** [comment]
Can you add to the interface the possibility to set the two following parameters in implicit dynamic?

https://github.com/KratosMultiphysics/Kratos/blob/fd02fad9e384601bd22042c10f0f6a4b8717284a/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_implicit_dynamic_solver.py#L40

**Comment by jginternational** [comment]
Just `rayleigh_alpha `and `rayleigh_beta` ?

**Comment by loumalouomega** [comment]
Yep, looks like they only want that. In any case @maceligueta you can use the process to estimate the values properly

**Comment by maceligueta** [comment]
@loumalouomega . What happens with _explicit_ dynamic? Isn't it possible to use them if that is the case? I don't even know if it's implemented, however, in principle the Rayleigh parameters can be used as long as it's a dynamic case.

**Comment by loumalouomega** [comment]
it can be used indeed, but I don't remember right now the implementation (I did it quite time ago). The thing is, I would use only mass damping, as the stiffness damping is expensive on explicit simulations

**Comment by loumalouomega** [comment]
BTW: 

https://github.com/KratosMultiphysics/Kratos/blob/fd02fad9e384601bd22042c10f0f6a4b8717284a/applications/StructuralMechanicsApplication/python_scripts/automatic_rayleigh_parameters_computation_process.py

**Comment by loumalouomega** [comment]
Yes, you can use it in explicit:

https://github.com/KratosMultiphysics/Kratos/blob/fd02fad9e384601bd22042c10f0f6a4b8717284a/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_explicit_dynamic_solver.py#L38

BTW, there are optimizations still pending for the explicit

**Comment by jginternational** [comment]
So, if analysis is dynamic, add those 2 parameters, right?

**Comment by loumalouomega** [comment]
Yes

**Comment by jginternational** [comment]
Closable?
