### ISSUE TITLE
Generic conditions are always 3D, even in 2D problems

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#634]
https://github.com/KratosMultiphysics/GiDInterface/blob/0b73e4959476c2308a97b8459a2867d00c1a9db8/kratos.gid/apps/Common/xml/Conditions.xml#L7

Can this be changed depending of the dimension?

**Comment by rubenzorrilla** [comment]
I think It can be filtered.

**Comment by loumalouomega** [comment]
I assume, it is done for the rest of elements and conditions, but I just noticed

**Comment by jginternational** [comment]
@rubenzorrilla 
This special condition works different

@loumalouomega 
You are right, they are always in 3D, but we shouldn't change the name for the LineCondition3D2N to LineCondition2D2N because you'll still need the 3d one.

Let me think about a solution
