### ISSUE TITLE
Possibility to choose what results are printed. Gid, VTK or both in Structural Mechanics Application

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/GiDInterface#635]
As far as I've seen recently, two output processes are written in the json file. One for GiD and another one for Paraview. I think that the user cannot deactivate one of them, so both are printed always. Can we add a couple of switches in the tree to add this ability to select if they are active or not?

**Comment by loumalouomega** [comment]
I thought we already add that:

![imagen](https://user-images.githubusercontent.com/19991680/63514814-c1d69380-c4e9-11e9-94e3-ca7c9d569399.png)

**Comment by maceligueta** [comment]
Sorry, we did not see it. Closing.
