### ISSUE TITLE
Cannot load problemtype of Kratos in GiD

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/GiDInterface#642]
I am getting the following error when trying to load the latest version of the problemtype in the current developer version of GiD. It is the same when I am trying to load the current release:

![gid_error](https://user-images.githubusercontent.com/25392219/64333259-7a1a3680-cfd6-11e9-90a0-71696801f4a0.png)

Is this a known problem?

**Comment by jginternational** [comment]
It used to happen long long time ago.
Anyway, it seems that you are using the GiD version 14.1.2d and the current developer is 14.1.4d

https://www.gidhome.com/download/developer-versions/linux64/

**Comment by AndreasWinterstein** [comment]
Here the output with GiD 14.1.4.d.
![gid_error](https://user-images.githubusercontent.com/25392219/64338923-1e09df00-cfe3-11e9-9eb2-88a31f4b8e7d.png)

It is the same.

**Comment by jginternational** [comment]
- Which linux system are you using?
- Can you try the Examples/cmas2d_customlib problemtype? Just to see if the same error appears

**Comment by jginternational** [comment]
Same as #626 and #630

**Comment by AndreasWinterstein** [comment]
Am am using Ubuntu 18. It was working perfectly before. The Example gives the same error.

**Comment by AndreasWinterstein** [comment]
I talked to @mpentek . It seems that only the release version is working at the moment in linux.

**Comment by AndreasWinterstein** [comment]
I tested it on my laptop with the same Ubuntu version. There it is working.

**Comment by pasenau** [comment]
Hi,
please try the last 'preliminary' version 14.1.5e which you can find here:
https://www.gidhome.com/download/developer-versions/linux64/
Thanks for your patience,

**Comment by AndreasWinterstein** [comment]
With this it is working again. Thank you. I will close this issue.
