### ISSUE TITLE
Run PfemSolidMechanicsApplication examples

### ISSUE THREAD

**Issue by Gaoliu19910601** [KratosMultiphysics/GiDInterface#648]
When I try to run the test_examples in PfemSolidMechanicsApplication:https://github.com/KratosMultiphysics/Kratos/tree/master/applications/PfemSolidMechanicsApplication/test_examples, I do not know how to run those examples. There are recognized as gid file but not specific type(mpm. pfem and so on). How I can run these examples in GID?

**Comment by jginternational** [comment]
Hi @Gaoliu19910601 

Those tests (in the kratos repository, not in the gui) are from an extremely old interface that kratos used to have several years ago. (I started working on Kratos in 2011 and that gui was already disappeared).

You are right. There are no GUI examples for the PFEM Solid application

@KratosMultiphysics/pfem

**Comment by Gaoliu19910601** [comment]
Hi @jginternational 
   Thanks for your answer. Then I will close this issue.
