### ISSUE TITLE
Error in MPM application

### ISSUE THREAD

**Issue by Gaoliu19910601** [KratosMultiphysics/GiDInterface#649]
Hi everyone
   It seems that the MPM application in the master branch can not be opened in GID and the error is 
![Screenshot from 2019-10-06 21-37-02](https://user-images.githubusercontent.com/48948507/66270034-7ef63280-e881-11e9-9860-e7133bcbf5f9.png)
can any one fix it?

**Comment by jginternational** [comment]
Thanks for the bug report!!

**Comment by Gaoliu19910601** [comment]
@jginternational  It seems that I cannot creat a part in the GID interface. It must be a bug.

**Comment by jginternational** [comment]
I fixed it here

https://github.com/KratosMultiphysics/GiDInterface/commit/a98fc33a5219164bf76983051af3fe3e0bd565e3

**Comment by Gaoliu19910601** [comment]
@jginternational 
I mean that when I try to click on the part icon to creat a part，there is no response. It seems that it did not work now.

**Comment by jginternational** [comment]
We updated the Structural app and had this side effect

You can test it now

**Comment by Gaoliu19910601** [comment]
Hi
@jginternational   When I try to run a case in GID interface in MPM. An error ocurred as 
Traceback (most recent call last):
  File "MainKratos.py", line 17, in <module>
    simulation = ParticleMechanicsAnalysis(model,parameters)
  File "/home/gaoliu/Kratos/applications/ParticleMechanicsApplication/python_scripts/particle_mechanics_analysis.py", line 29, in __init__
    super(ParticleMechanicsAnalysis, self).__init__(model, project_parameters)
  File "/home/gaoliu/Kratos/kratos/python_scripts/analysis_stage.py", line 43, in __init__
    self._GetSolver().AddVariables() # this creates the solver and adds the variables
  File "/home/gaoliu/Kratos/kratos/python_scripts/analysis_stage.py", line 201, in _GetSolver
    self._solver = self._CreateSolver()
  File "/home/gaoliu/Kratos/applications/ParticleMechanicsApplication/python_scripts/particle_mechanics_analysis.py", line 35, in _CreateSolver
    return CreateSolver(self.model, self.project_parameters)
  File "/home/gaoliu/Kratos/applications/ParticleMechanicsApplication/python_scripts/python_solvers_wrapper_particle.py", line 60, in CreateSolver
    return CreateSolverByParameters(model, solver_settings, parallelism)
  File "/home/gaoliu/Kratos/applications/ParticleMechanicsApplication/python_scripts/python_solvers_wrapper_particle.py", line 44, in CreateSolverByParameters
    solver = import_module(module_full).CreateSolver(model, solver_settings)
  File "/home/gaoliu/Kratos/applications/ParticleMechanicsApplication/python_scripts/mpm_implicit_dynamic_solver.py", line 13, in CreateSolver
    return MPMImplicitDynamicSolver(model, custom_settings)
  File "/home/gaoliu/Kratos/applications/ParticleMechanicsApplication/python_scripts/mpm_implicit_dynamic_solver.py", line 20, in __init__
    super(MPMImplicitDynamicSolver, self).__init__(model, custom_settings)
  File "/home/gaoliu/Kratos/applications/ParticleMechanicsApplication/python_scripts/mpm_solver.py", line 23, in __init__
    super(MPMSolver, self).__init__(model, custom_settings)
  File "/home/gaoliu/Kratos/kratos/python_scripts/python_solver.py", line 38, in __init__
    self.ValidateSettings()
  File "/home/gaoliu/Kratos/kratos/python_scripts/python_solver.py", line 56, in ValidateSettings
    self.settings.ValidateAndAssignDefaults(default_settings)
RuntimeError: Error: The item with name "rayleigh_alpha" is present in this Parameters but NOT in the default values
Hence Validation fails
I attach the gid here.
[mpm.gid.tar.gz](https://github.com/KratosMultiphysics/GiDInterface/files/3708269/mpm.gid.tar.gz)

**Comment by Gaoliu19910601** [comment]
Another question  is how to define a designated velocity of a pile (maybe it should be treated as a rigid body or just a body with a prescribed velocity?) which has a MohrCoulomb interaction with soil in MPM application, Does you know to do it.

**Comment by jginternational** [comment]
I think will be answered by @bodhinandach

**Comment by bodhinandach** [comment]
@Gaoliu19910601 you can do it by prescribing velocity to particles for moving boundaries. But you need to write it in specific derived functions from `particle_mechanics_analysis.py.`
As for the damping parameters, it is possible to use it for any constitutive laws, you just need to specify `RAYLEIGH_ALPHA` in your particle materials and the following string in your project parameters:

`"auxiliary_variables_list"           : ["RAYLEIGH_ALPHA"]`

Hope that this helps. I am really sorry for the slow reply.

**Comment by Gaoliu19910601** [comment]
Hi @bodhinandach 
I have added the  string  "auxiliary_variables_list" : ["rayleigh_alpha"]  in my project parameters ,but I do not know how to add rayleigh_alpha in  particle materials, because no matter where I place it ,

**Comment by bodhinandach** [comment]
The string should be capital. Did you check?

**Comment by jginternational** [comment]
@bodhinandach The thing here is that the Structural Application has the rayleig_alpha and beta parameters in the Implicit strategy, [See here](https://github.com/KratosMultiphysics/GiDInterface/blob/b4f98acca4ab67ada92f6995056f72e6fc323e73/kratos.gid/apps/Structural/xml/Strategies.xml#L6)

The error @Gaoliu19910601 is showing indicates that the parameter is written in the ProjectParameters.json and the solver does not understand it.

See an example of the solver settings section generated in a MPM 2D case in GiD:
```

"solver_settings"  : {
        "solver_type"                     : "Static",
        "model_part_name"                 : "MPM_Material",
        "domain_size"                     : 2,
        "echo_level"                      : 0,
        "analysis_type"                   : "non_linear",
        "model_import_settings"           : {
            "input_type"     : "mdpa",
            "input_filename" : "aaa_Body"
        },
        "material_import_settings"        : {
            "materials_filename" : "ParticleMaterials.json"
        },
        "time_stepping"                   : {
            "time_step" : 1.1
        },
        "rayleigh_alpha"                  : 0.0,
        "rayleigh_beta"                   : 0.0,
        "convergence_criterion"           : "residual_criterion",
        "displacement_relative_tolerance" : 0.0001,
        "displacement_absolute_tolerance" : 1e-9,
        "residual_relative_tolerance"     : 0.0001,
        "residual_absolute_tolerance"     : 1e-9,
        "max_iteration"                   : 10,
        "grid_model_import_settings"      : {
            "input_type"     : "mdpa",
            "input_filename" : "aaa_Grid"
        },
        "pressure_dofs"                   : false,
        "auxiliary_variables_list"        : ["RAYLEIGH_ALPHA"]
    }
```
And a fragment of the error shown:
```
RuntimeError: Error: The item with name "rayleigh_alpha" is present in this Parameters but NOT in the default values
Hence Validation fails
Parameters being validated are : 
{
    "analysis_type": "non_linear",
    "auxiliary_variables_list": [
        "RAYLEIGH_ALPHA"
    ],
    "convergence_criterion": "residual_criterion",
    "displacement_absolute_tolerance": 1e-09,
    "displacement_relative_tolerance": 0.0001,
    "domain_size": 2,
    "echo_level": 0,
    "grid_model_import_settings": {
        "input_filename": "aaa_Grid",
        "input_type": "mdpa"
    },
    "material_import_settings": {
        "materials_filename": "ParticleMaterials.json"
    },
    "max_iteration": 10,
    "model_import_settings": {
        "input_filename": "aaa_Body",
        "input_type": "mdpa"
    },
    "model_part_name": "MPM_Material",
    "pressure_dofs": false,
    "rayleigh_alpha": 0.0,
    "rayleigh_beta": 0.0,
    "residual_absolute_tolerance": 1e-09,
    "residual_relative_tolerance": 0.0001,
    "time_stepping": {
        "time_step": 1.1
    }
}
Defaults against which the current parameters are validated are :
{
    "analysis_type": "non_linear",
    "auxiliary_dofs_list": [],
    "auxiliary_reaction_list": [],
    "auxiliary_variables_list": [],
    "axis_symmetric_flag": false,
    "block_builder": true,
    "compute_reactions": false,
    "convergence_criterion": "Residual_criteria",
    "displacement_absolute_tolerance": 1e-09,
    "displacement_relative_tolerance": 0.0001,
    "domain_size": -1,
    "echo_level": 0,
    "element_search_settings": {
        "max_number_of_results": 1000,
        "search_algorithm_type": "bin_based",
        "searching_tolerance": 1e-05
    },
    "grid_model_import_settings": {
        "input_filename": "unknown_name_Grid",
        "input_type": "mdpa"
    },
    "linear_solver_settings": {
        "block_size": 3,
        "coarse_enough": 50,
        "coarsening_type": "aggregation",
        "gmres_krylov_space_dimension": 100,
        "krylov_type": "cg",
        "max_iteration": 200,
        "provide_coordinates": false,
        "scaling": false,
        "smoother_type": "damped_jacobi",
        "solver_type": "amgcl",
        "tolerance": 1e-07,
        "use_block_matrices_if_possible": true,
        "verbosity": 0
    },
    "material_import_settings": {
        "materials_filename": ""
    },
    "max_iteration": 20,
    "model_import_settings": {
        "input_filename": "unknown_name_Body",
        "input_type": "mdpa"
    },
    "model_part_name": "MPM_Material",
    "move_mesh_flag": false,
    "pressure_dofs": false,
    "problem_domain_sub_model_part_list": [],
    "processes_sub_model_part_list": [],
    "residual_absolute_tolerance": 1e-09,
    "residual_relative_tolerance": 0.0001,
    "time_stepping": {}
}

```

**Comment by bodhinandach** [comment]
@jginternational Thanks for clarifying!

**Comment by Gaoliu19910601** [comment]
@bodhinandach 
Hi, It seems the Release version does not have the above errors. 
In another,  I do not quite understand "you can do it by prescribing velocity to particles for moving boundaries. But you need to write it in specific derived functions from particle_mechanics_analysis.py ", could you explain it more detail. And Could we set the contact property (I need a Coulomb contact)?
Thanks a lot.

**Comment by jginternational** [comment]
I close this issue to clean up. If there are new questions please create a new issue ! Thanks!
