### ISSUE TITLE
Wind Tunnel Application

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#65]
Create a new application: **Wind Tunnel**

- [x] Create a logo
- [x] Initial window: 
    - Body fitted
    - Embedded

Starts Fluid app or Embedded in 3D mode.

The embedded toolbar to import an stl, move it, and create the tunnel, must be moved from the embedded application, to the Fluid. It must not be loaded automatically but must be available.
If Body fitted, when creating the tunnel, holes in the volume should be done

**Comment by jcotela** [comment]
Sorry, I closed it by mistake

**Comment by jginternational** [comment]
@rubenzorrilla  the hardest issue here is to find an appropriate image to distinguish between Body fitted and Embedded mesh

**Comment by rubenzorrilla** [comment]
Thanks a lot @jginternational. I'm going to try it to give you some feedback.

**Comment by jginternational** [comment]
There are 2 missing windows
1- Inlet intervals
2- Calculation data

**Comment by jginternational** [comment]
@rubenzorrilla Only missing the last page.

**Comment by rubenzorrilla** [comment]
@jginternational thanks a lot!

**Comment by jginternational** [comment]
![image](https://cloud.githubusercontent.com/assets/5918085/26054466/efa2247e-396c-11e7-8df9-23173c10679c.png)

We need to define the default values for this fields

**Comment by jginternational** [comment]
Missing apply mesh sizes

**Comment by rubenzorrilla** [comment]
I would keep mesh sizes as zero, meaning that if not set, the GiD defaults are used.

**Comment by jginternational** [comment]
I'm trying to recover this work. It is not easy because this branch modifies the Fluid and the Embedded applications.

I am going to try to modify it to keep everything involved in the wizard inside the Wind Tunnel Application, so no other app gets modified.

My idea is to create a Standalone product out of this

**Comment by jginternational** [comment]
Close since there's no more interest on this
