### ISSUE TITLE
[PfemFluid] error running examples

### ISSUE THREAD

**Issue by AFranci** [KratosMultiphysics/GiDInterface#650]
Hi @jginternational 

The assignation of node conditions has been changed and now it seems that the interface is not working.

This is the error that I get (also when I run the pre-packed example)

invalid command name ""
    while executing
"$domNode getAttribute $attributeName $defaultValue"
    (procedure "get_domnode_attribute" line 5)
    invoked from within
"get_domnode_attribute [$group find n Enabled_$i] v"
    (procedure "PfemFluid::write::getConditionsParametersDict" line 56)
    invoked from within
"PfemFluid::write::getConditionsParametersDict PFEMFLUID_NodalConditions "Nodal""
    (procedure "GetPFEM_ProcessList" line 4)
    invoked from within
"GetPFEM_ProcessList"
    (procedure "getNewParametersDict" line 19)
    invoked from within
"getNewParametersDict"
    (procedure "PfemFluid::write::writeParametersEvent" line 2)
    invoked from within
"PfemFluid::write::writeParametersEvent"
    ("eval" body line 1)
    invoked from within
"eval $wevent"

Furthermore, it appears the coordinate Z in the 2D case...

Is it possible to come back to the previous assignation way? Otherwise, can you fix it, please?

Thank you,

Alessandro

**Comment by jginternational** [comment]
No chance to go back. I'll fix it.

**Comment by AFranci** [comment]
OK @jginternational , please fix it back as soon as you can because now the PFEM interface is broken and cannot be used.
Thank you!

**Comment by jginternational** [comment]
Can you test it?

**Comment by AFranci** [comment]
Perfect! It's working!
..only a small change: in the 2D case it should not appear the Z-option in the boundary conditions.

Thank you!
