### ISSUE TITLE
Apps ready for the next release

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#661]
Regarding the [GiD interface agreement](https://github.com/orgs/KratosMultiphysics/teams/interface-committee/discussions/5)

### Apps currently ready:
- Fluid Dynamics
- Structural Mechanics
- FSI
- DEM
- Convection Diffusion
- Buoyancy
- Conjugate heat transfer
- Embedded Fluid
- Stenosis Wizard
- Stent
- Cohesive DEM
- Potential Flow
- Fluid DEM

### Apps not ready
- PFEM Fluid: Not in kratos release -Tetgen problems
- Solid: Examples not running KratosMultiphysics/Kratos/issues/5456
- PFEM: No example found
- PFEM DEM: Example not running. Writing errors #645  #629
- MPM: No example found

**Comment by jginternational** [comment]
Released 7.1.3-RC
https://github.com/KratosMultiphysics/GiDInterface/releases/tag/Release-7.1.3-RC

@KratosMultiphysics/all 

:) Bon Nadal!

**Comment by loumalouomega** [comment]
Why ContactStructuralMechanicsApplication is not ready?, i added for the release

**Comment by roigcarlo** [comment]
I don't think this is up to date. PfemFluid for example should not be there

**Comment by rubenzorrilla** [comment]
> Why ContactStructuralMechanicsApplication is not ready?, i added for the release

The ContactStructuralMechanicsApplication is included as part of the StructuralMechanicsApplication GUI, although there is no predefined example in the StructuralMechanicsApplication GUI testing the contact features...

**Comment by jginternational** [comment]
@loumalouomega  -> As @rubenzorrilla said, Contact is used by Structural, it does not have an app in the GUI
@roigcarlo -> Now it's up to date

**Comment by loumalouomega** [comment]
> 
> 
> > Why ContactStructuralMechanicsApplication is not ready?, i added for the release
> 
> The ContactStructuralMechanicsApplication is included as part of the StructuralMechanicsApplication GUI, although there is no predefined example in the StructuralMechanicsApplication GUI testing the contact features...

OK I tougth the list were the apps compiled

**Comment by rubenzorrilla** [comment]
@jginternational should we reuse this for the 8.1?

**Comment by jginternational** [comment]
Of course!
I'll update it soon
