### ISSUE TITLE
DEM-PFEM execution error

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#662]
This happends when running the example.

```
Traceback (most recent call last):
  File "MainKratos.py", line 40, in <module>
    Solution(model).Run()
  File "MainKratos.py", line 30, in __init__
    import swimming_DEM_PFEM_algorithm
ModuleNotFoundError: No module named 'swimming_DEM_PFEM_algorithm'
```

**Comment by jginternational** [comment]
ping @GuillermoCasas

**Comment by maceligueta** [comment]
I think it should say:
`import KratosMultiphysics.SwimmingDEMApplication.swimming_DEM_PFEM_algorithm as swimming_DEM_PFEM_algorithm`
However, maybe the algorithm is obsolete and we should be calling the analysis, like it is done in https://github.com/KratosMultiphysics/Kratos/blob/44c189b910a219f715b37b5e0aa5beb183de4642/applications/SwimmingDEMApplication/python_scripts/KratosSwimmingDEMPFEMAnalysis.py#L19
There the call is also wrong, I think it should be 
`from KratosMultiphysics.SwimmingDEMApplication.swimming_DEM_PFEM_analysis import SDEMPFEMAnalysis`

**Comment by maceligueta** [comment]
I guess @ipouplana and @jgonzalezusua will know this better.

**Comment by ipouplana** [comment]
Hi @jginternational , if you tried to run the pfem-dem examples (the ones inside Examples' repository) they are outdated right now... @jgonzalezusua and me will update the files there with the new input standard. 
If you want to see a test that is currently running you can look at the test in [https://github.com/KratosMultiphysics/Kratos/tree/master/applications/SwimmingDEMApplication/tests/PFEM-DEM_tests](url)

**Comment by ipouplana** [comment]
Here I opened a branch with the example updated: [https://github.com/KratosMultiphysics/Examples/tree/sdem/update-pfemdem-example/swimming_dem/use_cases/PFEMFluid_Element/One_Way/Small_Box_Lagrangian_OW/source](url)
I am compiling Kratos, but once it finishes, I will run the example to see if everything works and, if so, I will merge the branch into master

**Comment by ipouplana** [comment]
@jginternational I just updated the PFEM-DEM example here [https://github.com/KratosMultiphysics/Examples/pull/56](url)

**Comment by jginternational** [comment]
Answered in #645
