### ISSUE TITLE
mdpa file size: tabs vs spaces

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/GiDInterface#665]
I noticed that reading and rewriting an mdpa with Kratos reduces the file-size by ~25%
I checked, gid writes with spaces, while Kratos uses tabs

Without thinking abt it too much, would this be possible also in GiD to use tabs? For large models the difference can be in the GBs!

@KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
That's because a tab is \t and for spaces are literally the double of digits

**Comment by roigcarlo** [comment]
actually \t is just a single character, if they are using tab 4 they are using 4 times more :S

**Comment by jginternational** [comment]
Well, I can change most of them. 

I have in mind a new preference that allows users to switch between 'Optimized mdpa' vs 'readable mdpa'. The optimized will print the best to reduce memory and the readable will have tabs and spaces to fold/unfold in VSCode and have connectivities in columns.

**Comment by philbucher** [comment]
+1 for readable vs optimized
in fact I did exactly this in some of my toy-implementations

**Comment by rubenzorrilla** [comment]
> Well, I can change most of them.
> 
> I have in mind a new preference that allows users to switch between 'Optimized mdpa' vs 'readable mdpa'. The optimized will print the best to reduce memory and the readable will have tabs and spaces to fold/unfold in VSCode and have connectivities in columns.

Makes sense for me as well. Where will this preference be placed?

**Comment by jginternational** [comment]
@rubenzorrilla 

> > Well, I can change most of them.
> > I have in mind a new preference that allows users to switch between 'Optimized mdpa' vs 'readable mdpa'. The optimized will print the best to reduce memory and the readable will have tabs and spaces to fold/unfold in VSCode and have connectivities in columns.
> 
> Makes sense for me as well. Where will this preference be placed?

Check explanation in #667
