### ISSUE TITLE
[DEM-Fluid] Example not running

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#668]
In order to implement #645 I was trying to run the example of the Swimming Dem application but I couldn't run it.
[examplefluiddem.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/3816031/examplefluiddem.gid.zip)

```
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\DEMApplication\python_scripts\sphere_strategy.py", line 623, in ModifyProperties
    DiscontinuumConstitutiveLaw = globals().get(properties[DEM_DISCONTINUUM_CONSTITUTIVE_LAW_NAME])()
TypeError: 'NoneType' object is not callable
```

**Comment by farrufat-cimne** [comment]
I think the error is related to this:

Begin Properties 1
    DEM_DISCONTINUUM_CONSTITUTIVE_LAW_NAME Newtonian3DLaw
    DEM_CONTINUUM_CONSTITUTIVE_LAW_NAME DEMContinuumConstitutiveLaw
End Properties

Begin Properties 2
    DEM_DISCONTINUUM_CONSTITUTIVE_LAW_NAME DEM_D_Hertz_viscous_Coulomb
    PARTICLE_DENSITY 2500.0
    YOUNG_MODULUS 1000000.0
    POISSON_RATIO 0.20
    FRICTION 1.0
    COEFFICIENT_OF_RESTITUTION 0.2
    PARTICLE_MATERIAL 2
    ROLLING_FRICTION 0.01
    ROLLING_FRICTION_WITH_WALLS 0.01
    PARTICLE_SPHERICITY 1.0
    DEM_CONTINUUM_CONSTITUTIVE_LAW_NAME DEMContinuumConstitutiveLaw
End Properties

but properties 1 (with default law name?) is actually not being used or assigned to anything

i will give it a look. maybe something broke with recent updates or the example is not correctly constructed/assigned.

**Comment by jginternational** [comment]
I think I've got it.

Check this commit:
https://github.com/KratosMultiphysics/GiDInterface/commit/a4f6b6c34b3e98242eb6d1a6cbc7172d55756eb1
