### ISSUE TITLE
Kratos DEM application

### ISSUE THREAD

**Issue by Ali-RAFIEE** [KratosMultiphysics/GiDInterface#670]
Hi every one,
as a new user of Kratos, I search a simple user manual doc for starting to analysis the models for rock slope stability.
in fact, I look for a method for doing my models by python code, and run them by Kratos.
is there a way to do this via Gid, or not?
and how can find explanatory documents about how using Kratos via Gid.

Thanks a lot
Ali

**Comment by farrufat-cimne** [comment]
Hi @ali145 ,
Several tutorials can be found in:
http://kratos-wiki.cimne.upc.edu/index.php/DEMPack_Tutorials
and you can use the CohesiveDem module in GID (https://github.com/KratosMultiphysics/GiDInterface) or the GranularDem one if you do not actually require bonded particles.
Although the current interface is a bit newer, it is similar to the one defined in the tutorials.

**Comment by ali145** [comment]
Thanks Ferran for your reply,
is there a direct method for modeling with Kratos without using GID interface?
just by coding in python, and possibility to giving the input data without GID, and obtaining results in formats readable by software such Paraview?

I will be very grateful if you can share an example with direct method.

Thank you again
Ali

**Comment by farrufat-cimne** [comment]
As far as the input files follows the Kratos standards, there should be no problem. Our custom interface is convenient to write the required data files with minimum effort, but of course you can use any custom generated input file (geometrical data, properties, etc) that adjust to Kratos.

Furthermore, if you are familiar with python and the Kratos code you could even code directly all (or almost all) the required data in custom python functions, similar to the ones used in several benchmarks

As for the results being compatible with Paraview, I think there is a option to write the ouput in vtk format (although I haven't personally tested that feature).

**Comment by ali145** [comment]
That's good, Thanks a lot Ferran.
How can I find a simple example in python for Kratos, as I said I'm new user of Kratos, and as I saw Gid is not free software, I want use Kratos directly by python codes.

Best regards
Ali

**Comment by jginternational** [comment]
@ali145 you can use GiD for free if your mesh is less than 10.000 nodes

**Comment by ali145** [comment]
I know that I will exceed 10k nodes, so starting with free way is more better I think, of course if I can do something.
Thanks Javi.

**Comment by farrufat-cimne** [comment]
> That's good, Thanks a lot Ferran.
> How can I find a simple example in python for Kratos, as I said I'm new user of Kratos, and as I saw Gid is not free software, I want use Kratos directly by python codes.
> 
> Best regards
> Ali

For an insight of how to do it directly in python without using input files you can check: 
"applications/DEMApplication/python_scripts/time_step_testing_stage.py"
It is a simple example but you will get the idea. If your model is complex I wouldn't recommend this method.

**Comment by ali145** [comment]
I try the proposed example but I received this error message:
in fact, how can import "KratosMultiphysics.DEMApplication"?
I use Ubuntu 16.04. 
thanks
Ali


=====================================================
python3 time_step_testing_stage.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 7.0.0-b4d81f1-Release
Compiled with OpenMP support.
Maximum OpenMP threads: 8.
Traceback (most recent call last):
  File "time_step_testing_stage.py", line 2, in <module>
    from KratosMultiphysics.DEMApplication import *
ImportError: No module named 'KratosMultiphysics.DEMApplication'
========================================================

**Comment by jginternational** [comment]
@ali145 

Make sure that your cmake_build/configure.bat file has activated the line to compile the DEM module:
`-DDEM_APPLICATION=ON `

**Comment by ali145** [comment]
Thanks Javi and Ferran,
it's OK now, and I can run this example.

but in fact I search an explanatory example in which I can have the input geometry for example via stl format files or similar way, and I can adjust other parameters including material characteristics, contact conditions, boundary conditions, and output result file format (vtk) with python code.

and for that I have not found an example yet.

I thank you in advance for your help and I hope to start using Kratos via a simple example that I am looking for.

best regards
Ali

**Comment by jginternational** [comment]
I close this issue to clean up. If you still have questions to the DEM team, please create a new one and mention them! Thanks!
