### ISSUE TITLE
[dem] Custom submodelpart not printing anything

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/GiDInterface#677]
I just created an example with the standard DEM and tried to create a custom submodelpart with with one sphere, destination DEM mdpa. Nothing was printed there.
@farrufat-cimne 
Referencing also @jginternational in case you have time to look at it, too.

**Comment by jginternational** [comment]
It is commented here:

https://github.com/KratosMultiphysics/GiDInterface/blob/afe26b84e089b90f770e2e71185eb9e597e431e7/kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl#L33
