### ISSUE TITLE
[dem] Dem Parts in 2D allow assigning to Volumes, when they should not

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/GiDInterface#690]
This is general, but should be different in 2D/3D
https://github.com/KratosMultiphysics/GiDInterface/blob/a1d5208333049fdacb6369f6e1bcb3885ff5cb76/kratos.gid/apps/DEM/xml/Parts.spd#L3

**Comment by jginternational** [comment]
You'll need something like this:
```xml
 <condition n="Parts" pn="Parts" ov="[GetDEMPartsOv]" ovm="node,element" icon="shells16" help="Select your group" un="DEMParts"> 
```

and, in the procs.spd file, implement the function that returns "point,line,surface" in 2d and "point,line,surface,volume" in 3D

**Comment by maceligueta** [comment]
thanks! It is working. Will start a new PR for it.

**Comment by jginternational** [comment]
If you want it to be included in the release, be fast. In 1 hour it'll be out of the oven!

**Comment by maceligueta** [comment]
Well, several other bugs will be packed then. We spent the day reporting bugs related to DEM
