### ISSUE TITLE
[dem] CDEM 2D condition DEM-FEM-Wall shows three values for all vector fields

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/GiDInterface#692]
The DEM 2D version is doing this more or less right, but CDEM is not aware of the change in dimensions.

**Comment by farrufat-cimne** [comment]
I just created CDEM 2D example with wall condition and only 2 components in vector fields are shown.
Also tested in standard DEM 2D

**Comment by maceligueta** [comment]
True, I must have made a mistake beforehand.
