### ISSUE TITLE
FSI examples are broken

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#7]
The 2d and 3d FSI examples are broken.
The recent changes in the fluid application may have broken the scripts

**Comment by jginternational** [comment]
@rubenzorrilla I think this fixes the problems with the Automatic time step

**Comment by jginternational** [comment]
@rubenzorrilla MOK example is working, the next step is to check the default parameters

**Comment by rubenzorrilla** [comment]
Thanks @jginternational. I will have a look at it ASAP.

**Comment by jginternational** [comment]
3D Mesh sizes were not good. Before my last commit, 2D mesh information was applied to 3D body

**Comment by rubenzorrilla** [comment]
@jginternational  my bad! I will have a look to the 3D case ASAP.
