### ISSUE TITLE
[DEM] Quad mesh

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/GiDInterface#724]
Hi, I am using the latest master branch of this interface and cannot assign quad meshes to DEM-FEM walls anymore. 

`asd assigned to DEM-FEM-Wall - Selected invalid entity surface with 4 nodes - Check Conditions.xml
`

that is the error msg I get when I want to run the problem. Maybe I am doing sth. wrong but I dont think so.
[casd.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/4244592/casd.gid.zip)

**Comment by maceligueta** [comment]
Hi @KlausBSautter . The 4-noded walls are not supported, actually, by the DEM Team. As far as I know, they used to work for limited simple cases, but clearly they are incompatible with certain features, and they have always been.
This does not mean that a developer can’t use it. But it’s better not to add them to the GUI if they do not work in general.
If they are a priority we can start making the code compatible with them sooner than planned.

**Comment by KlausBSautter** [comment]
@maceligueta thanks for the answer! Makes sense, I'll use triangles
