### ISSUE TITLE
Generate Mesh after problem type selection (GiD 14.1.8d)

### ISSUE THREAD

**Issue by frawahl** [KratosMultiphysics/GiDInterface#741]
Error message appears instead of mesh when problem type already was selected:
"No Mesh generated. No geometry present, not correct entities or no entity selected to be meshed"

I recreated the problem by: opening GiD, creating Geometry > Object > Rectangle, selecting a problem type (kratos Structural 3D), hitting Ctl+G.
The same problem appears when the rectangle is created after selecting the problem type.

![gid_mesh_problem](https://user-images.githubusercontent.com/49983547/81567680-ebe42480-939c-11ea-9f97-d40ee9786e2c.png)

**Comment by frawahl** [comment]
Also, there seems to be no going back. Once problem type kratos was selected for the geometry, it won't mesh even after switching to another problem type or unloading the problem type. 
Switching/ unloading the problem type, deleting the old geometry, creating a completely new one and meshing does work.

**Comment by rubenzorrilla** [comment]
I guess that the problem is that you haven't created and assigned any group entity to the `Parts` section of the tree.

The problem type only meshes those entities assigned to groups.

**Comment by frawahl** [comment]
Yes, assigning group entities was the solution. The error message also makes sense to me now. Thanks!
