### ISSUE TITLE
[Structural] Self-weight

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/GiDInterface#753]
Hi, I cannot apply self-weight anymore using the GID Interface. I tried it on the PCs of my peers and get the same error an all machines. I do not think I did sth. wrong as the process is straightforward. Nevertheless, I added the problem (really simple):

[test_membrane.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/5160832/test_membrane.gid.zip)

With a self-weight condition I get the following msg:

`Problem Writing MDPA block:
invalid command name ""
End problems
`

Without it everything is fine.

Cheers

**Comment by KlausBSautter** [comment]
It works in the latest release 7.1.5, but apparently not in the latest devel. version

**Comment by jginternational** [comment]
I'll take a look. I also broke something in the VTK json yesterday
