### ISSUE TITLE
GiD, PFEM postprocess crashes

### ISSUE THREAD

**Issue by Mariveros** [KratosMultiphysics/GiDInterface#761]
Hello, I'm working with the PFEM module for tailing modeling using a basic model as follow:
- a "box" of fluid, with its properties using bingham material (aprox)
- and a frame for the run-out of fluid
Dimensions aprox. (height_total = 75m (frame), fluid_height = 15m , length_total = 450m , fluid_length = 50m)

when I run some example with a mesh size of 1,075,05,04 m everything works well even if I use a specific mesh for the border (general mesh 0.5 and border 0.1 or similar). However when I use a general mesh of 0.30 or 0.25 (cases that I already run) when GiD ends the process and click "Ok or "Postprocess", GiD closes itself then if I re-open it and click for the same project "Postprocess" it starting to compile file til some % (ex. 70.4%) and then stop and closes itself without showing any error.

is the first time that I had some errors in that way.

Info---

GiD - Version 14.1.10d
Processor : Intel Core i7-9750H @ 2.6GHz
Graphics: GeForce GTX 1650 Mobile  Max -Q
Ram: 16 Gib, DDR4 2400MHz
Storage : 100Gb (for linux)
OS: Linux

I'm glad if you can give me some reasons or something to set to avoid this "error". Thank you.

**Comment by Mariveros** [comment]
update comment-----

I trying to figure out about this problem and I found that is related to my "process capacity (Hardware)" or maybe the settings by itself.

I use the post-process option and open a few files (.bin) of post-process and it was opened well. So the problem as I said would be the settings or processing capacity if someone can give me some advice or suggestions about it.

**Comment by jginternational** [comment]
Hi @Mariveros ,

Could you attach here a zip with the example you are using?

**Comment by Mariveros** [comment]
Hi, are you talking about post-process info generated by GiD ( the number of files and mesh)? , I'll try to attach the file here, it had some weight.

I'll update you here. thanks

**Comment by jginternational** [comment]
Hi, the folder called 'name.gid'. If you can compress it and send it through here, or via weetransfer

**Comment by Mariveros** [comment]
I had to separate the .gid folder due to its size ( +2gb) I create 2 .zip files with the content of .gid folder p1 and p2 here is the content.
[part1](https://we.tl/t-7fzwm17mAA)
[part2](https://we.tl/t-IcQ4drdNqg)

**Comment by jginternational** [comment]
Hi @Mariveros 

I've tested it in my Windows with 24 GB of RAM and worked fine, GiD and the model are OK.
So why are you experiencing this issue? I've created a virtual machine with 16GB of RAM and this is what I see when changing to post process:
![image](https://user-images.githubusercontent.com/5918085/95354247-7ab18a80-08c4-11eb-821e-784b1291107d.png)

As you can see, when result files are being load, memory reaches 100%. As I have no swap space available, the whole OS stops.

I recommend you to use a PC with more RAM memory, or the cheapest and smart way: add some swap space:
- You can create a swap file, so you can use it only now, and erase it after your post process is closed
https://linuxize.com/post/create-a-linux-swap-file/

Following that manual, I've created the swap file and loaded successfully the postprocess files:
![image](https://user-images.githubusercontent.com/5918085/95356496-04625780-08c7-11eb-9a70-6728555a9618.png)

The missing memory is taken from the swap

**Comment by Mariveros** [comment]
Ok, I'll try it and give you some feedback about it.

Thank you!

**Comment by Mariveros** [comment]
The solution works. 

Problem: Run out  Memory.
The solution posted above.

Thank you!
