### ISSUE TITLE
Bug in FluidDEM interface

### ISSUE THREAD

**Issue by GuillermoCasas** [KratosMultiphysics/GiDInterface#763]
**Description**
When going through the problemtype tree, an error pops up when I try to select a part for the DEM elements.

**Scope**
Where in GiDInterface is this bug happening
- In the FluidDEM sub-interface of the DEM one.

**To Reproduce**
Simply double-click the 'Define particle groups' entry in the DEM tree before doing anything else:

Expected behavior**
No error message should appear. Also, this behaviour does not allow me to input a DEM mass, so it is a serious issue.

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: Ubuntu 16.04
- Branch: master
- GiD15.01, also GiD14.1.10D

Error log:
[error_interface.log](https://github.com/KratosMultiphysics/GiDInterface/files/5397750/error_interface.log)

**Comment by jgonzalezusua** [comment]
It is fixed in branch _update-fluiddem-interface_, I will see if I can solve it in master

**Comment by GuillermoCasas** [comment]
Ok, please do a PR of that branch, since the master one is useless

**Comment by jgonzalezusua** [comment]
Ok, the PR is already done #764

**Comment by jgonzalezusua** [comment]
I will close this issue since it is solved after the PR
