### ISSUE TITLE
[FSI] SingleMass on Point/Node

### ISSUE THREAD

**Issue by SamiBidier** [KratosMultiphysics/GiDInterface#765]
Hello,
I was wondering if there is a possibility to apply a single mass on a point/node in analogy to the point load functionality?
Thanks in advance,
Sami

**Comment by rubenzorrilla** [comment]
Hi @SamiBidier !

The mass element is not exported to the GUI yet (@KratosMultiphysics/structural-mechanics). In any case there is an ongoing discussion (see #7629) about the addition of the nodal spring element to the GiD GUI. From the GUI perspective, the mass element should be exactly the same. Hopefully, it will be available soon.

In any case you can modify your structure .mdpa manually to add a new `NodalConcentratedElement`. Should be something like
```
Begin Elements NodalConcentratedElement3D1N
1 2 3
End Elements
```
where 1 is the new element id, 2 the properties id and 3 the corresponding nodal id.

**Comment by SamiBidier** [comment]
Hi @rubenzorrilla ,
thanks again for the help. 
Sami
