### ISSUE TITLE
[All] Update Kratos version in the internet retrieve

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/GiDInterface#766]
The one we have right now is way old. We should upload a new one.

**Comment by jginternational** [comment]
I've been testing the current Gui and the last release of the compiled repo (https://github.com/KratosMultiphysics/Kratos/releases/tag/v8.0.1) and they are not fully compatible. I'll need to make a great effort to move some gui code back in time to match that version, and that's a job I'll hate to do

@roigcarlo As Gui and the current master branch are more or less up to date (The things in the Gui work fine. There are missing features but most of the features work) I suggest to wait for the next kratos release to generate a package

**Comment by roigcarlo** [comment]
I will have to make a release by the end of november no matter what, so we can schedule the releases for the week of the 23 if its ok.

**Comment by rubenzorrilla** [comment]
I don't think there is a problem in doing it by the 23th of November.

**Comment by jginternational** [comment]
Done
