### ISSUE TITLE
Getting a surface model part on the .mdpa file.

### ISSUE THREAD

**Issue by SADPR** [KratosMultiphysics/GiDInterface#768]
I am using the GiD interface (Kratos problem type) to create the .json and .mdpa files from a structural 3D model.
My model is made up of a solid model part (with assigned material) and two surface model parts. I would like to know if there is a way to generate the .mdpa file with the information from my two surface model parts without applying a boundary condition.

**Comment by jginternational** [comment]
Hi Sebastian,

You can write the information of geometries with no conditions on them.
Open the Kratos preferences (Up menu > Kratos > Preferences) and set Mode: Developer

You'll see this icon on the tree:
![image](https://user-images.githubusercontent.com/5918085/98556688-9af9ae00-22a3-11eb-8251-1941307510b9.png)
 you can apply that to your surfaces and select what do you want to print on them, nodes, elements and/or conditions

**Comment by jginternational** [comment]
Is this issue done @SADPR ?

**Comment by SADPR** [comment]
Yes, I am sorry I forgot to respond and close it. Thanks a lot.
