### ISSUE TITLE
Problem with FEMtoDEM mesher

### ISSUE THREAD

**Issue by jgonzalezusua** [KratosMultiphysics/GiDInterface#770]
The mesher does not work properly if you assign an element size to the volume in which the mesher has to transform the nodes of the FEM fashion in DEM. 

I have a case which consists in a cylinder with a sphere inside. This sphere represents a bunch of DEM particles. The problem is that even if I reduce the element size assigned to the sphere, I obtain always the same quantity of particles. It seems like the FEMtoDEM mesher only takes into account the size of the mesh selected for the entire model. This would be a problem if you have different DEM volumes and you want assign different sizes to each of them.

**Comment by maceligueta** [comment]
Thanks for reporting, @jgonzalezusua . We will take care of this.

**Comment by jginternational** [comment]
Hi @jgonzalezusua and @maceligueta 
This is the current behaviour: I've created the figure described. 
Parameters:
- GiD mesh size: size of the mesh elements of the geometrical sphere. Assigned via GiD mesh menu
- FEMtoDEM diameter: Assigned in the tree, defines the size of the mesh spheres

GiD mesh size: 1.0
FEMtoDEM diameter: 0.3
![m1-sphm-03](https://user-images.githubusercontent.com/5918085/99075442-c9380000-25b9-11eb-8b5a-db5bf9a1af7c.PNG)


GiD mesh size: 1.0
FEMtoDEM diameter: 0.1
![m1-sphm-01](https://user-images.githubusercontent.com/5918085/99075496-df45c080-25b9-11eb-9d42-74a256a96329.PNG)


GiD mesh size: 0.5
FEMtoDEM diameter: 0.1
![image](https://user-images.githubusercontent.com/5918085/99075603-09977e00-25ba-11eb-8868-2a9b9bb697b7.png)

**Conclusion**:
To increase the number of spheres in the mesh, you need to decrease the GiD mesh size, (Menu Mesh > Unstructured > Assign sizes on volumes > (set a size and select the geometric sphere)

**Comment by maceligueta** [comment]
Exactly, the separation between particles is governed by the GiD mesh size, not the size in the tree.

**Comment by jgonzalezusua** [comment]
I already fix the size in the tree, no issues with that. The problem is when I assign an element size to the volume I want to transform. 

If I assign, for example, an element size h=0.003 to the volume (which is a sphere), I obtain, we say, 200 particles and this number keep constant even if I reduce h to 0.001. But if I reduce the element size for the entire model, GiD provides me more particles, which makes sense. 

So my conclusion is that FEMtoDEM only takes into account the size of the mesh for the entire model and not for the size assigned to the sphere. I think this should be modify to customize better the FEMtoDEM mesher.

**Comment by maceligueta** [comment]
If you try these different mesh sizes of a sphere, but that sphere is not set as DEM in the tree, it should be meshed as tetrahedra. Does it happen the same way then? You should have the same problem, as from the ProblemType we are only converting nodes of a FEM mesh into spheres...

**Comment by jgonzalezusua** [comment]
Thanks @maceligueta, it is solved.
