### ISSUE TITLE
[DAM] Normal Load is broken

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#785]
I've disabled Normal Load (LinePressure2D and SurfacePressure3D) since it's process is implemented in Solid application.
Maybe you need to change it's process to ApplyLoadVectorDamTableProcess or another.

Please @KratosMultiphysics/dam 
Check it! 5d9f96c4b35e15fbe56f5ab87805715093acb4e2

**Comment by joaquinirazabal** [comment]
Thanks for pointing it out @jginternational. I think that we are not using these processes anymore, am I right @djvicente? @jginternational, If @djvicente confirms it you can remove those conditions from the interface.

**Comment by djvicente** [comment]
Thanks, @jginternational. As @joaquinirazabal says, we no longer use these processes as they are rarely applied in real practice. Perhaps in the future, we will be able to recover them for academic purposes, but at the moment they may be disabled.
Thank you!
