### ISSUE TITLE
Generic submodelpart from group

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#79]
As said in https://github.com/KratosMultiphysics/Kratos/issues/278

There is a proposal that needs a  `<condition>` to write a Group as submodelpart.
something like:
```json
<condition n="GenericModelParts" pn="Add SubModelPart" un="ExtraModelParts" ov="point,line,surface,volume" state="[ShowInMode Developer]">
    <value n="WriteElements" pn="Write elements" v="False" values="True,False"/>
    <value n="WriteConditions" pn="Write conditions" v="True" values="True,False"/>
</condition>
```
The result is:
![image](https://cloud.githubusercontent.com/assets/5918085/24953516/e58dd5d8-1f7b-11e7-80ef-b9b5a8d30bb5.png)
**Note:** It's important to select the entity type even if the group was previously created

We'll need to modify the writing process, to add this new feature

**Comment by adityaghantasala** [comment]
Hello @jginternational  ... I have a question regarding the usage of this problem type. I downloaded this branch and had a look at it. I saw that the generic submodelpart from group works for Structural as mentioned. 

Is it also possible to do it for a fluid problem (2D and 3D) ?? If not is there a plan to do that ?

**Comment by jginternational** [comment]
The idea is to have it in all apps (in development mode) soon

**Comment by adityaghantasala** [comment]
@jginternational  that would be awesome .. thank you!
