### ISSUE TITLE
stuck reading post-process

### ISSUE THREAD

**Issue by Mariveros** [KratosMultiphysics/GiDInterface#795]
Hi everyone,

I create a model on PFEM modulus inside GiD 14.1.10d on Linux (Ubuntu 20.), everything is ok until I try to read files created using the post-process tab. it reads all files but when it reaches 99% stuck at processing and cannot continue...

I create a similar model but just with 1 (s) of total time. and it can be read correctly.

It cannot be a problem of memory I suppose. I had assigned more than 60 Gb of memory (internal).

I'll attach the file here. [File](https://wetransfer.com/downloads/63f11a35665df6909a64f8e9b829fb4a20210123195708/eaca5097faf1546b1a15e1895d5ac5f320210123195713/0eb840)

There is no warning of error message just stuck at 99 %.

I'll wait for your suggestions.

Thank you.

Marcelo

**Comment by RiccardoRossi** [comment]
forwarding at @maceligueta @AFranci

**Comment by maceligueta** [comment]
@RiccardoRossi and @rubenzorrilla : I am not a maintainer, nor a developer, of the PFEM in Kratos. @AFranci is managing it.

**Comment by rubenzorrilla** [comment]
> @RiccardoRossi and @rubenzorrilla : I am not a maintainer, nor a developer, of the PFEM in Kratos. @AFranci is managing it.

Sorry, I though you were still involved on it.

**Comment by AFranci** [comment]
Hi Marcelo,

I tried to open the post-process results that you sent us and if you open all of them, as you said, the GiD seems to remain stuck. Nevertheless, after a while, he finished the process and I could regularly see the results. 

This is because there are a lot of output files (5000).

If you open fewer output files you will have not to wait so long. 

Note that you can also reduce the number of outputs by giving a lower writing frequency in the input GiD interface or ProjectParameters.json (either increasing the delta time interval or the time step between two following output steps).

Regards,

Alessandro

**Comment by Mariveros** [comment]
Hi everyone,


Alessandro, thanks for your reply. As you said if the file opened after a while so it's due to the number of outputs created for such a problem. I'll try to reduce the number of outputs.

I'll review and if it works I'm going to repost and close this thread.

Regards,


Marcelo

**Comment by jginternational** [comment]
@pasenau FYI

**Comment by Mariveros** [comment]
after a while, the file was opened.

Thanks to everyone.

**Comment by pasenau** [comment]
hi,
i tested your example and found the problem. GiD takes long time to gather the information from these files. This needs to be improved, but at the end ( around 40 minutes in debug mode) the results can be viewed. As said, i found the problem and i'm working on it.

**Comment by Mariveros** [comment]
Hi @pasenau.

For your information, I tested a similar simulation a few months ago (same version of GiD 14.1.10d) version and this problem does not exist. If I take those models created before it opens (without modifying or update, the system suggests an update of archives) immediately after 100% is reached but for the newer the excessive time to process it appears.

info: different computers the last one with better (+ RAM and CPU).
