### ISSUE TITLE
How to cite GiD?

### ISSUE THREAD

**Issue by riccardotosi** [KratosMultiphysics/GiDInterface#796]
Good afternoon,

I would like to cite GiD in a work I am doing. Specifically, I am using GiD in combination with Kratos. I see that [in the GiD web page](https://www.gidhome.com/support/brand-resources/citing-gid/) there are four different citation possibilities, but none seem to refer to the software. They only refer to manuals.

Should I use all of them? Only one? A different one?

Thanks.

**Comment by jginternational** [comment]
@escolano @pasenau

**Comment by escolano** [comment]
Hi Riccardo,
thanks for your interest.
I think that you must cite only the ones you consider relevant for your work (e.g. the customization manual, and/or the reference manual, and for the GiD software itself can cite the webpage)

**Comment by riccardotosi** [comment]
Thanks.

**Comment by loumalouomega** [comment]
Just the following: 

https://www.gidhome.com/support/brand-resources/citing-gid/

PS: I used this in my PhD

**Comment by riccardotosi** [comment]
> 
> 
> Just the following:
> 
> https://www.gidhome.com/support/brand-resources/citing-gid/
> 
> PS: I used this in my PhD

Thanks Vicente.

However, this link is what I posted in the question. My question was which of these 4 references should I use.

**Comment by loumalouomega** [comment]
> > Just the following:
> > [gidhome.com/support/brand-resources/citing-gid](https://www.gidhome.com/support/brand-resources/citing-gid/)
> > PS: I used this in my PhD
> 
> Thanks Vicente.
> 
> However, this link is what I posted in the question. My question was which of these 4 references should I use.

Sorry, particularly I referenced the reference manual.
