### ISSUE TITLE
Create an example for Fluid Dynamics app

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#8]
The main idea is to find some examples to be implemented in the Fluid 2D and 3D app

Examples: 
- https://www.comsol.com/models/cfd-module

**Comment by rubenzorrilla** [comment]
The simpler the better (at least at this point). Thus, we could create the 2D and 3D cylinder examples.

**Comment by jginternational** [comment]
[DOC.pdf](https://github.com/KratosMultiphysics/GiDInterface/files/895647/DOC.pdf)

**Comment by jginternational** [comment]
@rubenzorrilla We need to calibrate the mesh sizes in 2D and 3D, and this is done
