### ISSUE TITLE
Error when loading kratos.gid

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/GiDInterface#802]
**It is error when I loading kratos.gid from GID14.1.9d.**
**Error (l693):** invalid command name "gid_groups_conds::close_all_windows"
STACK:
invalid command name "gid_groups_conds::close_all_windows"
    while executing
"gid_groups_conds::close_all_windows"
    (procedure "Kratos::DestroyWindows" line 2)
    invoked from within
"Kratos::DestroyWindows"
    (procedure "Kratos::Event_EndProblemtype" line 16)
    invoked from within
"$proc {*}$args"
    (procedure "RaiseEvent_Registered" line 4)
    invoked from within
"RaiseEvent_Registered GiD_Event_EndProblemtype"

Error (l671): invalid command name "CreateWidgetsFromXml::ClearCachePreferences"
STACK:
invalid command name "CreateWidgetsFromXml::ClearCachePreferences"
    while executing
"CreateWidgetsFromXml::ClearCachePreferences"
    (procedure "Kratos::RegisterGiDEvents" line 38)
    invoked from within
"Kratos::RegisterGiDEvents"
    (procedure "Kratos::Events" line 10)
    invoked from within
"Kratos::Events"
    (procedure "Kratos::Event_InitProblemtype" line 14)
    invoked from within
"Kratos::Event_InitProblemtype $dir"
    (procedure "::GiD_Event_InitProblemtype" line 2)
    invoked from within
"::GiD_Event_InitProblemtype {C:/Program Files/GiD/GiD 14.1.9d/problemtypes/kratos.gid}"

**Comment by jginternational** [comment]
Dear @ZhimingGuo 
Thanks for reporting. A hotfix has been merged into the master branch in order to fix this bug.
Could you please try it?
Update your code to the master 
```
git checkout master
git pull -p
```

**Comment by ZhimingGuo** [comment]
It is good to work, thanks!
