### ISSUE TITLE
Solid - Write degrees of freedom on ProjectParameters.json

### ISSUE THREAD

**Issue by lluis-mv** [KratosMultiphysics/GiDInterface#81]
Hi,
I'm experiencing problems in writing the type of degrees of freedom in Solid Mechanics Application and Pfem Application interfaces. In these applications there are several types of elements; in all of them the displacements are the degrees of freedom and in some of them extra degrees of freedom are used (e.g.  pressure in mixed formulations). In the xml of these elements they have the filter filed "HybridType" to filter the constitutive equations, since different constitutive laws are used for each element type. In previous problem types we used to write something like:
     "pressure_dofs"                      : true,
in the solver_settings part of the ProjectParameters.json so the degrees of freedom at each node could be added in the appropiate python file.
How can this filter used in the element xml (HybridType) be retrieved in the writting process of the json file?
Thanks

**Comment by josep-m-carbonell** [comment]
:+1:   I agree with Lluís, some field is needed to set if the elements formulation is mixed or hybrid and if it is an structural element, the real dofs for the problem are needed as an input parameter. The object that knows that dofs is the element.

**Comment by jginternational** [comment]
We are going to add to the elements in Elements.xml a field like:

`Dofs="DISPLACEMENT,ROTATION"`

And it is going to be written in the json as a list

**Comment by jginternational** [comment]
@josep-m-carbonell I've added the functionality, but I dont know which elements need to have this dofs
