### ISSUE TITLE
[Fluid/ConvDiff] Conjugate Heat Transfer Application

### ISSUE THREAD

**Issue by sunethwarna** [KratosMultiphysics/GiDInterface#811]
Hi, I was checking one of the examples from Thermic [ ConjugateHeatTransfer/CylinderCooling2D ] and i found that if I change the mesh units to cm, it writes the fluid mdpa in cm, but the solid mdpa is in m which gives non-cnverging results. This is true for one of my cases as well. At the moment, I am writing the mdpa in m and changing the mdpa file to cm to avoid this problem. But it would be nicer if this can be fixed from GiD side.

I am using the following versions:
Gid version: 15.0
Kratos version: 8.1.0

**Comment by jginternational** [comment]
Thanks for reporting @sunethwarna 
I'll take a look
