### ISSUE TITLE
[PfemFluid] Error with the new changes

### ISSUE THREAD

**Issue by AFranci** [KratosMultiphysics/GiDInterface#812]
Hi @jginternational 

I have just updated the interface and I am having an error trying to use the PfemFluid interface. Can you take a look at it, please?

This is the error I get

![Screenshot from 2021-06-03 09-38-42](https://user-images.githubusercontent.com/25818902/120606832-e3e79e80-c44f-11eb-899f-3b33d3f0c6ed.png)

thankd

**Comment by AlejandroCornejo** [comment]
Must be something related to the latest DEM changes??

**Comment by jginternational** [comment]
It was a problem with the conflict resolution.

Is it fixed now?

**Comment by AFranci** [comment]
yes, thanks!
do you confirm it @AlejandroCornejo?
