### ISSUE TITLE
[FluidDEM] Problem with FluidDEM::write::writeParametersEvent 

### ISSUE THREAD

**Issue by jgonzalezusua** [KratosMultiphysics/GiDInterface#819]
Hi @jginternational,

I am writing to you because I am getting an error when I try to write the ProjectParameters.json of a case from the FluidDEM application. I am on the last version of the master of the GiDInterface. The error is the following:

```
Problem Writing MDPA block:
key "properties" not known in dictionary
End problems
Problem Writing Project Parameters block:
key "hydrodynamic_law" not known in dictionary
Event FluidDEM::write::writeParametersEvent 
End problems
```

It looks like it does not find the hydrodynamic_law even though I have defined it in the problem type. Could you help me?

**Comment by jginternational** [comment]
Try with this branch
https://github.com/KratosMultiphysics/GiDInterface/pull/818
@jgonzalezusua

**Comment by jgonzalezusua** [comment]
Hi @jginternational,

I am still getting an error:

```
Problem Writing Custom file block:
NodeTest: Expected "WCARDNAME" for '' 
Event FluidDEM::write::writeCustomFilesEvent 
End problems
```

I do not know what is it

**Comment by jginternational** [comment]
Can you attach a zip with the model? (no mesh is required)

**Comment by jgonzalezusua** [comment]
Find it attached in this message. I have found that the error shown above appears when I click in 'Material relations' button:

```
NodeTest: Expected "WCARDNAME" for '' 
NodeTest: Expected "WCARDNAME" for '' 
    while executing
"[customlib::GetBaseRoot] selectNodes [spdAux::getRoute DEMROOT]"
    (procedure "DEM::write::GetDEMUsedMaterialsNodeList" line 5)
    invoked from within
"DEM::write::GetDEMUsedMaterialsNodeList"
    (procedure "GetMaterialRelationsTable" line 5)
    invoked from within
"GetMaterialRelationsTable"
    (procedure "DEM::xml::ShowMaterialRelationWindow" line 3)
    invoked from within
"DEM::xml::ShowMaterialRelationWindow"
    invoked from within
".gid.bitmapsKPreprocessModelbar.8 invoke "
    invoked from within
".gid.bitmapsKPreprocessModelbar.8 instate !disabled { .gid.bitmapsKPreprocessModelbar.8 invoke } "
    invoked from within
".gid.bitmapsKPreprocessModelbar.8 instate pressed { .gid.bitmapsKPreprocessModelbar.8 state !pressed; .gid.bitmapsKPreprocessModelbar.8 instate !disab..."
    (command bound to event)
```

[Periodic_bounding_box.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/6808303/Periodic_bounding_box.gid.zip)

**Comment by jginternational** [comment]
You will need to ->
Create a new case, select fluid DEM
Import GiD model (Files > Import > Import GiD Model)
Reattach the existing groups to the tree conditions (Fluid parts, inlet, outlet...)

This branch breaks the backward compatibility

**Comment by jgonzalezusua** [comment]
I will close this issue
