### ISSUE TITLE
[Kratos][CFD] Problemtype 8.1 with GID 15.0.3

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/GiDInterface#821]
In one model I can have a group only containing volumes and have added to this:

conditions -> custom velocity constraints
results -> gid output -> drag results

For another, very similar model it only allows me the use a group containing only surfaces.

**Comment by jginternational** [comment]
I will need more information in order to reproduce this. Could you attach a zip with the model?

**Comment by mpentek** [comment]
This is a model which has such issues: https://syncandshare.lrz.de/dl/fi3X57FgcR9BWDcaYEpfqH13/Gbeb.gid

**Comment by mpentek** [comment]
Apart from this seeming to be a bug, similar technical issues I see when trying to add a model part to the drag results (git output).

Mind you, for me these only represent a temporary workaround anyway, as in the end I need a model part (or better said nodes list) which only contains nodes such that I can have some specific conditions on these. 

Still, having groups containing only volumes should, in my opinion, be able to be added either to the custom velocity constraints or grad results.

Ideally, we would have this working from the developer/advanced version of the Kratos problemtype, which already permits AddSubmodelPart, but only with option write elements and/or conditions. Maybe it is the easiest to add here the option nodes.

**Comment by jginternational** [comment]
In Fluid 3D application, the condition 'Custom Velocity Constraints' is restricted to surfaces.
I can change that, and let users pick between points, lines, surfaces, and volumes. Theres only 1 rule. Mix is not allowed, a condition -  group relation will print only 1 type of element. If you assign this velocity on this group for surfaces, it will only print the linear mesh elements, even if the group contains also tetraedra.

In addition, when you create a SubModelPart in dev mode using the Add SubModelPart tool, you can pick 'write elements' or 'write conditions' but nodes are always written, even if elements and conditions are unchecked

**Comment by mpentek** [comment]
I think that the Cusomt Velocity Constraints should not be restricted to surfaces. I agree with the rule that the mixing of entities should not be allowed. Let me know if I can test it.

**Comment by rubenzorrilla** [comment]
Just mentioning that I agree with @mpentek 's observations:
1. Custom velocity constraints shouldn't be restricted to surfaces (indeed a potential use case of this, which is to fix corners in 2D and edges in 3D to avoid the spurious slip velocities, could be handled by changing it to allow lower entities).
2. The add submodelpart should be capable to only write nodes. As far as I understand, if you deactivate the write conditions and write elements options it only writes the nodes. @jginternational  am I wrong?

**Comment by mpentek** [comment]
> Just mentioning that I agree with @mpentek 's observations:
> 
> 1. Custom velocity constraints shouldn't be restricted to surfaces (indeed a potential use case of this, which is to fix corners in 2D and edges in 3D to avoid the spurious slip velocities, could be handled by changing it to allow lower entities).
> 2. The add submodelpart should be capable to only write nodes. As far as I understand, if you deactivate the write conditions and write elements options it only writes the nodes. @jginternational  am I wrong?

I have not tried using the add submodel part without having either conditions or elements selected. @jginternational could you clarify the intended use is this case? It would be great to have a warning (or some text) that nodes will be anyway created.

**Comment by jginternational** [comment]
Yes, the base of the custom submodelparts are the nodes, and you can add the Conditions and/or the Elements.
About displaying warnings, there are not many places to display them.

**Comment by rubenzorrilla** [comment]
> Yes, the base of the custom submodelparts are the nodes, and you can add the Conditions and/or the Elements.
> About displaying warnings, there are not many places to display them.

@jginternational is technically possible to add another `Write nodes` option that iis not modifiable by the user? This would be sufficient to indicate that nodes are always written.

**Comment by mpentek** [comment]
> > Yes, the base of the custom submodelparts are the nodes, and you can add the Conditions and/or the Elements.
> > About displaying warnings, there are not many places to display them.
> 
> @jginternational is technically possible to add another `Write nodes` option that iis not modifiable by the user? This would be sufficient to indicate that nodes are always written.

Maybe with the box for write nodes ticked by default and without the possibility of changing?

**Comment by jginternational** [comment]
That's easy! I'll add a PR

**Comment by rubenzorrilla** [comment]
> > > Yes, the base of the custom submodelparts are the nodes, and you can add the Conditions and/or the Elements.
> > > About displaying warnings, there are not many places to display them.
> > 
> > 
> > @jginternational is technically possible to add another `Write nodes` option that iis not modifiable by the user? This would be sufficient to indicate that nodes are always written.
> 
> Maybe with the box for write nodes ticked by default and without the possibility of changing?

This is exactly what I meant. :wink:
