### ISSUE TITLE
[ConvDiff][CHT] Solid nodes not written

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/GiDInterface#822]
While creating a case I realized that the solid domain nodes are not written if initial conditions are not specified.

**Comment by jginternational** [comment]
I could not reporduce this, nor detect the missing nodes

**Comment by rubenzorrilla** [comment]
Create for instance the cooling cylinder example and remove the initial conditions in the solid. Nodes won't be written in the solid .mdpa.

**Comment by jginternational** [comment]
I've done that. The only difference between both cases is the Begin SubModelPart TEMPERATURE_Solid

**Comment by rubenzorrilla** [comment]
@jginternational you fixed this in #828 right?

**Comment by rubenzorrilla** [comment]
Closing then. Thanks!!!
