### ISSUE TITLE
The gid home website is down

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/GiDInterface#824]

**Comment by rubenzorrilla** [comment]
There is a power shutdown at CIMNE and most probably the server that hosts the website is down because of this. If this is the reason, which I think it is, it is expected to be solved tomorrow.

**Comment by jginternational** [comment]
@rubenzorrilla is right. Also CIMNE mail is down today

But the licence service is Online, so we can still use the cloud licences 😄
