### ISSUE TITLE
Geometry -> delete randomly switches back and forth for also deleting lower entitites

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/GiDInterface#825]
GiD 15.0.3
When deleting geometric entitites, it seems to switch back and forth every now and then between also deleting lower entitites or not. Perhaps it is linked to some hidden default.

**Comment by jginternational** [comment]
If you mean that the lower entities are erased (or not) when deleting entities as a user, it's a check that you can activate when deleting.

https://gidsimulation.atlassian.net/wiki/spaces/GRM/pages/2385547468/Delete

<img width="1027" alt="Screenshot 2021-08-06 at 18 38 26" src="https://user-images.githubusercontent.com/5918085/128543519-0ec707a7-c533-4f7b-afd7-9a6e0df608d0.png">

**Comment by mpentek** [comment]
I know that activation part, had the impression that recently it was jumping back and forth automatically. I will pay more attention to it, to see if it is so and what actions it can be linked to.
