### ISSUE TITLE
Add example to embedded

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#83]
Add the example Sphere in square tunnel, defined by @rubenzorrilla

**Comment by rubenzorrilla** [comment]
@jginternational it would be possible to change the sphere by a cylinder?

**Comment by jginternational** [comment]
Uuuuuh big trouble! @rubenzorrilla  I need to check what happends in the walls, where the cylinder intersects the surfaces, when the Octree tries to mesh there

**Comment by rubenzorrilla** [comment]
@jginternational If I do not remember wrong, if the cylinder width is larger than the fluid box one (of course in its both ends) no problem appears.

**Comment by jginternational** [comment]
We need to cut the length and improve the mesh

**Comment by jginternational** [comment]
@rubenzorrilla Test it when you can, I think it's still too large. Maybe we need to reduce the End time and the number of outputs

**Comment by rubenzorrilla** [comment]
@jginternational I've added the left side bar example button. Now the example is supposed to work but when meshing the volume it crashes...

**Comment by jginternational** [comment]
The crash is caused by the points in the surface. I'm fixing it

**Comment by jginternational** [comment]
Finished in #182
