### ISSUE TITLE
[PfemFluid] Other bug

### ISSUE THREAD

**Issue by AFranci** [KratosMultiphysics/GiDInterface#840]
When I open the default example of pfem fluid, I get this error
![image](https://user-images.githubusercontent.com/25818902/134473508-26d0e9e6-4831-4e69-bc3e-d77c7125f4bd.png)

@jginternational can you please take a look at it asap? Today I have to share the code with a student..

**Comment by jginternational** [comment]
You can try it

**Comment by AFranci** [comment]
Thanks, now it works!
