### ISSUE TITLE
[PfemFluid] another bug

### ISSUE THREAD

**Issue by AFranci** [KratosMultiphysics/GiDInterface#841]
I cannot run cases from GiD and it does not even create ProjectParameters.json

![Screenshot from 2021-09-23 10-59-16](https://user-images.githubusercontent.com/25818902/134480393-0d72c037-6dd8-4b57-8c90-5029cc077289.png)

**Comment by jginternational** [comment]
It should be fixed. This happends because of the namespace structure, that finds functions in ascending order
