### ISSUE TITLE
not printing calculation files

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/GiDInterface#851]
Recently I'm not able to generate the calculation files using the PfemFluidDynamicsApplication.

Branch: master
App: PfemFluidDynamicsApplication
GiD version: 15.1.3d

![imagen](https://user-images.githubusercontent.com/25640870/140939259-6f5c1db8-210d-4cc1-b13d-4555b3c03c34.png)

**Comment by miguelmaso** [comment]
fyi @AFranci

**Comment by AFranci** [comment]
Thank you @miguelmaso , I had the same issue..

**Comment by AlejandroCornejo** [comment]
![imagen](https://user-images.githubusercontent.com/26402605/140946077-98bf5f06-d20c-4834-8382-99fb970fafaf.png)

**Comment by jginternational** [comment]
Grrrrr You can try it now. Hope this fix it

**Comment by AFranci** [comment]
Now it's working!

**Comment by miguelmaso** [comment]
Thanks
