### ISSUE TITLE
[DEM] Problems with condition assignation in groups

### ISSUE THREAD

**Issue by jgonzalezusua** [KratosMultiphysics/GiDInterface#853]
Hi @jginternational, I am getting an error when I use the DEMApplication of GiDInterface:

`wrong # args: should be "spdAux::ProcGetFilesValues domNode"
wrong # args: should be "spdAux::ProcGetFilesValues domNode"
    while executing
"spdAux::ProcGetFilesValues"
    ("eval" body line 3)
    invoked from within
"eval [$procNode text]"
    (procedure "gid_groups_conds::eval_proc" line 69)
    invoked from within
"gid_groups_conds::eval_proc $proc $domNode"
    (procedure "_get_attribute_value" line 5)
    invoked from within
"_get_attribute_value $domNode $res"
    (procedure "get_domnode_attribute" line 6)
    invoked from within
"get_domnode_attribute $valueNode values"
    (procedure "::boundary_conds::Snit_method_fill_data_window_values" line 123)
    invoked from within
"$self _fill_data_window_values $w $domNode $valueNodes $title $level"
    (procedure "::boundary_conds::Snit_method_fill_data_window" line 15)
    invoked from within
"$self _fill_data_window $win.data $domNode $title"
    (procedure "::boundary_conds::Snit_methodapply_cond" line 155)
    invoked from within
"$self apply_cond -what apply -open_window $open_window"
    (procedure "::boundary_conds::Snit_methodexecute_select" line 47)
    invoked from within
".gid.central.boundaryconds.gg execute_select 108 121"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 [linsert $args 0 $self]"
    invoked from within
"::snit::RT.CallInstance ::boundary_conds::Snit_inst1 execute_select 108 121 "
    (command bound to event)`

This issue appears when I try to assign a group in the section "Assign conditions".  Regarding the version of the GidInterface, I am in newest update of the master branch. Could you help us?

**Comment by jginternational** [comment]
I could not reproduce the error using gid 15.1.2d and the master branch updated.

If this is still an open issue, i'll need more information (steps to reproduce it)

**Comment by jgonzalezusua** [comment]
It is closed because it's solved. Sorry for the inconvenience.
