### ISSUE TITLE
[All] Setting unrequired constrained status to true

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/GiDInterface#861]
When writing the  BC vector processes (e.g. assign_vector_variable_process) we set all the components to be constrained, that is `"constrained" :  [true,true,true]`. This enforces the addition of the three components of the variable of interest as DOF (e.g. `VELOCITY_X`, `VELOCITY_Y` and `VELOCITY_Z`) even for 2D simulations, which is a complete non-sense and a waste of memory.

In a 2D simulation, to fix a vector variable to zero, instead of
```json
"constrained" : [true,true,true],
"value" : [0.0,0.0,0.0]
```
we should automatically write
```json
"constrained" : [true,true,false],
"value" : [0.0,0.0,null]
```
By introducing such `null` keyword Kratos skips the constrained check, so it will never try to fix a DOF that doesn't exist in the nodal database.

**Comment by jginternational** [comment]
I think this enhacement is already done.

I've created a 2D structural case and this is the output.
```
"constraints_process_list" : [{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "AssignVectorVariableProcess",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Ground",
                "variable_name"   : "DISPLACEMENT",
                "interval"        : [0.0,"End"],
                "constrained"     : [true,true,false],
                "value"           : [0.0,0.0,null]
            }
        }],
```

Maybe in another app it can be different

**Comment by rubenzorrilla** [comment]
I think it is. Provided that the `null` keyword appears in the `value` array the corresponding third entry in the `constrained` array becomes meaningless.
