### ISSUE TITLE
[FluidDEM] Boundary conditions over particles does not work

### ISSUE THREAD

**Issue by jgonzalezusua** [KratosMultiphysics/GiDInterface#866]
Hello, I have a problem when using the FluidDEM application. I can assign boundary conditions over particles but in the DEM mdpa, GiD does not write these conditions.

**Comment by jginternational** [comment]
I'm not sure if I can reproduce this. I apply the "Boundary conditions over particles" over the Inlet group, selecting volumes in the entities selector.
The DEM.mdpa contains the submodelpart `DEM-VelocityBC_Spheres` but not a Conditions, since the velocity is applied directly over the nodes 

```
Begin SubModelPart DEM-VelocityBC_Spheres // GUI DEM-VelocityBC - DEM-VelocityBC - group identifier: Spheres
  Begin SubModelPartData // DEM-VelocityBC. Group name: Spheres
    FORCE_INTEGRATION_GROUP 0
    IDENTIFIER Spheres
  End SubModelPartData
  Begin SubModelPartNodes
      6611
  End SubModelPartNodes
End SubModelPart
```

**Comment by jginternational** [comment]
Sorry, I my fault. I meant that I applied over the spheres volume part
