### ISSUE TITLE
Compressible Navier Stokes

### ISSUE THREAD

**Issue by EduardGomezEscandell** [KratosMultiphysics/GiDInterface#869]
Hello, I'm describing here what the compressible fluid app would look like as we talked yesterday. It's a subapplication of the FluidDynamics one so it has a lot in common.

Available in 2D and 3D

About the mesh:
- Elements are:
    - Triangle: CompressibleNavierStokesExplicit2D3N
    - Quadrilateral: CompressibleNavierStokesExplicit2D4N
    - Tetrahedron: CompressibleNavierStokesExplicit3D4N
- Conditions are:
    - Line: LineCondition2D2N
    - Triangle: SurfaceCondition3D3N

Tree:
- Analysis type
    - Solution strategy:
        - Compressible Navier Stokes
    - Scheme: Runge Kutta 3
        - Forward Euler -> forward_euler
        - Runge Kutta 3 -> RK3-TVD
        - Runge Kutta 4 -> RK4
- Parts:
    - Element:
        - CompressibleNavierStokesExplicit
    - Fluid type (Remove this field)
    - Material (same as fluid)
    - DYNAMIC_VISCOSITY: 2e-5
    - CONDUCTIVITY: 0.024
    - SPECIFIC_HEAT: 722.14
    - HEAT_CAPACITY_RATIO: 1.4
- Time intervals: (Same as fluid)
- Boundary Conditions (applied to boundaries):
    - Slip
    - Custom Density -> scalar variable DENSITY
    - Custom Momentum -> vector variable MOMENTUM
    - Custom Total Energy -> scalar variable TOTAL_ENERGY
- Initial Conditions (applied to boundaries or inside):
    - Custom Density -> scalar variable DENSITY
    - Custom Momentum -> vector variable MOMENTUM
    - Custom Total Energy -> scalar variable TOTAL_ENERGY
- Solution:
    - Parallel configuration (same as fluid)
    - Strategy parameters:
        - Echo Level: 0
        - Compute Reactions: No
        - Use orthogonal subscales: No
        - Dynamic tau: Remove this field
        - Maximum iterations: Remove this field
        - Shock capturing:
            - None -> none
            - Physics-based -> physics_based
            - Entropy-viscosity method -> entropy_based
        - Tolerances: Remove these fields
    - Gravity (Same as fluid)
    - Time parameters:
        - Start time: 0.0
        - End time: 1.0
        - Automatic delta time: Yes
            - If yes:
                - CFL number: 0.1
                - Thermal Fourier number: 0.1,
                - Viscous Fourier number: 0.1,
                - Minimum delta time: 1e-8
                - Maximum delta time: 1e-3
            - If no:
                - Delta time: 1e-5
        - Linear solver: Remove this field
- Results
    - On nodes
    - GiD-Output (Same as fluid, but remove Drag)
    - VTK (Same as fluid)
- Units (Same as fluid)

The results to print are:
- nodal_results: `MOMENTUM, DENSITY, TOTAL_ENERGY, PRESSURE, TEMPERATURE, VELOCITY, NUMERICAL_ENTROPY*`
- gauss_point_results: `SHOCK_SENSOR^*, THERMAL_SENSOR^, SHEAR_SENSOR^`
- nodal_nonhistorical_results: `SOUND_VELOCITY, MACH`
- Elemental results: `ARTIFICIAL_MASS_DIFFUSIVITY*, ARTIFICIAL_BULK_VISCOSITY^, ARTIFICIAL_DYNAMIC_VISCOSITY^*, ARTIFICIAL_CONDUCTIVITY^*`

If possible, the results marked with...
- `*`: Necessary if shock capturing is `Entropy-viscosity method`
- `^`: Necessary if shock capturing is `Physics-based`
- `^*` Necessary if shock capturing is not `None`

I also append a sample case as an example
[sample_case.zip](https://github.com/KratosMultiphysics/GiDInterface/files/8123314/sample_case.zip)

I already started working on it back in september, you can try to use that (https://github.com/KratosMultiphysics/GiDInterface/pull/830) or start from scratch which may be easier.

I'll be glad to answer any doubts or questions.

**Comment by jginternational** [comment]
Hi @EduardGomezEscandell 

You can do most of the things in the issue, see that it's just edit the xml files.

I'll check the Results part, maybe is a little bit tricky

**Comment by EduardGomezEscandell** [comment]
Closing because I will no longer work on this issue; if anyone whants to take over, be my guest.
