### ISSUE TITLE
[PfemFluid] Wave monitoring process

### ISSUE THREAD

**Issue by AFranci** [KratosMultiphysics/GiDInterface#873]
hi @jginternational 

I am trying to add to the PFEM-Fluid interface a process to monitor the wave height. 

I have done a first implementation and I obtained something close to what we need and I would need your help to conclude it. 
In particular, I need to put inside "[" "]" a list and give the possibility to add more points from the interface in the coordinates button (up to now, only one node can be given).

At the current point I can write from the user input the following:

    "output_processes"     : {
        "output_list" : {
            "python_module" : "wave_height_output_process",
            "kratos_module" : "KratosMultiphysics.PfemFluidDynamicsApplication",
            "Parameters"    : {
                "model_part_name"           : "PfemFluidModelPart",
                "coordinates"               : [0.0,0.0,0.0],
                "wave_calculation_settings" : {
                    "mean_water_level"       : 0,
                    "relative_search_radius" : 2
                },
                "output_file_settings"      : {
                    "file_name"   : "pfem_<i>",
                    "output_path" : "gauges"
                },
                "time_between_outputs"      : 0.01
            }
        }
    }

While I would need:
```
    "output_processes"     : {
        "output_list" :  **[**
{
            "python_module" : "wave_height_output_process",
            "kratos_module" : "KratosMultiphysics.PfemFluidDynamicsApplication",
            "Parameters"    : {
                "model_part_name"           : "PfemFluidModelPart",
                "coordinates"               : **[**
[0.0,0.0,0.0]
**..here more coordinates provided by the user...**
**]**,
                "wave_calculation_settings" : {
                    "mean_water_level"       : 0,
                    "relative_search_radius" : 2
                },
                "output_file_settings"      : {
                    "file_name"   : "pfem_<i>",
                    "output_path" : "gauges"
                },
                "time_between_outputs"      : 0.01
            }
        }
**]**
    }
```
The implementation is done in PfemFlui/ProcessForWaveMonitoring. 

Can you help me with this?

Tell me if you need more details

Regards,

Alessandro

**Comment by AFranci** [comment]
Hola Javi, como lo ves?
Gracias 
Alessandro

**Comment by jginternational** [comment]
Ciao Alessandro

Tras mirar con calma e intentar resolverlo, he llegado a la conclusion de que igual hay que cambiar un par de cosas.
Si quieres que se aplique a varios nodos, es posible que lo que quieras es un submodelpart con los nodos? En lugar de tener las coordenadas como parámetros (para el usuario introducir coordenadas puede ser más costoso que seleccionar nodos)

**Comment by AFranci** [comment]
Hola @jginternational muchas gracias por la ayuda! te comento en #877
