### ISSUE TITLE
Cannot use GiD 15.1.5d

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/GiDInterface#874]
Hi guys, this is not interface related but I do not know where else to post this. I just installed GiD 15.1.5d and after creating a group I cannot right-click it to assign entities. After right-clicking I get the following error msg and cannot proceed. I also reinstalled GiD and get the same error. Btw: why is there no zipped folder with the executable anymore? Only the deb file :(

acan't read "::GidPriv(CurrentTheme,path_alternative,0,generic)": no such element in array
can't read "::GidPriv(CurrentTheme,path_alternative,0,generic)": no such element in array
    while executing
"file join $::GidPriv(CurrentTheme,$try_path,$auxthemesize,$category) $filename"
    (procedure "gid_themes::LoadImage" line 55)
    invoked from within
"gid_themes::LoadImage $filename $IconCategory"
    (procedure "gid_themes::GetImage" line 16)
    invoked from within
"gid_themes::GetImage clone.png small_icons"
    (procedure "Groups::ContextualMenu" line 22)
    invoked from within
"Groups::ContextualMenu .gid.central.wlay.body.nb.f_groups.middle.t 1 1603 129"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $ch [list $self [$tree selection get] $X $Y]"
    (procedure "::fulltktree::Snit_methodcontextual" line 59)
    invoked from within
".gid.central.wlay.body.nb.f_groups.middle.t contextual 55 21 1603 129"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 [linsert $args 0 $self]"
    invoked from within
"::snit::RT.CallInstance ::fulltktree::Snit_inst1 contextual 55 21 1603 129"
    (command bound to event)

**Comment by KlausBSautter** [comment]
![output2](https://user-images.githubusercontent.com/26179700/166973257-a11cec79-e58c-45fa-80f9-65273e3bfcdd.gif)

**Comment by KlausBSautter** [comment]
I am using the new Ubuntu 22.04, has GiD been tested in that version?

**Comment by rubenzorrilla** [comment]
You can directly contact the GiD support team by clicking the question mark in the bottom right corner of their website. See below. Alternatively, you can email them in `gid@cimne.upc.edu`.


![gid_support](https://user-images.githubusercontent.com/19992225/167093623-87f95048-ab4d-47a3-9796-5f89b7a13d2d.jpg)

Closing as this is not directly related to Kratos.

**Comment by KlausBSautter** [comment]
Alright thanks ! :)
