### ISSUE TITLE
Linking Kratos

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/GiDInterface#875]
Hi, I have another problem. I followed all the steps on the main page to link my Kratos folder to GiD. It seems to work, as I can see the Kratos problemtype and when I open it there is all the applications and stuff. 
BUT: It always asks me to download the Kratos python package.
![grafik](https://user-images.githubusercontent.com/26179700/166972295-2468be6c-b15f-47e5-8098-8998dbfeea61.png)

This is a little bit annoying as I do not want to download, I have it linked. So why does it ask everytime?

Cheers

**Comment by mpentek** [comment]
This seems to be linked to some new aspects, since the Kratos 9.0 problemtype (python wheel packages - with version 3.10). @jginternational @roigcarlo did you receive similar feedback? Did someone test it?

**Comment by VeronikaSinger** [comment]
Hi I also have the same problem in windows.

**Comment by jginternational** [comment]
Dear @KlausBSautter and @VeronikaSinger 

I misunderstood the problem.

I think that, if you do not want to use the pip packages and use the local compiled version, you should apply the proper configuration. Follow the steps:
- Go to Preferences,
- Click on the dropdown and select the local compiled version.
- Apply
- Close GiD and reload Kratos. The message should no longer appear.

![image](https://user-images.githubusercontent.com/5918085/167606902-1e55064b-b0b0-4185-ad4c-f997eac3872a.png)

![image](https://user-images.githubusercontent.com/5918085/167607080-3c8eb6c7-6241-4f26-96fe-d70cbab833c0.png)


In addition, I think that it will be positive to remove the initial check of dependencies. Maybe a good moment to check them is when the user tries to run, instead on check them in the start up.

**Comment by KlausBSautter** [comment]
Cool, thanks that works! Maybe we can add this to the general description on this GitHub page.
