### ISSUE TITLE
Error running PFEM 2D FSI examples

### ISSUE THREAD

**Issue by alexbrownsoft** [KratosMultiphysics/GiDInterface#886]
While running PFEM 2D FSI examples, below errors occur:

"Problem Writing MDPA block:
Element SurfaceRigidLagrangianElement2D2N Linear (2 nodes) not available for line entities on group Interface
End problems"

I assume this is some bug in GidInterface, is that correct?

**Comment by rubenzorrilla** [comment]
Ping @AFranci @jginternational

**Comment by jginternational** [comment]
Hi @alexbrownsoft 

Could you attach a zip containing the case?

**Comment by alexbrownsoft** [comment]
Dear Sir,

This is the official example in Gid, examples->pfem fluid->pfemfluid damage break fsi 2d

The files are also attached.
[examplePFEMfsi.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/9423896/examplePFEMfsi.gid.zip)

**Comment by alexbrownsoft** [comment]
Dear Sir,

Is there any update on this? @jginternational

**Comment by jginternational** [comment]
Hi @alexbrownsoft , thanks for reporting.
You were right, it was an old bug, that produced this one like a week ago.

It should be fixed now
