### ISSUE TITLE
Multiple model parts for Convection-Diffusion cases.

### ISSUE THREAD

**Issue by SADPR** [KratosMultiphysics/GiDInterface#900]
Convection-Diffusion cases don't allow to use multiple parts. 
![image](https://user-images.githubusercontent.com/61457043/191040487-7c498f15-02b5-4b54-a478-4bb12657a793.png)
@jginternational is this easy to fix? I am working with complex geometries so the use of the GiD interface saves me lots of time. 
Thanks! @

**Comment by jginternational** [comment]
@SADPR Are you sure that you are using the latest version (master branch)? I think this bug was fixed long time ago https://github.com/KratosMultiphysics/GiDInterface/commit/317e7e4c6d8ae1860807f52911b6b520884e34c6
