### ISSUE TITLE
Kratos conditions in Gid 16.1.0, MacOs

### ISSUE THREAD

**Issue by NickNick9** [KratosMultiphysics/GiDInterface#904]
Hi everybody,

I have an issue on Gid when I open a Gid file already existing made as a kratos problemtype.
In this file I have all the informations about IC, BC, materials, ecc, but I cannot neither see nor modify them.

I have tried clincking on Data-->Conditions, but nothing happend.

Even re-selecting the problemtype --> kratos, and choosing "Reset to new problem type" or "Transform to a new problem type" does not lead to any results.

I attach here my gid file I'm trying to open.

[Embedded_fluid_domain_RZ.gid(2).zip](https://github.com/KratosMultiphysics/GiDInterface/files/9666672/Embedded_fluid_domain_RZ.gid.2.zip)

Thanks,
Nicolò

**Comment by jginternational** [comment]
I could open your model fine in windows, so I assume the problem has something to do with Mac

![image](https://user-images.githubusercontent.com/5918085/193796150-936057ac-39ec-424b-8c1e-5e8138cf8930.png)

I'll do some extra testing.

If you open kratos (GiD Menu > Data > Problemtype > Kratos), is it loading fine?

**Comment by NickNick9** [comment]
Hi Javi,

Sorry for answering you so late.
Now using the new version 16.1.1d I see that I can open the Gid file, but I
cannot see the groups that are inside. Can you see them?

Best regards,
Nicolò

Il giorno mar 4 ott 2022 alle ore 12:25 Javi Gárate <
***@***.***> ha scritto:
