### ISSUE TITLE
FSI mapping Fluid Structure

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#91]
Fluid Interface condition should know if it's positive or negative in the double sided interfaces

A new json section must be writen in the coupled part

**Comment by jginternational** [comment]
@rubenzorrilla Add the resulting json please

**Comment by rubenzorrilla** [comment]
"coupling_solver_settings"  : {
        "problem_data"    : {
            "parallel_type" : "OpenMP"
        },
        "solver_settings" : {
            "coupling_scheme"              : "DirichletNeumann",
            "solver_type"                  : "partitioned_fsi_dirichlet_neumann_solver",
            "nl_tol"                       : 1e-7,
            "nl_max_it"                    : 25,
            "solve_mesh_at_each_iteration" : true,
            "coupling_strategy"            : {
                "solver_type" : "MVQN_recursive",
                "w_0"         : 0.825,
                "buffer_size" : 7
            },
            "mesh_solver"                  : "mesh_solver_structural_similarity",
            "mesh_reform_dofs_each_step"   : false,
            "structure_interfaces_list"      : ["StructureInterface2D_StructureInterface"],
            "fluid_interfaces_list"          : ["FluidNoSlipInterface2D_FluidInterface"]
        },
        "mapper_settings"              : [{
            "search_radius_factor"                  : 2.0,
            "mapper_max_iterations"                 : 200,
            "mapper_tolerance"                      : 1e-12,
            "fluid_interface_submodelpart_name"     : "FluidNoSlipInterface2D_FluidInterface",
            "structure_interface_submodelpart_name" : "StructureInterface2D_StructureInterface"
        }]
    }
