### ISSUE TITLE
Problem in mesh generation with Kratos

### ISSUE THREAD

**Issue by JuliaArce** [KratosMultiphysics/GiDInterface#910]
Hi!
I would like to ask for help as when trying to generate mesh with GiD - problemtype: Kratos, a message appears "Mesh not generated. There is no geometry, or there is nothing selected to be meshed".
I have reinstalled both GiD and Kratos for GiD; saved the project; tried and mesh with different element sizes... but the error keeps displaying. A screenshot is provided below:

![imagen](https://user-images.githubusercontent.com/119288339/204223968-24eb0ea4-f20f-4715-99a1-f8a56e2f256e.png)

Thank you in advance,

Julia

**Comment by ipouplana** [comment]
Hi @jginternational, I also tested this in the Fluid 2D problemtype and got the same error... 

It seems that every time I want to mesh a surface, this gets automatically set as "No mesh" and thus no mesh can be generated. I tried with "Reset mesh data", and even explicitly defining the "Mesh" option on the surface, but when I hit "Generate mesh..." the surface is automatically set as "No mesh" again...

**Comment by rubenzorrilla** [comment]
Did you assign a part in the tree? From the snapshot it seems you didn't. If so, this is the problem.

**Comment by ipouplana** [comment]
Thanks @rubenzorrilla . I did not think about that ^_^'

**Comment by rubenzorrilla** [comment]
Note that you can check how to set a case in the "pre-loaded" examples (the pencil and paper button on top of the settings one).

Closing as it seems to be solved. Feel free to reopen if needed.

**Comment by JuliaArce** [comment]
Thank you very much Dr. Zorrilla!!

I did assign a "part" and finally everything worked properly!


Best regards,

Julia




Missatge de Rubén Zorrilla ***@***.***> del dia dl., 28 de
nov. 2022 a les 12:04:

**Comment by jginternational** [comment]
I know that the Fluid application should warn better about this

**Comment by JuliaArce** [comment]
It's okay, at least it works :)

Thanks,

Julia

El dimarts, 29 de novembre de 2022, Javi Gárate ***@***.***>)
va escriure:
