### ISSUE TITLE
[Fluid] Wall law project parameters

### ISSUE THREAD

**Issue by ncrescenzio** [KratosMultiphysics/GiDInterface#923]
Hi,

I think that the project parameters that are written when using the wall law condition are not correct. 
Shouldn't it be `"wall_model_name"` instead of `"wall_model"`? 

Here the code from the python process in the `FluidDynamicsApplication`:

https://github.com/KratosMultiphysics/Kratos/blob/b04aa01d2f368c51db283cd501aafe7e9b42384b/applications/FluidDynamicsApplication/python_scripts/apply_wall_law_process.py#L96-L103

Thanks

**Comment by rubenzorrilla** [comment]
Seems so. Thanks for reporting.
