### ISSUE TITLE
make the StructuralMechanics Independent

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/GiDInterface#93]
Hi Javi,
please make the StructuralMechanicsApplicaion independent
cheers
Riccardo

**Comment by jginternational** [comment]
Need to check:

- [ ] Procs -> visibility of nodal conditions
- [ ] Write -> All the writting procs must be implemented

**Comment by loumalouomega** [comment]
@jginternational Have you checkewd it works?, several things have changed in the way the structural works, now we use the materials.json instead of materials.py. Use the branch feature-porting-elements to check it

**Comment by jginternational** [comment]
@loumalouomega It works as well as it worked using the Solid Mechanics. There are some other branches to implement new develompents and now both apps will be free to implement new features

**Comment by loumalouomega** [comment]
The thing is that the old implementation will not work, so this is can not been closed

**Comment by jcotela** [comment]
@loumalouomega the initial goal was just to duplicate shared code, so that changes can be made in one without altering the other. I understand this has been accomplished. Now we can start work in incorporating the changes you are mentioning.
Have you identified something that is broken right now, so that we can give it higher priority?

**Comment by loumalouomega** [comment]
We can close the issue, but the resulting output will not work with the current implementation.

The main difference is that we don't use materials.py anymore, instead we use the materials.json. Besides the UpdatedLagrangianElement is not avalaible and just the most basic CL are available.

**Comment by jcotela** [comment]
Yes, I agree. However, until we start changing the scripts themselves, models made with this PT will still launch the old scripts. Just so I understand, is this thing of the material definition currently broken? Or is it just that we are still calling the SolidMechanics stuff under the hood?

Maybe we could set up a project to organize the transition? I'm willing to help but I'm a bit lost regarding what has to be changed.

**Comment by jginternational** [comment]
There is a branch for the development of the materials.json file, but I have not recieved any example nor request.

Now it is working almost perfect. There is a little issue in the Structural (a runtime warning) due to some multiple declaration of objects. Nothing to do with the problemtype.

**Comment by loumalouomega** [comment]
The current work will work with the StructuralApplication in the master, but the changes are in the feature-porting-elements branch. You can find an example in the tests from the core, called test_materials.py and you will se the material.json example. @jginternational  Tomorrow I will call you to give you more details, which is your Skype?

**Comment by jginternational** [comment]
@loumalouomega Please, check the structural in the problemtype 

Use only An element, fix displacement and apply a point load to test the materials.json file

**Comment by jginternational** [comment]
Sorry, I didn't see the new task

**Comment by loumalouomega** [comment]
Can I update without overwriting what I have currently? I mean, during some time I will be using the legacy problem type, and update will destroy that

**Comment by loumalouomega** [comment]
@jginternational That why it is important to remain the branches during development

**Comment by jginternational** [comment]
We are working in a branch just for this (https://github.com/KratosMultiphysics/GiDInterface/tree/feature-porting-element-structural)

**Comment by loumalouomega** [comment]
@jginternational Nice
