### ISSUE TITLE
[Dam] Write Elements in Condition Process

### ISSUE THREAD

**Issue by joaquinirazabal** [KratosMultiphysics/GiDInterface#932]
Hi, @jginternational. I am facing a problem that I do not know how to solve in the Dam app.

When assigning one condition I also need to write in the submodelpart the Elements "inside" that conditions. Here you have an example in 2D.

![Uplift](https://user-images.githubusercontent.com/25591219/231126636-9815ebf8-2c2b-4a22-a477-ad7f3b7cb7d0.png)

I have a contact surface composed by 2D4N elements and Line 1 and Line 2 with 2D2N lines and nodes. When writting the mdpa I want it to write the nodes, the elements and the line conditions. Is it possible?

The process is UpliftConditionsProcess.

Thanks in advance.

**Comment by jginternational** [comment]
Hi @joaquinirazabal 
The fast answer is no, conditions dont print elements. Elements are only printed in Parts, and Parts do not print conditions.

The long answer is that, of course, it can be programed in the ::Dam::write::writeModelPartEvent . You will need to define exactly what should be printed and get rid of the current code, that prints everything in the standard way

**Comment by joaquinirazabal** [comment]
Thanks for the tips, @jginternational. I'll let you know with my advances.

**Comment by joaquinirazabal** [comment]
Finally I found a workaround, thanks for the advices!
