### ISSUE TITLE
[GPFEM with GiD] No application corresponding to solid PFEM in recent releases

### ISSUE THREAD

**Issue by junohc** [KratosMultiphysics/GiDInterface#937]
Hi everybody,
I would like to solve a geotechnical problem (CPT tests) with PFEM and CASM constitutive model.

This using the GiD interface and Kratos solver. I don't succeed in getting the interface for PFEM application as in this video :
https://www.youtube.com/watch?v=L0b8jP33FZs&t=1584s from L. Monforte Vila
The ones I have is for PFEM fluid and PFEM/DEM and PFEM Thermic accordingly to the list of apps present in GidInterface repository 
https://github.com/KratosMultiphysics/GiDInterface

I used the developer manual to install GidInterface and made the link Gid to Kratos.
My version of Kratos is 9.3.1 from repository https://gitlab.com/pfem-research/kratos 
and I installed it with Release option. 
The installed apps are in the following image :
![image](https://user-images.githubusercontent.com/129756574/233800899-60d75fec-b908-4b6f-ae34-dae21b18db1e.png)

Also i saw that in folder Pfemapplication there is a folder called  Kratos_Pfem_Solid_Mechanics_Application.gid, in which there is part of what I need on the gid interface but I don't understand how to implement it in the software.

Best regards,
Arthur

**Comment by AFranci** [comment]
Hi @junohc 
For geotechnical applications with PFEM using PFEMapplication, you should ask @lluis-mv 
Regards,
Alessandro

**Comment by junohc** [comment]
Hi everybody, 
Thank you very much for all the answers and sorry that i did not ping you at first @lluis-mv instead of only quoting you. This would have been faster but it is the first I use github...
I will email you right away from my university email account and close the issue.
Regards, 
Arthur
