### ISSUE TITLE
Geometries in mdpa

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#939]
We are trying to define a way to write the mdpa file, replacing the elements and conditions for geometries.
![image](https://github.com/KratosMultiphysics/GiDInterface/assets/5918085/3b9fc6bc-0385-4066-ad61-878c4a2d7d69)

### What we have now:

Begin nodes
 1 0 1 0
 2 0 0 0
 3 1 0 0
End nodes

Begin Elements Triangle2D2N
 1 1 2 3
End elements

Begin Conditions LineCondition2D2N
1 1 2
2 2 3
3 3 1
End Conditions

Begin Submodelpart sm1
Begin SubModelPartNodes
1
2
3
End SubModelPartNodes
Begin SubModelPartElements
1
End SubModelPartElements
End Submodelpart

Begin Submodelpart sm2
Begin SubModelPartNodes
1
2
3
End SubModelPartNodes
Begin SubModelPartConditions
1
2
3
End SubModelPartConditions
End Submodelpart
.
.

Then in the json, we refer to the submodelparts to apply processes.

### What we want:
Begin nodes
 1 0 0 0
 2 1 0 0
 3 0 1 0
End nodes

Begin Geometry Triangle2D2N
 1 1 2 3
End Geometry 

Begin Geometries Line2D2
2 1 2
3 2 3
4 3 1
End Geometry 

Begin Submodelpart sm1
Begin SubModelPartNodes
1
2
3
End SubModelPartNodes
Begin SubModelPartGeometries 
1
End SubModelPartGeometries  
End Submodelpart

Begin Submodelpart sm2
Begin SubModelPartNodes
1
2
3
End SubModelPartNodes
Begin SubModelPartGeometries 
2
3
4
End SubModelPartGeometries 
End Submodelpart

And, in the json, we can assign the element or condition to the submodelpart

### Changes
- Notice that now we can use GiD ids instead of creating a new set of ids. This will improve the performance, since we can write the mdpa usign GiD C++ functions instead of using the current TCL code.
- This new way lets Kratos developers decide the "overlap" policy. What happends if I assign 2 conditions to the same geometry? An application may want to keep the same Id and another application may want to generate a new id.
- Need to be carefull in MPI with numerations

@rubenzorrilla @RiccardoRossi 
https://github.com/KratosMultiphysics/GiDInterface/issues/80

**Comment by loumalouomega** [comment]
At last!

**Comment by sunethwarna** [comment]
Is the sections such as `ElementData` gonna be removed from mdpa as well (no complaints) which is used to have `LOCAL_AXIS` information? How will this change for cases with something like beams?

**Comment by jginternational** [comment]
You can now use the MDPA Generator to create this geometries.

On top of the tree you can choose the write mode between classical "Element and conditions" and "Geometries".
See https://github.com/KratosMultiphysics/GiDInterface/pull/940#issuecomment-1602959782 for more information

I have added support for NodalData such as Radius for circles/spheres, so I hope we can add the ElementData also @sunethwarna

**Comment by jginternational** [comment]
This is in the latest release 9.4.2 

Fluid and Geomechanics applications can use it
Check Kratos preferences in order to enable it
