### ISSUE TITLE
[Structure] Eigenvalue analysis

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/GiDInterface#946]
When doing an eigenvalue analysis (i.e. setting `Solver type` to `Eigenvalue`) the elimination builder and solver needs to be used in order to remove the zeroes in the diagonal. This requires to add this to the `solver_settings` section of the `ProjectParameters.json`
```json
    "builder_and_solver_settings" : {
        "use_block_builder" : false
    }
```
I think this must be automatically set by the GUI. If not, I think we should add this to the GUI by defaulting to the value above.

**Comment by jginternational** [comment]
Is there any chance for the user to change it? Can a user chose `true` or `false` in that value?

**Comment by rubenzorrilla** [comment]
In the eigenvalue context switching it to `true` turns to an error.

**Comment by rubenzorrilla** [comment]
@jginternational what is the status of this?
