### ISSUE TITLE
[PFEM Fluid] bug when loading the Ptype

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/GiDInterface#950]
When I open the ptype (latest ptype + GiD 16.1.6d ) it returns this error message and does not allow to use it:

![imagen](https://github.com/KratosMultiphysics/GiDInterface/assets/26402605/96d9fa4f-8b17-4e97-8913-a134c28fee83)

@AFranci @jginternational

**Comment by AlejandroCornejo** [comment]
Complete mssg:

![imagen](https://github.com/KratosMultiphysics/GiDInterface/assets/26402605/53b96a87-5e58-46bf-971f-22d905f3012e)

**Comment by jginternational** [comment]
Hi @AlejandroCornejo 

It is a typo in the file app.json detected in a previous issue.
#942 

FIxed in a new commit in master branch
