### ISSUE TITLE
GiDx64.16.1.4d + Debian 12 error

### ISSUE THREAD

**Issue by ncrescenzio** [KratosMultiphysics/GiDInterface#966]
When I try to generate a mesh I get the following error:

```
expected boolean value but got "1SoftwareOpenGL"
expected boolean value but got "1SoftwareOpenGL"
    while executing
"if { $::GidPriv(ProgressInMeshing,More) } {             
        #deletedata also does a $w.fplot.c delete data
        if { [catch { $graph(plot) del..."
    (procedure "ProgressInMeshing::DoResize" line 4)
    invoked from within
"ProgressInMeshing::DoResize .gid.wprogress"
    ("after" script)
```

I am using Debian GNU/Linux 12 (bookworm).

Any suggestion?

**Comment by ncrescenzio** [comment]
I tried and got the same error

**Comment by pasenau** [comment]
It seems that there is a problem with GiD preferences. 
Try to reset preferences with the 'Repair GiD' entry or executing `$HOME/GiDx64/gid-16.1.8d/gid_safe_mode`.
And select the option 'Reset preferences' from the window: 
![imagen](https://github.com/KratosMultiphysics/GiDInterface/assets/20422435/0c8e663c-0fe1-432f-af4e-56cc40d9ea2e)

If problem persists, please can you upload the example and the preferences files located at `$HOME/.gid/16.1.8d/` ? 
Thanks
