### ISSUE TITLE
 [Dam] Problem with tables assignment in mdpa

### ISSUE THREAD

**Issue by joaquinirazabal** [KratosMultiphysics/GiDInterface#981]
Hi, @jginternational, I am facing an error when assigning tables to a model part.

When I create a problem (find attached an example) everything works properly, but the list of tables associated to the SubModelPart BOFANGTEMPERATURE_Reservoir_temperature:_Bofang_Auto1 are not written like expected:
    Begin SubModelPartTables
            1
            2
    End SubModelPartTables

I have been trying to solve it, but I do not find the way, can you help me?

Thank you!

[TestTables.gid.zip](https://github.com/user-attachments/files/15913010/TestTables.gid.zip)

**Comment by jginternational** [comment]
Hi @joaquinirazabal 

I'll take a look at it after the GiD Convention, on July 3rd

**Comment by joaquinirazabal** [comment]
Great, thanks!

**Comment by joaquinirazabal** [comment]
Hi, @jginternational, did you have time to take a look at this? Thanks!

**Comment by jginternational** [comment]
Yes! I can not find the cause of the failure in this model. In addition it seems to be old in some parameters:
Day_Max_Temp -> Day_Ambient_Temp

if you generate the model again it works fine.

Please test it and write back

**Comment by joaquinirazabal** [comment]
Sorry, I made some changes last weeks. Here it is the new problem: 
[test_tables.gid.zip](https://github.com/user-attachments/files/16126926/test_tables.gid.zip)

When running it an error arises "Get value from empty table".

The Bofang condition submodelpart needs to be defined in the MDPA as:

Begin SubModelPart BOFANGTEMPERATURE_Reservoir_temperature:_Bofang_Auto1 // Group Reservoir temperature: Bofang Auto1 // Subtree BOFANGTEMPERATURE
Begin SubModelPartNodes
1
3
5
9
13
17
21
26
32
38
45
52
60
68
77
86
96
107
117
128
138
End SubModelPartNodes
Begin SubModelPartTables
1
2
End SubModelPartTables
End SubModelPart

But the tables are not written.
